### ISSUE TITLE
xunit reporter crashes when the output directory does not exist

### ISSUE THREAD

**Issue by sebastien-fragnaud** [mochajs/mocha#1311]
I was having the following error :
```
/Users/me/my_project/node_modules/mocha/lib/mocha.js:137
    if (!_reporter) throw new Error('invalid reporter "' + reporter + '"');
                          ^
Error: invalid reporter "xunit-file"
    at Mocha.reporter (/Users/me/my_project/node_modules/mocha/lib/mocha.js:137:27)
    at Object.<anonymous> (/Users/me/my_project/node_modules/mocha/bin/_mocha:191:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
make: *** [functional-test] Error 8
```

Because the output directory didn't exist. I created it, and now it's working. I believe there should be at least a better error message...

Thanks :-)

**Comment by jbnicolai** [comment]
Feel free to create a PR.

Closing the issue as it's been inactive for over a year.
