### ISSUE TITLE
Error: spawn --harmony ENOENT;  mocha --harmony on node 0.12.0 and mocha 2.2.0

### ISSUE THREAD

**Issue by thecaddy** [mochajs/mocha#1583]
Not sure what happened in a day but my builds are failing and all signs point to something related with mocha and using the harmony flag.  I have been on 0.12.0 for a while now and have tried every 2.X version of mocha.  The error looks like its process related but all my apps run fine with every other package.

Do you guys have any ideas?

```
mocha --harmony
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn --harmony ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

```
 mocha --harmony-generators
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn --harmony-generators ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by danielstjules** [comment]
Thanks for pointing that out! It should be fixed once https://github.com/mochajs/mocha/pull/1567 gets merged

**Comment by thecaddy** [comment]
Awesome, thats great to hear.  Thanks for the quick response!

**Comment by danielstjules** [comment]
Fixed https://github.com/mochajs/mocha/pull/1567 :)
