### ISSUE TITLE
`"before each" hook` messages do not include any information on cause of error

### ISSUE THREAD

**Issue by mikemaccana** [mochajs/mocha#1588]
Where the message `1) "before each" hook` in red appears, there is no indication of the cause of the message - whether it's:

 - a timeout
 - a broken assertion
 - An Error being thrown
 - done() being called with a truthy err
 - Something else

The docs also don't seem to cover handling these errors.

**Comment by danielstjules** [comment]
Closing as that doesn't seem to be the case with Mocha 2.2.1:

``` javascript
// ---------------------------------------------
// Timeout
// ---------------------------------------------

$ cat example.js
describe('example', function() {
  beforeEach(function(done) {
    setTimeout(done, 10000);
  });

  it('test', function(done) {
    done();
  });
});

danielstjules:~/git/mocha (master =)
$ ./bin/mocha example.js


  ․

  0 passing (207ms)
  1 failing

  1) example "before each" hook:
     Error: timeout of 200ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (lib/runnable.js:170:19)

// ---------------------------------------------
// Broken assertion
// ---------------------------------------------

$ cat example.js
var assert = require('assert');

describe('example', function() {
  beforeEach(function(done) {
    assert.ok(false);
    done();
  });

  it('test', function(done) {
    done();
  });
});

danielstjules:~/git/mocha (master =)
$ ./bin/mocha example.js


  ․

  0 passing (5ms)
  1 failing

  1) example "before each" hook:
     AssertionError: false == true
      at Context.<anonymous> (example.js:5:12)
      at Hook.Runnable.run (lib/runnable.js:233:15)
      at next (lib/runner.js:271:10)
      at Object._onImmediate (lib/runner.js:292:5)

// ---------------------------------------------
// Error being thrown
// ---------------------------------------------

$ cat example.js
describe('example', function() {
  beforeEach(function(done) {
    throw new Error('ohno!');
    done();
  });

  it('test', function(done) {
    done();
  });
});

danielstjules:~/git/mocha (master =)
$ ./bin/mocha example.js


  ․

  0 passing (4ms)
  1 failing

  1) example "before each" hook:
     Error: ohno!
      at Context.<anonymous> (example.js:3:11)
      at Hook.Runnable.run (lib/runnable.js:233:15)
      at next (lib/runner.js:271:10)
      at Object._onImmediate (lib/runner.js:292:5)

// ---------------------------------------------
// Truthy error
// ---------------------------------------------

$ cat example.js
describe('example', function() {
  beforeEach(function(done) {
    done(true);
  });

  it('test', function(done) {
    done();
  });
});

danielstjules:~/git/mocha (master =)
$ ./bin/mocha example.js


  ․

  0 passing (5ms)
  1 failing

  1) example "before each" hook:
     Error: done() invoked with non-Error: true
      at lib/runnable.js:239:25
      at Context.<anonymous> (example.js:3:5)
      at Hook.Runnable.run (lib/runnable.js:233:15)
      at next (lib/runner.js:271:10)
      at Object._onImmediate (lib/runner.js:292:5)
```

**Comment by muraiki** [comment]
In Mocha 2.3.3, if done() is called more than one time in a single beforeEach, the only error output is `1) "before each" hook`

This happened to me when I forgot to remove a done() while refactoring. D'oh!

**Comment by muraiki** [comment]
Also, I should note that I only got an error when running in watch mode. No error was displayed when mocha was run normally.
