### ISSUE TITLE
Tests failing because mocha itslef...

### ISSUE THREAD

**Issue by salboaie** [mochajs/mocha#1607]
/*
 This simple test should pass but it simple fails because of mocha . Also, very strange but  the order of calls in setTimeout function create various wrong behaviours. 
*/
```javascript
function EventDispatcher(){
    var _callback = null;
    this.dispatch = function(){

        _callback();
    }

    this.on = function(type, callback){
        _callback = callback;
    }
}

var clientDoctor        = new EventDispatcher();
var clientPatient       = new EventDispatcher();

var clientDoctor2       = new EventDispatcher();

describe("Test notification clientDoctor2" , function(){

    it("Should dispatch clientDoctor2", function(done){
        clientDoctor2.on("Notifications.js", function(){
            done();
        });
    })
});


describe('Test notification for both doctor and patient', function() {

    it("Should dispatch clientDoctor", function(end){
        clientDoctor.on("RequestAccess.js", function () {
            end();
        });
    })

    it("Should dispatch clientPatient", function(end){
        clientPatient.on("RequestAccess.js", function () {
            end();
        });
    })
});


setTimeout(function(){
    console.log("Dispatching...");
    clientDoctor2.dispatch();
    clientDoctor.dispatch();
    clientPatient.dispatch();
}, 100)
```

Link to code: https://github.com/salboaie/mocha-fail/blob/master/MochaFail.js

**Comment by danielstjules** [comment]
Not a "mocha fail" :) You're dispatching before the specs even get a change to run. Furthermore, the callback for one of those objects isn't even set, so it was causing an error. The following changes make it a bit more evident:

``` javascript
function EventDispatcher() {
  var _callback = null;

  this.dispatch = function() {
    console.log('--Dispatching--');
    // You need to make sure this isn't null
    if (_callback) _callback();
  }

  this.on = function(type, callback) {
    _callback = callback;
  }
}

var clientDoctor  = new EventDispatcher();
var clientPatient = new EventDispatcher();
var clientDoctor2 = new EventDispatcher();

describe("Test notification clientDoctor2" , function() {
  it("Should dispatch clientDoctor2", function(done) {
    clientDoctor2.on("Notifications.js", done);
  });
});

describe('Test notification for both doctor and patient', function() {
  it("Should dispatch clientDoctor", function(done) {
    clientDoctor.on("RequestAccess.js", done);
  });

  it("Should dispatch clientPatient", function(done) {
    clientPatient.on("RequestAccess.js", done);
  });
});

setTimeout(function(){
    clientDoctor2.dispatch();
    clientDoctor.dispatch();
    clientPatient.dispatch();
}, 100)

```

```
$ mocha test.js


  Test notification clientDoctor2
--Dispatching--
    ✓ Should dispatch clientDoctor2 (89ms)
--Dispatching--
--Dispatching--

  Test notification for both doctor and patient
    1) Should dispatch clientDoctor
    2) Should dispatch clientPatient


  1 passing (4s)
  2 failing
```

Here's a version without this issue:

``` javascript
function EventDispatcher() {
  var _callback = null;
  this.dispatch = function() {
    _callback();
  }

  this.on = function(type, callback) {
    _callback = callback;
  }
}

var clientDoctor  = new EventDispatcher();
var clientPatient = new EventDispatcher();
var clientDoctor2 = new EventDispatcher();

describe("Test notification clientDoctor2" , function() {
  it("Should dispatch clientDoctor2", function(done) {
    clientDoctor2.on("Notifications.js", done);
    clientDoctor2.dispatch();
  })
});

describe('Test notification for both doctor and patient', function() {
  it("Should dispatch clientDoctor", function(done) {
    clientDoctor.on("RequestAccess.js", done);
    clientDoctor.dispatch();
  })

  it("Should dispatch clientPatient", function(done) {
    clientPatient.on("RequestAccess.js", done);
    clientPatient.dispatch();
  })
});
```

```
$ mocha test.js


  Test notification clientDoctor2
    ✓ Should dispatch clientDoctor2

  Test notification for both doctor and patient
    ✓ Should dispatch clientDoctor
    ✓ Should dispatch clientPatient


  3 passing (16ms)
```

Hope that makes sense!

**Comment by salboaie** [comment]
Sorry, but  it doesn't make much sense. You just fixed  this particular test but not a real issue... My example is a simplified version of some asynchronous tests that get triggered by some websockets message.  If 100ms is not enough for mocha to set his internal stuff, I see a problem.   My original  tests are located in separated files  but still somehow there is a concurrency issue in mocha that triggers the problem exactly like in my example.. Each test pass happily when is executed separated but when I run all tests in that folder the second test always fail.  I really don't have control on the external dispatching as it is triggered by a call made before  executing describe.

If functions from "describe" are executed one by one in a serialized form, at least mocha should not interfere between executing multiple files as it happens now. Apparently when running multiple test files, mocha execute some parts in parallel but impose an execution order on describe parts...    It looks like an issue for mocha itself... as it could break  tests like in my example.

**Comment by danielstjules** [comment]
Hi @salboaie, you're right about test suites being invoked serially! :) That's the case for many JS test runners/frameworks, e.g. Mocha, Jasmine, and Tape. But the issue is unrelated to setup. You can see for yourself by increasing the timeout before dispatch to a full 1 second:

``` javascript
function EventDispatcher() {
  var _callback = null;

  this.dispatch = function() {
    console.log('--Dispatching--');
    if (_callback) _callback();
  }

  this.on = function(type, callback) {
    _callback = callback;
  }
}

var clientDoctor  = new EventDispatcher();
var clientPatient = new EventDispatcher();
var clientDoctor2 = new EventDispatcher();

describe("Test notification clientDoctor2" , function() {
  it("Should dispatch clientDoctor2", function(done) {
    clientDoctor2.on("Notifications.js", done);
  });
});

describe('Test notification for both doctor and patient', function() {
  it("Should dispatch clientDoctor", function(done) {
    clientDoctor.on("RequestAccess.js", done);
  });

  it("Should dispatch clientPatient", function(done) {
    clientPatient.on("RequestAccess.js", done);
  });
});

setTimeout(function(){
    clientDoctor2.dispatch();
    clientDoctor.dispatch();
    clientPatient.dispatch();
}, 1000);
```

```
$ mocha example.js


  Test notification clientDoctor2
--Dispatching--
    ✓ Should dispatch clientDoctor2 (989ms)
--Dispatching--
--Dispatching--

  Test notification for both doctor and patient
    1) Should dispatch clientDoctor
    2) Should dispatch clientPatient


  1 passing (5s)
  2 failing

  1) Test notification for both doctor and patient Should dispatch clientDoctor:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout (timers.js:110:15)

  2) Test notification for both doctor and patient Should dispatch clientPatient:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout (timers.js:110:15)
```

Any logic outside of a top level hook, suite, or spec will be ran when the file loads. For example, the setTimeout function that dispatches those events will be invoked immediately. Any logic that should be ran _only_ when mocha is about to run that file's tests should be placed in a `before` or `beforeEach` hook.

**Comment by salboaie** [comment]
Ok, seems a better advice. I was beginning to figure myself... Thank you!

**Comment by salboaie** [comment]
I wander that if you change a bit the behavior of "describe" and do not call at beginning, you could get rid entirely by before, after functions... Apparently mocha runs "describe" blocks  immediately but contradictory the "it" blocks are serialized, delayed after the "describe" blocks finished... 
 I found an workaround, this is a suggestion to make things even simpler, more intuitive...

**Comment by dasilvacontin** [comment]
For some features/reporters we need to know how many tests will be ran, e.g. progress bar. Unless we execute the `describe` blocks, there's no other way to do so.

**Comment by danielstjules** [comment]
@salboaie Glad you were able to get things working for you :)
