### ISSUE TITLE
Mocha does not call "global after" if a test's before function returns failure.

### ISSUE THREAD

**Issue by psinghsp** [mochajs/mocha#1612]
I have following format:
before <-- global
after <-- global

describe(
   beforeEach();
   afterEach();
   it();
   it();
)

If beforeEach returns failure, global after is not called. We need to in our situation to clean up things in global before. Is this a bug or Mocha just behaves this way?

**Comment by danielstjules** [comment]
Hi @psinghsp, sorry to hear you're running into an issue! Have you tried upgrading to the latest version of mocha? Please see the example below, showing that `after` is correctly invoked after the `beforeEach` failure.

``` javascript
// example.js
before(function() {
  console.log('before');
});

after(function() {
  console.log('after');
});

describe('suite', function() {
  beforeEach(function() {
    throw new Error('In beforeEach');
  });

  afterEach(function() {
    console.log('afterEach');
  });

  it('test', function() {
    // example
  });
});

// Test run
$ mocha example.js

  before

  ․afterEach
after


  0 passing (7ms)
  1 failing

  1) suite "before each" hook:
     Error: In beforeEach
      at Context.<anonymous> (/Users/dstjules/git/mocha/example.js:11:11)
      at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:251:21)
      at Hook.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:244:7)
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:259:10)
      at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by psinghsp** [comment]
I am using Mocha 2.1.0. Is thee a newer version of it?

**Comment by danielstjules** [comment]
Yup! Give 2.2.1 a try :) https://github.com/mochajs/mocha/releases
