### ISSUE TITLE
[BUG] Does not work with CoffeeScript 1.9.2

### ISSUE THREAD

**Issue by alexbuzzbee** [mochajs/mocha#1717]
With CoffeeScript version 1.9.2, the following error is thrown on attempting to use `mocha --compilers coffee:coffee-script`:

```
$ mocha --compilers coffee:coffee-script -R spec
/Users/<REDACTED>/Dropbox/Projects/CoffeeScript/CoffeeNode CMS/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210
          throw new Error("Use CoffeeScript.register() or require the coffee-s
                ^
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee] (/Users/<REDACTED>/Dropbox/Projects/CoffeeScript/CoffeeNode CMS/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210:17)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /Users/<REDACTED>/Dropbox/Projects/CoffeeScript/CoffeeNode CMS/node_modules/mocha/lib/mocha.js:192:27
  at Array.forEach (native)
  at Mocha.loadFiles (/Users/<REDACTED>/Dropbox/Projects/CoffeeScript/CoffeeNode CMS/node_modules/mocha/lib/mocha.js:189:14)
  at Mocha.run (/Users/<REDACTED>/Dropbox/Projects/CoffeeScript/CoffeeNode CMS/node_modules/mocha/lib/mocha.js:422:31)
  at Object.<anonymous> (/Users/<REDACTED>/Dropbox/Projects/CoffeeScript/CoffeeNode CMS/node_modules/mocha/bin/_mocha:398:16)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by jbnicolai** [comment]
Could you add a reproducible testcase? Unable to reproduce the issue locally.

**Comment by alexbuzzbee** [comment]
See github.com/coffeenode-cms/system, as that's where the problem's
happening. Clone, switch to it, and run `mocha --compilers
coffee:coffee-script -R spec`.

**Comment by alexbuzzbee** [comment]
Problem is still unresolved after reinstalling Mocha and CoffeeScript.

**Comment by dasilvacontin** [comment]
You must use `mocha --compilers coffee:coffee-script/register` instead.

**Comment by alexbuzzbee** [comment]
Thank you!

**Comment by dasilvacontin** [comment]
No worries!
Check the changelog of CoffeeScript v1.7.0 for more info: http://coffeescript.org/#changelog. :)
