### ISSUE TITLE
ES6 Template strings break describe

### ISSUE THREAD

**Issue by OOPMan** [mochajs/mocha#1866]
I am writing my tests in ES6 and using babel to transpile them. I ran into the following issue when attempting to use an ES6 template string.

ES6 version of code:
```
describe(```
    var A = encapsulate({
        x: 0,
        y: function () {
            return this.x;
        }
    })```,
    () => {
        // DO STUFF
});
```

ES5 version of code:
```
describe(
    "var A = encapsulate({" +
    " x: 0," +
    " y: () => {" +
    " return this.x;" +
    " }" +
    "})",
    function () {
        // DO STUFF
});
```

The ES6 version fails with the following error when run:
```
 adamj@Harvester  ~/Development/Personal/Javascript/encapsulate   master ●✚  babel-node ./node_modules/mocha/bin/mocha
/home/adamj/Development/Personal/Javascript/encapsulate/test/encapsulate.es6:63
    describe(''(_templateObject2)(_templateObject), function () {
               ^
TypeError: "" is not a function
    at Suite.<anonymous> (/home/adamj/Development/Personal/Javascript/encapsulate/test/encapsulate.es6:40:13)
    at context.describe.context.context (/home/adamj/Development/Personal/Javascript/encapsulate/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Object.<anonymous> (/home/adamj/Development/Personal/Javascript/encapsulate/test/encapsulate.es6:5:1)
    at Module._compile (module.js:430:26)
    at normalLoader (/home/adamj/Development/Personal/Javascript/encapsulate/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .es6] (/home/adamj/Development/Personal/Javascript/encapsulate/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/adamj/Development/Personal/Javascript/encapsulate/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/adamj/Development/Personal/Javascript/encapsulate/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/home/adamj/Development/Personal/Javascript/encapsulate/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/home/adamj/Development/Personal/Javascript/encapsulate/node_modules/mocha/bin/_mocha:401:18)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:953:3
 ✘ 
```

My mocha.opts is as follows:
```
--require babel/register -C -R spec ./test/*.es6
```

**Comment by danielstjules** [comment]
This isn't an issue with mocha. You probably don't mean to be using triple backticks? https://github.com/babel/babel/issues/1115 

``` javascript
// Your example
function describe(str, fn) {
  console.log(str);
}

describe(```
    var A = encapsulate({
        x: 0,
        y: function () {
            return this.x;
        }
    })```,
    () => {
        // DO STUFF
});

// ---------------------------
// Compiles to =>
// ---------------------------

"use strict";

var _templateObject = _taggedTemplateLiteral([""], [""]),
    _templateObject2 = _taggedTemplateLiteral(["\n    var A = encapsulate({\n        x: 0,\n        y: function () {\n            return this.x;\n        }\n    })"], ["\n    var A = encapsulate({\n        x: 0,\n        y: function () {\n            return this.x;\n        }\n    })"]);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

function describe(str, fn) {
    console.log(str);
}

describe(""(_templateObject2)(_templateObject), function () {
    // DO STUFF
});
```

``` javascript
// This is probably what you want
function describe(str, fn) {
  console.log(str);
}

describe(`
    var A = encapsulate({
        x: 0,
        y: function () {
            return this.x;
        }
    })`,
    () => {
        // DO STUFF
});

// ---------------------------
// Compiles to =>
// ---------------------------

"use strict";

function describe(str, fn) {
    console.log(str);
}

describe("\n    var A = encapsulate({\n        x: 0,\n        y: function () {\n            return this.x;\n        }\n    })", function () {
    // DO STUFF
});
```

**Comment by OOPMan** [comment]
Oh god, I feel so stupid right now. Argh, Python ''' ''' syntax bites again.

**Comment by flux627** [comment]
Python bit me too! Thanks for making this issue for me to google.
