### ISSUE TITLE
Markdown reporter error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by baldercm** [mochajs/mocha#1875]
We are using Markdown reporter for our Mocha tests and started having troubles with version 2.3.0 and above. There seems to be an infinite recursion in Markdown reporter:

```
$ NODE_ENV=test ./node_modules/.bin/mocha --reporter markdown >> docs/README.md

/home/balder/git/payments/node_modules/mocha/lib/reporters/markdown.js:40
    obj = obj[key] = obj[key] || { suite: suite };
                        ^

RangeError: Maximum call stack size exceeded
  at mapTOC (/home/balder/git/payments/node_modules/mocha/lib/reporters/markdown.js:40:25)
  at /home/balder/git/payments/node_modules/mocha/lib/reporters/markdown.js:42:7
  at Array.forEach (native)
  at mapTOC (/home/balder/git/payments/node_modules/mocha/lib/reporters/markdown.js:41:18)
  at /home/balder/git/payments/node_modules/mocha/lib/reporters/markdown.js:42:7
```

Apparently, the issues started with commit 3f78f10ca40dba63be10454c8e17dc9586416e10, with the changes in the `mapTOC` function in `lib/reporters/markdown.js`, more precisely, deletion of callback parameter in the foreach loop:

```javascript
function mapTOC(suite, obj) {
    var ret = obj;
    var key = SUITE_PREFIX + suite.title;

    obj = obj[key] = obj[key] || { suite: suite };
    suite.suites.forEach(function() { // suite param missing leads to infinite recursion
      mapTOC(suite, obj);
    });

    return ret;
  }
```

I have tested locally and adding the param back fixes the issue.

**Comment by danielstjules** [comment]
Thanks for letting us know! I'll hopefully merge this fix in shortly https://github.com/mochajs/mocha/pull/1876/files
