### ISSUE TITLE
specify type of runnable in multiple done error

### ISSUE THREAD

**Issue by dasilvacontin** [mochajs/mocha#1890]
before:
```
 1) suite test1:
     Uncaught Error: done() called multiple times
      at Suite.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:2:3)
      at Object.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:1:63)
      at Array.forEach (native)
      at node.js:814:3
```

after:
```
 1) suite test1:
     Uncaught Error: done() called multiple times in `beforeEach` hook
      at Suite.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:2:3)
      at Object.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:1:63)
      at Array.forEach (native)
      at node.js:814:3
```

**Comment by danielstjules** [comment]
Looks like a duplicate of https://github.com/mochajs/mocha/issues/1798 since https://github.com/mochajs/mocha/pull/1889 fixes exactly that?

```
$ cat test/integration/fixtures/multiple.done.beforeEach.js
describe('suite', function() {
  beforeEach(function(done) {
    setTimeout(done, 10);
    setTimeout(done, 20);
  });

  it('test1', function(done) {
    setTimeout(done, 50);
  });

  it('test2', function(done) {
    setTimeout(done, 50);
  });
});
danielstjules:~/git/mocha (issue-1798)
$ ./bin/mocha test/integration/fixtures/multiple.done.beforeEach.js


  ․․․․

  2 passing (133ms)
  2 failing

  1) suite "before each" hook:
     Error: done() called multiple times
      at Hook.Runnable (lib/runnable.js:54:17)
      at new Hook (lib/hook.js:22:12)
      at Suite.beforeEach (lib/suite.js:237:14)
      at beforeEach (lib/interfaces/common.js:52:17)
      at Suite.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:2:3)
      at context.describe.context.context (lib/interfaces/bdd.js:47:10)
      at Object.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:1:63)
      at Array.forEach (native)
      at Object.<anonymous> (bin/_mocha:393:18)
      at node.js:951:3

  2) suite "before each" hook:
     Error: done() called multiple times
      at Hook.Runnable (lib/runnable.js:54:17)
      at new Hook (lib/hook.js:22:12)
      at Suite.beforeEach (lib/suite.js:237:14)
      at beforeEach (lib/interfaces/common.js:52:17)
      at Suite.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:2:3)
      at context.describe.context.context (lib/interfaces/bdd.js:47:10)
      at Object.<anonymous> (test/integration/fixtures/multiple.done.beforeEach.js:1:63)
      at Array.forEach (native)
      at Object.<anonymous> (bin/_mocha:393:18)
      at node.js:951:3
```

I think you were using `mocha` rather than `/path/to/repo/mocha/bin/mocha`

**Comment by danielstjules** [comment]
Note that it doesn't say `suite test1:` since that's misleading - instead it correctly attributes the error to `suite "before each" hook:`

**Comment by dasilvacontin** [comment]
> I think you were using mocha rather than /path/to/repo/mocha/bin/mocha

Bingo. I was furthermore confused due to test helpers actually using the dev source code.
