### ISSUE TITLE
no method 'match'

### ISSUE THREAD

**Issue by ainthek** [mochajs/mocha#1894]
after upgrading to 2.3.2, I receive this:

usr/local/lib/node_modules/mocha/lib/reporters/base.js:201
      var match = message.match(/^([^:]+): expected/);
                          ^
TypeError: Object 0,1,2,3 has no method 'match'
  at /usr/local/lib/node_modules/mocha/lib/reporters/base.js:201:27
  at Array.forEach (native)
  at Function.exports.list (/usr/local/lib/node_modules/mocha/lib/reporters/base.js:163:12)
  at Spec.Base.epilogue (/usr/local/lib/node_modules/mocha/lib/reporters/base.js:321:10)
  at Runner.emit (events.js:117:20)
  at /usr/local/lib/node_modules/mocha/lib/runner.js:717:12
  at done (/usr/local/lib/node_modules/mocha/lib/runner.js:615:7)
  at Runner.next [as nextSuite] (/usr/local/lib/node_modules/mocha/lib/runner.js:582:16)
  at Runner.uncaught (/usr/local/lib/node_modules/mocha/lib/runner.js:686:17)
  at process.uncaught (/usr/local/lib/node_modules/mocha/lib/runner.js:710:10)
  at process.emit (events.js:95:17)
  at process._fatalException (node.js:295:26)

**Comment by danielstjules** [comment]
Can you clone the repo and run ./path/to/repo/bin/mocha on your project? Wondering if https://github.com/mochajs/mocha/pull/1848 / https://github.com/mochajs/mocha/commit/0956c023e4530a527f376be4ae0724ea96713ab7 fixed it. If it doesn't can you provide a small snippet to reproduce? Thinking it's because the error being thrown has a non-string message property.

**Comment by ainthek** [comment]
than works, however my test was buggy
found the error after your hints

**Comment by ainthek** [comment]
BAD:
assert(output === input, expected, "Mutate original array");
FIX:
assert(output === input, "Mutate original array");
