### ISSUE TITLE
Mocha exploded, Map is not defined

### ISSUE THREAD

**Issue by littleCoderVA** [mochajs/mocha#1896]
Hi I ran mocha test on my MEAN stack project and it exploded. I used the same set up on windows and it doesn't show the problem, just on linux, don't know why it can't find the Map() function. Although the Map() function is new for js, I don't know why it works on windows but not linux and how to fix it.
Mocha set up for my project:
    "grunt-mocha-istanbul": "^3.0.1",
    "grunt-mocha-test": "~0.12.1",
    "mocha-junit-reporter": "^1.6.1",
Any help will be appreciated!

Below are the output when I ran the test:

>> Mocha exploded!
>> ReferenceError: Map is not defined
>>     at Object.<anonymous> (/home/ ...'project directory' ...)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at ... 'project directory' .../node_modules/mocha/lib/mocha.js:216:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (...'project directory' .../node_modules/mocha/lib/mocha.js:213:14)
>>     at MochaWrapper.run (...'project directory' .../node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
>>     at ...'project directory' .../node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
>>     at capture (...'project directory' .../node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
>>     at Object.<anonymous> (...'project directory' .../node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
>>     at Object.<anonymous> (...'project directory' .../node_modules/grunt/lib/grunt/task.js:264:15)
>>     at Object.thisTask.fn (...'project directory' .../node_modules/grunt/lib/grunt/task.js:82:16)

......

var versionList = new Map();								// <----- Problem comes from this line
                      ^
ReferenceError: Map is not defined
    at Object.<anonymous> (...'project directory' ...)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object.Module._extensions.(anonymous function) [as .js] (...'project directory' .../node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at ...'project directory' .../node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (...'project directory' .../node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (...'project directory' .../node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (...'project directory' .../node_modules/mocha/bin/_mocha:401:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object.Module._extensions.(anonymous function) [as .js] (...'project directory' .../node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (...'project directory' .../node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at ...'project directory' .../node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at ...'project directory' .../node_modules/istanbul/lib/util/file-matcher.js:68:16
    at ...'project directory' .../node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at ...'project directory' .../node_modules/istanbul/node_modules/async/lib/async.js:363:13
    at ...'project directory' .../node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (...'project directory' .../node_modules/istanbul/node_modules/async/lib/async.js:248:21)
    at ...'project directory' .../node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at ...'project directory' .../node_modules/istanbul/node_modules/async/lib/async.js:360:17
    at LOOP (fs.js:1361:14)
    at process._tickCallback (node.js:415:13)
>>

**Comment by danielstjules** [comment]
Map is ES6. If you're running Node 0.12, you'll need to use the --harmony flag. If using iojs, it should be enabled by default. If you're using nvm or n, it's possible you may have been using an older version of node accidentally.

**Comment by littleCoderVA** [comment]
Thanks for the info. I'm using Node 0.10, and using "grunt test" to run all the tasks including mocha test. May I ask how I can add the mocha --harmony flag? This is my mocha config in the gruntfile.js: 
mochaTest: {
			src: watchFiles.mochaTests,
			options: { 
				
				reporter: 'mocha-junit-reporter',
				    reporterOptions: {
				        mochaFile: './mochaTests.xml'
				    },
				require: 'server.js'
			}
		}
...

**Comment by boneskull** [comment]
Just upgrade to NodeJS v4.0.x and be done w/ it :smile:

**Comment by boneskull** [comment]
@littleCoderVA You'll have to ask the maintainer of grunt-mocha-test about that.

**Comment by littleCoderVA** [comment]
Thanks Christopher, although upgrading to NodeJS led to many dependency
warnings, mocha finally worked.
