### ISSUE TITLE
Reporting the wrong test failing

### ISSUE THREAD

**Issue by aray12** [mochajs/mocha#1913]
So I created a folder for all of my functional route tests for an API I am building. I kept getting the following error:

```
  1) /listing should return a successfully created listing:
     Uncaught AssertionError: expected 'New Name' to be false
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at Test.<anonymous> (tests/functional/routes/calendar_spec.js:92:59)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:908:16
```

The following is the file containing the test it was referencing:
listing_spec.js
```javascript
'use strict';

var should = require('should'),
	jwt = require('jsonwebtoken'),
	app = require('../../../bin/www'),

	request;

var data = {
	male: 1,
	female: 2,
	cal_tz: 1,
	lang: 'English',
	auth: null
};

describe('/listing', function () {

	beforeEach(function (done) {
		request = require('supertest')(app);

		var profile = {
			account_id: 1,
			account_email: "first@test.com"
		};

		var token = jwt.sign(profile, process.env.SECRET, {expiresInMinutes: 60 * 5});

		data.auth = 'Bearer ' + token;
		done();
	});


	it('should return a successfully created listing', function (done) {
		var listing = {
			"max_attendance": 1,
			"skill_id": 3,
			"listing_type_id": 1,
			"billing_policy_id": 1,
			"lang": "English",
			"calendar_id": 1
		};

		request
			.post('/listing')
			.set('Authorization', data.auth)
			.send(listing)
			.end(function (err, res) {
				if (err) {
					throw new Error(err);
				}

				res.should.have.property('status').which.equal(200);


				res.body.max_attendance.should.equal(1);

				// skill object
				res.body.skill.should.have.property('skill_id').which.equal(3);
				res.body.skill.should.have.property('skill_name').which.equal('Spanish');
				res.body.skill.should.have.property('skill_name_label').which.equal('SPANISH_LANGUAGE_SKILL');

				// listing type object
				res.body.listing_type.should.have.property('listing_type_id').which.equal(1);
				res.body.listing_type.should.have.property('listing_type').which.equal('Private');
				res.body.listing_type.should.have.property('listing_type_label').which.equal('PRIVATE_LISTING_TYPE');

				// listing status object
				res.body.listing_status.should.have.property('listing_status').which.equal('Draft');

				// billing policy object
				res.body.billing_policy.should.have.property('billing_policy_id').which.equal(1);
				res.body.billing_policy.should.have.property('billing_policy_name').which.equal('Flexible');

				done();
			});
	});
});
```
After an embarrassing amount of time I realized the stacktrace was actually referencing a different test in a different file. The following is that file:
calendar_spec.js
```javascript
'use strict';

var should = require('should'),
	jwt = require('jsonwebtoken'),
	app = require('../../../bin/www'),

	request;

var data = {
	male: 1,
	female: 2,
	cal_tz: 1,
	lang: 'English',
	auth: null
};

describe('/calendar', function() {

	beforeEach(function(done) {
		request = require('supertest')(app);

		var profile = {
			account_id: 1,
			account_email: "first@test.com"
		};

		var token = jwt.sign(profile, process.env.SECRET, {expiresInMinutes: 60 * 5});

		data.auth = 'Bearer ' + token;
		done();
	});

	describe('Add', function() {
		it('should create a new calendar', function(done) {
			request
				.post('/calendar')
				.set('Authorization', data.auth)
				.send({"test": "test"})
				.end(function(err, res) {
					if(err) {
						throw new Error(err);
					}

					res.should.have.property('status').which.equal(200);
				});

			done();
		});
	});

	describe('Edit', function() {
		it('should successfully change the calendar name', function(done) {
			var calendar = {
				"calendar_name": "New Name"
			};

			request
				.put('/calendar/1')
				.set('Authorization', data.auth)
				.send(calendar)
				.end(function(err, res) {
					if(err) {
						throw new Error(err);
					}

					res.should.have.property('status').which.equal(200);
					res.body.should.have.property('calendar_name').which.equal(calendar.calendar_name);
				});

			done();
		});

		it('should successfully deactivate the calendar', function(done) {
			var calendar = {
				"is_active": false
			};

			request
				.put('/calendar/1')
				.set('Authorization', data.auth)
				.send(calendar)
				.end(function(err, res) {
					if(err) {
						throw new Error(err);
					}

					res.should.have.property('status').which.equal(200);
					res.body.should.have.property('calendar_name').which.equal(calendar.is_active);
				});

			done();
		});
	});
});
```

More specifically the problem was the following test:
```javascript
               it('should successfully deactivate the calendar', function(done) {
			var calendar = {
				"is_active": false
			};

			request
				.put('/calendar/1')
				.set('Authorization', data.auth)
				.send(calendar)
				.end(function(err, res) {
					if(err) {
						throw new Error(err);
					}

					res.should.have.property('status').which.equal(200);
					res.body.should.have.property('calendar_name').which.equal(calendar.is_active);
				});

			done();
		});
```

The following assertion
```javascript
res.body.should.have.property('calendar_name').which.equal(calendar.is_active);
```
should have been 
```javascript
es.body.should.have.property('is_active').which.equal(calendar.is_active);
```

The following is the Makefile I created to run the tests:
```
test: unit integration functional

.PHONY: test

unit:
	@NODE_ENV=test PORT=4000 ./node_modules/.bin/mocha tests/unit

.PHONY: unit

integration:
	echo 'No integration tests written yet
.PHONY: integration

functional: routes

.PHONY: functional

routes: setup
	@NODE_ENV=test PORT=4000 ./node_modules/.bin/mocha tests/functional/routes

.PHONY: routes

setup:
	dropdb api-test-db --if-exists
	createdb api-test-db
	psql api-test-db < test-db-image.sql

.PHONY: setup
```

I am fairly new to mocha but I don't believe this is the intended behavior. I tried to provide everything I thought would be necessary to investigate further, but please let me know if you need anything else.

**Comment by dasilvacontin** [comment]
`done` is used to let `mocha` know when your test is finished doing async operations – you probably want to use it inside the last callback. When you execute `done`, mocha will think you are finished with your current test and will move on to the next one.

```js
it('should successfully deactivate the calendar', function(done) {
  var calendar = {
    "is_active": false
  };

  request
  .put('/calendar/1')
  .set('Authorization', data.auth)
  .send(calendar)
  .end(function(err, res) {
    if(err) {
      throw new Error(err);
    }
    res.should.have.property('status').which.equal(200);
    res.body.should.have.property('is_active').which.equal(calendar.is_active);

    done(); // <-- here
  });         
});
```

Let us know if it's failing for you!

**Comment by aray12** [comment]
Ya that makes sense. That was just a typo that I missed after a long day. Thanks for your help. Greatly appreciate it.

**Comment by dasilvacontin** [comment]
No problemo, glad to help :). Cheers!

**Comment by mrjacobbloom** [comment]
In case this helps anyone with a similar issue: I was running into weird errors where the wrong test was reported failing. It turned out that I had written something like this:

```javascript
it('testname', () => { // forgot "done" argument
  // test stuff...
  done();
});
```
