### ISSUE TITLE
Stacktraces display incorrect line when tests throw errors

### ISSUE THREAD

**Issue by LyonesGamer** [mochajs/mocha#1927]
When an Error is thrown and unhandled in a test being run, a stacktrace is printed to stderr in the middle of the test runner output. However, on the line which includes my own files, the line number will usually become line 9 (regardless of the file or code), and the character count is relative to the position of the code in the file, as if the file is being strangely minified (note that I am not minifying or in any other way compiling my javascript or changing it before running it). This makes it impossible to tell where the error is actually being generated. This does not occur for stacktrace lines that I did not create (e.g. those in libraries).

Example of that output:

```
Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header ([project root]/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send ([project root]/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json ([project root]/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send ([project root]/node_modules/express/lib/response.js:151:21)
    at [project root]/src/activities.js:9:7248
    at tryCatcher ([project root]/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler ([project root]/node_modules/knex/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt ([project root]/node_modules/knex/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue ([project root]/node_modules/knex/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues ([project root]/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] ([project root]/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

This is an error from express, that I apparently am setting response headers twice. Where, though? `at [project root]/src/activities.js:9:7248`

This is on mocha 2.3.3 on node 0.12.7.

**Comment by agessner** [comment]
I'm getting the same problem, have you found any solution?

**Comment by LyonesGamer** [comment]
@agessner No, I never found a solution. Now that I think about it, though, I don't think I've seen this issue in several months. It may have been fixed for me by upgrading mocha, Node, or both. I'm not sure. :disappointed:

**Comment by drazisil** [comment]
As OP has not observed issue in some time, closing as it may be resolved

**Comment by GCSBOSS** [comment]
Having the same problem. Could any reason for this behavior be found?

**Comment by andrew-flg** [comment]
I'm also seeing this behaviour.

**Comment by agirorn** [comment]
I'm experiencing this right now ;(
