### ISSUE TITLE
Stack trace cleaning not happening when using Babel's async/await

### ISSUE THREAD

**Issue by djanowski** [mochajs/mocha#1950]
Test:

```js
describe('foo', function() {
  it('bar', async function() {
    await bar();
  });
});

function bar() {
  return new Promise(function(resolve, reject) {
    reject(new Error('bar'));
  });
}
```

```
mocha --compilers js:babel/register foo_test.js 


  foo
    1) bar


  0 passing (194ms)
  1 failing

  1) foo bar:
     Error: bar
      at foo_test.js:9:12
      at new Promise (node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:183:7)
      at bar (foo_test.js:8:10)
      at Context.callee$1$0$ (foo_test.js:3:11)
      at tryCatch (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:328:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
      at invoke (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:136:37)
      at callInvokeWithMethodAndArg (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:172:16)
      at previousPromise (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:194:19)
      at new Promise (node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:183:7)
      at AsyncIterator.enqueue (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:193:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
      at Object.runtime.async (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:215:14)
      at Context.callee$1$0 (foo_test.js:2:13)
```

**Comment by danielstjules** [comment]
The stack trace filtering no longer filters out anything but mocha's internal calls. This is expected behavior. To filter out function calls from your own dependencies, try https://github.com/rstacruz/mocha-clean

**Comment by djanowski** [comment]
I guess [this](https://github.com/mochajs/mocha/blob/master/lib/utils.js#L710-L717) confused me.

Thanks for your reply!
