### ISSUE TITLE
Tests display full stacktrace in 2.3.3 by default

### ISSUE THREAD

**Issue by Vannevelj** [mochajs/mocha#1960]
I'm using mocha 2.3.3 which should have the shortened stacktraces by default yet I am still receiving them in full:

	2) conditionBuilder greater_than_condition returns false with smaller input:
	 AssertionError: expected undefined to equal false
	  at evaluateCondition (C:\Users\jeroen\Documents\Github\MyPackage\tests\conditionBuilderTests.js:44:11)
	  at Context.<anonymous> (C:\Users\jeroen\Documents\Github\MyPackage\tests\conditionBuilderTests.js:31:4)
	  at callFn (C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runnable.js:286:21)
	  at Test.Runnable.run (C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runnable.js:279:7)
	  at Runner.runTest (C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runner.js:421:10)
	  at C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runner.js:528:12
	  at next (C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runner.js:341:14)
	  at C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runner.js:351:7
	  at next(C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runner.js:283:14)
	  at Immediate._onImmediate(C:\Users\jeroen\Documents\Github\MyPackage\node_modules\mocha\lib\runner.js:319:5)

`npm show mocha version` returns `2.3.3` and I execute my tests using `mocha myTestFile` (so there is no `full-trace` flag specified).

Does anyone else notice this? Did I make a mistake anywhere? I would show a test but I don't think it's contents are relevant.

**Comment by danpantry** [comment]
:+1: also getting this

````
$ npm test

> project@0.0.1 test c:\projects\project
> mocha test/index.js



  foo
    1) should not be equal to bar


  0 passing (32ms)
  1 failing

  1) foo should not be equal to bar:

      AssertionError: 'foo' == 'bar'
      + expected - actual

      -foo
      +bar

      at Context.<anonymous> (c:\projects\project\test\index.js:6:12)
      at callFn (c:\projects\project\node_modules\mocha\lib\runnable.js:286:21)
      at Test.Runnable.run (c:\projects\project\node_modules\mocha\lib\runnable.js:279:7)
      at Runner.runTest (c:\projects\project\node_modules\mocha\lib\runner.js:421:10)
      at c:\projects\project\node_modules\mocha\lib\runner.js:528:12
      at next (c:\projects\project\node_modules\mocha\lib\runner.js:341:14)
      at c:\projects\project\node_modules\mocha\lib\runner.js:351:7
      at next (c:\projects\project\node_modules\mocha\lib\runner.js:283:14)
      at Immediate._onImmediate (c:\projects\project\node_modules\mocha\lib\runner.js:319:5)
````

spec

````javascript

'use strict';
const assert = require('assert');
describe('foo', function() {
  it('should not be equal to bar', function() {
    assert.equal('foo', 'bar');
  });
});
````

**Comment by ewendel** [comment]
I'm also getting long stacktraces using version `2.3.4`, running my tests with `mocha` from the cli. 

Stacktraces are up to ~45 lines long.

**Comment by danielstjules** [comment]
Looks like this might be specific to windows? If you clone this repo and run `make test-all`, do tests fail?

Updating `var slash` to be `path.sep` when `is.node` is true should hopefully fix it.

**Comment by ewendel** [comment]
I'm on Ubuntu 14.04, all tests passed when running `make test-all`

**Comment by danielstjules** [comment]
Can you post an example stack trace? The stack traces are a bit longer, as they no longer hide frames from your dependencies. But they still try to hide those from mocha.

**Comment by ewendel** [comment]
After closer inspection, the by far longest stack trace is being caused by Babel when there's a syntax error present (added import in a function):

Long stack trace: https://gist.github.com/ewendel/eb4958034cfb945efcd0
Shorter but still long: https://gist.github.com/ewendel/317e12165be61c65b6b6

**Comment by danpantry** [comment]
cc @danielstjules was this ever fixed? I haven't used Mocha in a long while
