### ISSUE TITLE
Insane error noise?

### ISSUE THREAD

**Issue by dmitriz** [mochajs/mocha#2031]
So I have a syntax error: 

```sh
> mocha --compilers js:babel-core/register --recursive "--watch"

SyntaxError: /Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/test/core_spec.js: Unexpected token (71:37)
  69 |         vote: Map({
  70 |           pair: List.of('Trainspotting', '28 Days Later'),
> 71 |           tally: Map({'Trainspotting', 1})
     |                                      ^
  72 |         })
  73 |       }))
  74 | 
...
```

This small error was reported with hundreds of lines! 
Is that really necessary?

```sh
...
  74 | 
    at Parser.pp.raise (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseObjPropValue (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:820:8)
    at Parser.pp.parseObj (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:750:10)
    at Parser.pp.parseExprAtom (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:479:19)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:341:20)
    at Parser.pp.parseSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:304:29)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:275:15)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseObjPropValue (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:777:99)
    at Parser.pp.parseObj (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:750:10)
    at Parser.pp.parseExprAtom (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:479:19)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:341:20)
    at Parser.pp.parseSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:304:29)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:275:15)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseObjPropValue (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:777:99)
    at Parser.pp.parseObj (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:750:10)
    at Parser.pp.parseExprAtom (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:479:19)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:341:20)
    at Parser.pp.parseSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:304:29)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:275:15)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:341:20)
    at Parser.pp.parseSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:304:29)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:275:15)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:85:19)
    at Parser.pp.parseStatement (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:156:19)
    at Parser.pp.parseBlockBody (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:500:21)
    at Parser.pp.parseBlock (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:481:8)
    at Parser.pp.parseFunctionBody (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:886:22)
    at Parser.pp.parseArrowExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:865:8)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:597:17)
    at Parser.pp.parseExprAtom (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:469:19)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:341:20)
    at Parser.pp.parseSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:304:29)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:275:15)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:85:19)
    at Parser.pp.parseStatement (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:156:19)
    at Parser.pp.parseBlockBody (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:500:21)
    at Parser.pp.parseBlock (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:481:8)
    at Parser.pp.parseFunctionBody (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:886:22)
    at Parser.pp.parseArrowExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:865:8)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:597:17)
    at Parser.pp.parseExprAtom (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:469:19)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:341:20)
    at Parser.pp.parseSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:304:29)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:275:15)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:85:19)
    at Parser.pp.parseStatement (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:156:19)
    at Parser.pp.parseBlockBody (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:500:21)
    at Parser.pp.parseBlock (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:481:8)
    at Parser.pp.parseFunctionBody (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:886:22)
    at Parser.pp.parseArrowExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:865:8)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:597:17)
    at Parser.pp.parseExprAtom (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:469:19)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:341:20)
    at Parser.pp.parseSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:304:29)
    at Parser.pp.parseExprSubscripts (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:275:15)
    at Parser.pp.parseMaybeUnary (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExpression (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/expression.js:85:19)
    at Parser.pp.parseStatement (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:156:19)
    at Parser.pp.parseBlockBody (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:500:21)
    at Parser.pp.parseTopLevel (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/statement.js:29:8)
    at Parser.parse (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/parser/index.js:98:17)
    at Object.parse (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babylon/lib/index.js:44:50)
    at File.parse (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-core/lib/transformation/file/index.js:480:24)
    at File.parseCode (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-core/lib/transformation/file/index.js:560:20)
    at /Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-core/lib/transformation/pipeline.js:45:12
    at File.wrap (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-core/lib/transformation/file/index.js:520:16)
    at Pipeline.transform (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-core/lib/transformation/pipeline.js:43:17)
    at Object.transformFileSync (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-core/lib/api/node.js:116:10)
    at compile (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-register/lib/node.js:102:20)
    at loader (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-register/lib/node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/mocha/lib/mocha.js:453:10)
    at loadAndRun (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/mocha/bin/_mocha:349:22)
    at Object.<anonymous> (/Users/dmitrizaitsev/Dropbox/Sandbox/voting-server/node_modules/mocha/bin/_mocha:366:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by danielstjules** [comment]
Sorry, we no longer filter out lines from your dependencies: https://github.com/mochajs/mocha/issues/1766 https://github.com/mochajs/mocha/pull/1767

I'd recommend using https://github.com/rstacruz/mocha-clean to reduce some of the noise cause by babylon.

**Comment by dmitriz** [comment]
Thanks, `mocha-clean` is great!
