### ISSUE TITLE
Promises works only with done but not with assertaions

### ISSUE THREAD

**Issue by NoHomey** [mochajs/mocha#2035]
I was bumping my had against a wall whit unit testing my code. So I tried to make a little experiment...
So When I pass a function that simply calls done() to .then all is ok. But when I pass function that tests if 3 is 4 and then calls done() it timeouts.

This is the code the first test passes the second gets timeouted:

```
         describe "my expectaion", ->
           p = undefined
           beforeEach "makes new promise" ->
             p = new Promise (resolve) -> resolve()
            it "just calls done()", (done) ->
              p.then ->
                done()
            it "makes fail assertaion and then calls done()", (done) ->
              p.then ->
                expect(3).to.equal 4
                done()
```

**Comment by danielstjules** [comment]
``` javascript
var assert = require('assert');

describe('my expectation', function() {
  var p;

  beforeEach(function() {
    p = Promise.resolve();
  });

  it('just calls done()', function(done) {
    p.then(done);
  });

  it('makes a failing assertion then calls done()', function(done) {
    // You're not returning the promise, and you're not handling its failure
    p.then(function() {
      assert.equal(3, 4);
      done();
    });
  });

  it('better', function(done) {
    // Here we pass the failure
    p.then(function() {
      assert.equal(3, 4);
      done();
    }).catch(done);
  });

  it('best', function() {
    // Mocha support promises, so there's no need for a callback
    return p.then(function() {
      assert.equal(3, 4);
      done();
    });
  });
});
```

The last 2 specs work as you'd expect:
```
  my expectation
    ✓ just calls done()
    1) makes a failing assertion then calls done()
    2) better
    3) best


  1 passing (2s)
  3 failing

  1) my expectation makes a failing assertion then calls done():
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.


  2) my expectation better:

      AssertionError: 3 == 4
      + expected - actual

      -3
      +4

      at promises.js:25:14

  3) my expectation best:

      AssertionError: 3 == 4
      + expected - actual

      -3
      +4

      at promises.js:33:14
```

Newer versions of node can take advantage of unhandledRejection, which should help detect that case. https://github.com/mochajs/mocha/issues/1926

Hope that helps!

**Comment by NoHomey** [comment]
Yes it did. I wasn't mocking my mongoose DB model right by using proxyquire. Using proxyquire.noCallThru() beforeEach and proxyquire.callThru() afterEach fixed my issue wich in fact was that I had never actually mocked my model since it required mongoose ... and it never reloved/rejected
