### ISSUE TITLE
Mocha Crash -- mocha/lib/reporters/base.js:208:27 -- TypeError: message.match is not a function

### ISSUE THREAD

**Issue by jcalfee** [mochajs/mocha#2050]
Mocha crashes on this exception below.  
mocha": "2.3.4"

```
> mocha --compilers js:babel-core/register --recursive "--watch" "test/wallet_api_spec.js"




  Wallet API client
    ✓ createWallet (147ms)
    ✓ createWallet (duplicate) (144ms)
    ✓ fetchWallet (Recovery)
    ✓ fetchWallet (Not Modified)
    ✓ fetchWallet (Not Exist)
    1) saveWallet
    2) saveWallet (Conflict)
    3) saveWallet (Unknown key)
    ✓ changePassword
    ✓ deleteWallet
WARN: close called with active subscriptions 2


  7 passing (2s)
  3 failing

  4) "after all" hook

  7 passing (2s)
  4 failing

/home/jcalfee/plasma/node_modules/mocha/lib/reporters/base.js:208
      var match = message.match(/^([^:]+): expected/);
                          ^
TypeError: message.match is not a function
    at /home/jcalfee/plasma/node_modules/mocha/lib/reporters/base.js:208:27
    at Array.forEach (native)
    at Function.exports.list (/home/jcalfee/plasma/node_modules/mocha/lib/reporters/base.js:163:12)
    at Spec.Base.epilogue (/home/jcalfee/plasma/node_modules/mocha/lib/reporters/base.js:328:10)
    at emitNone (events.js:72:20)
    at Runner.emit (events.js:163:7)
    at /home/jcalfee/plasma/node_modules/mocha/lib/runner.js:735:12
    at done (/home/jcalfee/plasma/node_modules/mocha/lib/runner.js:619:7)
    at Runner.next [as nextSuite] (/home/jcalfee/plasma/node_modules/mocha/lib/runner.js:586:16)
    at Runner.uncaught (/home/jcalfee/plasma/node_modules/mocha/lib/runner.js:703:17)
    at process.uncaught (/home/jcalfee/plasma/node_modules/mocha/lib/runner.js:727:10)
    at emitOne (events.js:77:13)
    at process.emit (events.js:166:7)
    at process._fatalException (node.js:218:26)
    at emitNone (events.js:72:20)
    at Runner.emit (events.js:163:7)
    at /home/jcalfee/plasma/node_modules/mocha/lib/runner.js:735:12
    at /home/jcalfee/plasma/node_modules/mocha/lib/runner.js:626:9
    at next (/home/jcalfee/plasma/node_modules/mocha/lib/runner.js:283:14)
    at Immediate._onImmediate (/home/jcalfee/plasma/node_modules/mocha/lib/runner.js:319:5)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
npm ERR! Test failed.  See above for more details.

npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/home/jcalfee/opt/iojs-v2.0.1-linux-x64/bin/iojs" "/home/jcalfee/opt/iojs-v2.0.1-linux-x64/bin/npm" "run" "test:watch" "--" "test/wallet_api_spec.js"
npm ERR! node v2.0.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! @graphene/wallet-client@1.0.0 test:watch: `npm test -- --watch "test/wallet_api_spec.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @graphene/wallet-client@1.0.0 test:watch script 'npm test -- --watch "test/wallet_api_spec.js"'.
npm ERR! This is most likely a problem with the @graphene/wallet-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test -- --watch "test/wallet_api_spec.js"
npm ERR! You can get their info via:
npm ERR!     npm owner ls @graphene/wallet-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jcalfee/plasma/libraries/@graphene/wallet-client/npm-debug.log

```

**Comment by chandankrishnan** [comment]
i have also got error 

  authenticate test1
{"name":"myapp","hostname":"bridgelabz1-MS-7788","pid":13408,"level":30,"msg":"Mongoose connected on port 3002","time":"2016-04-30T11:09:14.707Z","v":0}
    ✓ auth for email and password (2710ms)
TypeError: mobile.match is not a function
    at Object.module.exports.isMobile (/home/bridgelabz1/basic-express/app/helper/common.js:30:13)
    at authenticate.mobileToken (/home/bridgelabz1/basic-express/app/model/authenticate.js:39:10)
    at /home/bridgelabz1/basic-express/app/controllers/authenticate.js:51:8
    at Layer.handle [as handle_request] (/home/bridgelabz1/basic-express/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/bridgelabz1/basic-express/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/bridgelabz1/basic-express/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/bridgelabz1/basic-express/node_modules/express/lib/router/layer.js:95:5)
    at /home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:176:3)
    at router (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/bridgelabz1/basic-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:312:13)
    at /home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:176:3)
    at router (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/bridgelabz1/basic-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:312:13)
    at /home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/bridgelabz1/basic-express/node_modules/body-parser/lib/types/urlencoded.js:81:44)
    at Layer.handle [as handle_request] (/home/bridgelabz1/basic-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:312:13)
    at /home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:271:10)
    at compression (/home/bridgelabz1/basic-express/node_modules/compression/index.js:218:5)
    at Layer.handle [as handle_request] (/home/bridgelabz1/basic-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:312:13)
    at /home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bridgelabz1/basic-express/node_modules/express/lib/router/index.js:271:10)
    at /home/bridgelabz1/basic-express/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/home/bridgelabz1/basic-express/node_modules/raw-body/index.js:262:16)
    at done (/home/bridgelabz1/basic-express/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/bridgelabz1/basic-express/node_modules/raw-body/index.js:308:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    ✓ auth for mobile


  2 passing (3s)

**Comment by chandankrishnan** [comment]
i write follwing code for test
var chai    = require('chai')
  , expect  = require('chai').expect
  , request = require('supertest')
  , express = require('express')
  , auth    = require('../../app.js');

describe('authenticate test1',function(){
	this.timeout(30000);
	it('auth for email and password',function(done){
			request('http://localhost:3002')
				.post('/auth/user')
				.send({'email':'chandan@gmail.com','password':'Chandan123'})
				.end(function(err,res){
			   			if(err){
			   				done(err);
			   			}else{
			   				expect(res.request._data.email).to.match(/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{2,6})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/);
			   				expect(res.request._data.password).to.be.a('string')
			   			}
			   			done();
			   		})
	})

	it('auth for mobile',function(done){
			request('http://localhost:3002')
				.post('/auth/mobile')
				.send({'mobile':'+91-7276447408'})
				.end(function(err,res){
						if(err){
							done(err);
						}else{
							expect(res.request._data.mobile).to.be.a('string');
							expect(res.request._data.mobile).to.match(/^(\+){1}91(\-){1}\d[0-9]{9}$/);
						}
						done();
				})
	})
});

**Comment by chandankrishnan** [comment]
i write following code for test

```
var chai    = require('chai')
  , expect  = require('chai').expect
  , request = require('supertest')
  , express = require('express')
  , auth    = require('../../app.js');

describe('authenticate test1',function(){
	this.timeout(30000);
	it('auth for email and password',function(done){
			request('http://localhost:3002')
				.post('/auth/user')
				.send({'email':'chandan@gmail.com','password':'Chandan123'})
				.end(function(err,res){
			   			if(err){
			   				done(err);
			   			}else{
			   				expect(res.request._data.email).to.match(/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{2,6})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/);
			   				expect(res.request._data.password).to.be.a('string')
			   			}
			   			done();
			   		})
	})

	it('auth for mobile',function(done){
			request('http://localhost:3002')
				.post('/auth/mobile')
				.send({'mobile':'+91-7777777777'})
				.end(function(err,res){
						if(err){
							done(err);
						}else{
							expect(res.request._data.mobile).to.be.a('string');
							expect(res.request._data.mobile).to.match(/^(\+){1}91(\-){1}\d[0-9]{9}$/);
						}
						done();
				})
	})
});
```

**Comment by ScottFreeCode** [comment]
@chandankrishnan, that's an unrelated issue: the output you posted shows that the Mocha tests are both still passing (perhaps the error is being caught and logged by the same app or library that it came from?), the stacktrace in it shows the error coming from non-Mocha code (in fact, I don't see Mocha in the stacktrace at all), and it's coming from a `mobile` object in an `isMobile` function rather than the `message` object in the base reporter.

@jcalfee, does this still happen with more recent versions of Mocha? This looks like it should be fixed by e0a43d2f5a39a55e5fe62b4c8734767b8c7fc86e/#2101 in v2.5.x. But if it is still an issue, could you put together a minimal test case we can run to reproduce it? Thanks!

**Comment by chandankrishnan** [comment]
thanks....@ScottFreeCode

**Comment by cullenr** [comment]
I get this error when I set the message of an error to something other than a string.

`assert(false, {status: 400,  message: "Something went wrong"});`

**Comment by boneskull** [comment]
not mocha issue

**Comment by boneskull** [comment]
well, actually, we can probably work around this.

**Comment by ScottFreeCode** [comment]
Actually I think it was a Mocha issue but has since been fixed (not sure how I missed following up on it at the time) -- in 4.0.1 if I use that `assert` example, or manually construct an `Error` with an object `.message` and throw it, either way I get a failing test where the message is `[object Object]`, rather than a crash or anything else weird.
