### ISSUE TITLE
mocha does not work in watch mode with node 5.0 flags

### ISSUE THREAD

**Issue by afaayerhan** [mochajs/mocha#2093]
mocha works fine one only one flag is passed to node compiler but does not work when I add the second compiler opts  --harmony_default_parameters 
λ npm run test-watch

> billboard@1.0.0 test-watch P:\billboard
> SET NODE_ENV=test&& node --harmony_destructuring --harmony_default_parameters  node_modules/mocha/bin/_mocha -w  test/*.test.js

SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (P:\billboard\server.js:5:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (P:\billboard\test\api.test.js:14:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at P:\billboard\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (P:\billboard\node_modules\mocha\lib\mocha.js:216:14)
    at Mocha.run (P:\billboard\node_modules\mocha\lib\mocha.js:468:10)
    at loadAndRun (P:\billboard\node_modules\mocha\bin_mocha:359:22)
    at Object.<anonymous> (P:\billboard\node_modules\mocha\bin_mocha:376:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by ScottFreeCode** [comment]
Hi @afaayerhan,

I just saw this issue (sorry no one got back to you back when it came up!); are you still having trouble with it?

That stack trace appears to show a failure of Node to parse a file required by your `server.js` file, which is required by your `test/api.test.js` file. This is unlikely to be affected by Mocha -- have you tried using `server.js` without Mocha with the same Node flags that cause this issue?

If you do find that this error only occurs when running your files through Mocha and not through Node alone, it would be helpful if we could get [a minimal set of code that we can use to reproduce the issue](https://stackoverflow.com/help/mcve).

If you're no longer having this problem feel free to close this issue!

**Comment by afaayerhan** [comment]
@ScottFreeCode have upgraded node. even forgot about it. but I think I found the problem previously, so closing thanks.
