### ISSUE TITLE
AssertionError thrown in callback inside Promise are not caught

### ISSUE THREAD

**Issue by onip** [mochajs/mocha#2130]
sample test case using node LTS (currently **4.3.1**) and mocha **2.4.5**
```javascript
var assert = require ('assert');

describe ('AssertionError', function () {

  it ('is not caught with callbacks', function () {
    return new Promise (function (resolve) {
      setImmediate (function () {
        assert (false);
        resolve ();
      });
    });
  });

  it ('is caught without callbacks', function () {
    return new Promise (function (resolve) {
      assert (false);

      resolve ();
    });
  });

});
```

produces
```bash
$ ./node_modules/.bin/mocha sample/


  AssertionError
    1) is not caught with callbacks
    2) is caught without callbacks


  0 passing (21ms)
  2 failing

  1) AssertionError is not caught with callbacks:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Immediate._onImmediate (sample/foo_test.js:8:9)

  2) AssertionError is caught without callbacks:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at foffo/foo_test.js:16:7
      at Context.<anonymous> (sample/foo_test.js:15:12)
```

the **setImmediate** call is to represent a classic node-style function with callback.

the main problem (for me at least) happens when running `mocha -w` inside a npm run script: uncaught errors make the npm run exit thus "invalidating" the watch functionality (running `mocha -w` alone doesn't interrupt the watching.

Thanks for any feedback

**Comment by danielstjules** [comment]
Unfortunately, it's a known limitation. You could write the tests in the following way, so that assertion errors are correctly handled by the promise chain as a rejection.

``` javascript
var assert = require ('assert');

describe ('AssertionError', function () {
  it ('is not caught with callbacks', function () {
    return new Promise(function (resolve) {
      setImmediate(resolve);
    }).then(function() {
      assert(false);
    });
  });

  it ('is caught without callbacks', function () {
    return new Promise(function(resolve) {
      resolve();
    }).then(function() {
      assert(false);
    });
  });
});
```
