### ISSUE TITLE
problems with require('@mycompany/mymodule') - npm private modules

### ISSUE THREAD

**Issue by timknip** [mochajs/mocha#2131]
Mocha borks on require's like `@mycompany/mymodule`

```
node_modules/.bin/mocha --compilers js:mocha-traceur spec/
Error: ENOENT: no such file or directory, open 'D:\floorplanner\pdf-export\fp.engine.export\node_modules\@floorplanner\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at D:\floorplanner\pdf-export\fp.engine.export\node_modules\traceur-runner\lib\traceur-runner.js:16:30
    at shouldCompile (D:\floorplanner\pdf-export\fp.engine.export\node_modules\traceur\src\node\require.js:51:20)
    at Object.Module._extensions..js (D:\floorplanner\pdf-export\fp.engine.export\node_modules\traceur\src\node\require.js:66:9)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\floorplanner\pdf-export\fp.engine.export\lib\svg.js:65:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (D:\floorplanner\pdf-export\fp.engine.export\node_modules\traceur\src\node\require.js:68:21)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\floorplanner\pdf-export\fp.engine.export\lib\main.js:68:35)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (D:\floorplanner\pdf-export\fp.engine.export\node_modules\traceur\src\node\require.js:68:21)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\floorplanner\pdf-export\fp.engine.export\spec\main.spec.js:1:22)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (D:\floorplanner\pdf-export\fp.engine.export\node_modules\traceur\src\node\require.js:68:21)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at D:\floorplanner\pdf-export\fp.engine.export\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\floorplanner\pdf-export\fp.engine.export\node_modules\mocha\lib\mocha.js:216:14)
    at Mocha.run (D:\floorplanner\pdf-export\fp.engine.export\node_modules\mocha\lib\mocha.js:468:10)
    at Object.<anonymous> (D:\floorplanner\pdf-export\fp.engine.export\node_modules\mocha\bin\_mocha:403:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by ScottFreeCode** [comment]
Sorry this was missed originally; given that the error is coming from `traceur` which is being used as a compiler, it is *unlikely* that Mocha is causing this issue; however, if you are still affected by it, we'll need more specific example of a minimal project to reproduce the problem and look into it more closely.
