### ISSUE TITLE
When the Response is not a valid object issue

### ISSUE THREAD

**Issue by GranitB** [mochajs/mocha#2133]
Hi 
I have problem a problem with mocha  sorry if it has been posted before me 

When I have a response and is not a valid json object , Its playing creazy the response has a status code and a reponse like this 

Status 400 Bad Request
Response body :  
{"message": "{ "message" : "Field: 'name' is null" }"}

but the mocha says 

```
TypeError: Cannot read property 'statusCode' of undefined
    at Test.<anonymous> (29.Preference.js:371:27)
    at Test.assert (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/supertest/lib/test.js:156:6)
    at assert (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/supertest/lib/test.js:127:12)
    at /Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/superagent/lib/node/index.js:781:12)
    at /Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/superagent/lib/node/index.js:955:25
    at IncomingMessage.<anonymous> (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/superagent/lib/node/parsers/json.js:13:7)
    at endReadableNT (_stream_readable.js:903:12)

```

I know that is not a valid json object but its better to have a better response from mocha 
I had many days problem till I found with Postman what was the problem 

thank you for your work

**Comment by danielstjules** [comment]
I think there might be an issue with the test itself. You're probably doing something like `assert.equal(res.statusCode, X);` but res isn't defined in this case, hence `Cannot read property 'statusCode' of undefined`. I'd recommend adding another assertion that res is defined. Hope that helps! :)

**Comment by GranitB** [comment]
The response is a malformed json so this is why it says is not defined 
is not a problem with the test

**Comment by danielstjules** [comment]
Sure, but you can write your assertions so that they're more helpful. E.g.

``` javascript
var expect = require('chai').expect;
// Instead of this:
expect(res.foo.statusCode).to.equal(200);
// => TypeError: Cannot read property 'statusCode' of undefined

// You can do this:
expect(res).to.have.property('foo');
expect(res.foo.statusCode);
// => Assertion error: res does not have property foo
```

Mocha can't help much with a TypeError, but an AssertionError should look cleaner! :)

**Comment by RamadanPajaziti** [comment]
I have the same problem too. 
If the API returns somehow an object like this: {"message": "{ "message" : "Field: 'name' is null" }"}, then mocha crashes and i cant even read the response, and sure not any type of value of response, like statusCode, body, header etc. 
In this case response(or res) is undefined, like the error of @GranitB states:
`TypeError: Cannot read property 'statusCode' of undefined
    at Test.<anonymous> (29.Preference.js:371:27)
    at Test.assert (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/supertest/lib/test.js:156:6)
    at assert (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/supertest/lib/test.js:127:12)
    at /Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/superagent/lib/node/index.js:781:12)
    at /Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/superagent/lib/node/index.js:955:25
    at IncomingMessage.<anonymous> (/Users/macbookpro/Desktop/java-api/hk-api-v3/hotelkey/node_modules/superagent/lib/node/parsers/json.js:13:7)
    at endReadableNT (_stream_readable.js:903:12)
`
If response is undefined, we cannot read anything. I think this is an error in API because it shouldn't return a message with another object of message key, but mocha should handle this. If you still do not understand, or think this is not an error, i will give you a sample.

**Comment by RamadanPajaziti** [comment]
Also, im sory to say this but i think you shouldn't close one issue, when its still an issue!
I wouldn't figure it out never this problem with mocha, if i would not have Postman.

**Comment by danielstjules** [comment]
Sorry, I closed this cause because it's an expected JS exception with a clear description. You're accessing a property of something that's undefined. I'm not sure what else you'd like to decorate it with.

If you wanted the message to instead read `TypeError: Cannot read property 'statusCode' of undefined variable Foo`, that would require parsing the exception stack trace to get the line/column numbers, and then reading the file to extract the relevant identifier. A PR would be welcome, but I don't see this as gaining much. 

In your example, it should be clear from the stack trace that at line 156, you're trying to access statusCode of a variable or property that's undefined.

**Comment by danielstjules** [comment]
For example, it should be clear why this happens from the stack:

``` javascript
try {
  var foo = {};
  foo.bar.invalid = 'will throw';
} catch (e) {
  console.log(e.stack);
}

$ node test.js
TypeError: Cannot set property 'invalid' of undefined
    at Object.<anonymous> (/Users/dstjules/git/test/test.js:3:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```
