### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode in debug --use_strict

### ISSUE THREAD

**Issue by beautifulcoder** [mochajs/mocha#2143]
Hello,

I am getting this error when I try to debug in the node debugger:

```
node_modules\.bin\mocha debug --ui bdd --use_strict --harmony tests/**/httpHandler.test.js
<     for (let prop in headers) {
<          ^^^
< SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
<     at exports.runInThisContext (vm.js:53:16)
<     at Module._compile (module.js:387:25)
<     at Object.Module._extensions..js (module.js:422:10)
<     at Module.load (module.js:357:32)
<     at Function.Module._load (module.js:314:12)
<     at Module.require (module.js:367:17)
<     at require (internal/module.js:16:19)
<     at Object.<anonymous> (C:\Dev\PickAGrade\tests\engines\httpHandler.test.js:2:16)
<     at Module._compile (module.js:413:34)
<     at Object.Module._extensions..js (module.js:422:10)
<     at Module.load (module.js:357:32)
<     at Function.Module._load (module.js:314:12)
<     at Module.require (module.js:367:17)
<     at require (internal/module.js:16:19)
<     at C:\Dev\PickAGrade\node_modules\mocha\lib\mocha.js:219:27
<     at Array.forEach (native)
```

The tests all pass outside the debugger in node. Has the `--use_strict` flag been added to handle debugging sessions?

**Comment by danielstjules** [comment]
What version of mocha are you using? Support should have been added in https://github.com/mochajs/mocha/pull/1999/files

``` javascript
$ cat test.js
it('test', function() {
  let foo = 'bar';
});

danielstjules:~/git/testing
$ mocha --use_strict test.js


  ✓ test

  1 passing (7ms)
```

If you're unable to upgrade versions of mocha, I'd suggest using https://www.npmjs.com/package/use-strict

Hope that helps! :)

**Comment by beautifulcoder** [comment]
Yes, this works without the `debug` parameter. Once you break into the debugger it no longer works.

**Comment by danielstjules** [comment]
You're right, sorry!

```
$ cat test.js
let foo = 'foo';
dstjules:~/Desktop
$ node --debug --use_strict test.js
Debugger listening on port 5858
dstjules:~/Desktop
$ mocha debug --use_strict test.js
< Debugger listening on port 5858
debug> . ok
break in /usr/local/lib/node_modules/mocha/bin/_mocha:7
  5  */
  6
> 7 var program = require('commander'),
  8   path = require('path'),
  9   fs = require('fs'),
debug> c
< /Users/dstjules/Desktop/test.js:1
< (function (exports, require, module, __filename, __dirname) { let foo = 'foo';
<                                                               ^^^
< SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by danielstjules** [comment]
From https://github.com/mochajs/mocha/issues/2156#issue-140902482
It seems to work with _mocha but not mocha

**Comment by bitsofinfo** [comment]
+1

**Comment by nfedyk** [comment]
+1 same issue

**Comment by jgrosche** [comment]
+1 same as @bitsofinfo

**Comment by daithi-coombes** [comment]
+1 same issue

**Comment by QuantumInformation** [comment]
I have issue for a simple node file using v5.10.1

even with `--use_strict`

**Comment by boneskull** [comment]
unclear to me if this is still an issue.  if it is, would accept PR to fix

**Comment by juergba** [comment]
Node's `debug` was replaced by `inspect`, this shouldn't be an issue anymore.
