### ISSUE TITLE
Problem with --use_strict

### ISSUE THREAD

**Issue by nbasov** [mochajs/mocha#2156]
Trying to use --use_strict option:

```
$ ./node_modules/mocha/bin/mocha --use_strict tests/integration/contractor/account.js
/home/nbasov/Documents/~SSPlatform/ssp-api/node_modules/mocha/bin/_mocha:355
  function loadAndRun() {
  ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

But works good when using "_mocha":

```
$ ./node_modules/mocha/bin/_mocha --use_strict tests/integration/contractor/account.js
...
  3 passing (659ms)
```

Is it possible to use --use_strict with mocha not _mocha?

mocha 2.4.5
node: 0.12.4
npm: 2.10.1

**Comment by danielstjules** [comment]
Thanks for opening the issue! Since we already have one open on the topic, I hope to direct the conversation over to https://github.com/mochajs/mocha/issues/2156
