### ISSUE TITLE
Glob difficulties: {app,src}/**/*.spec.js not working

### ISSUE THREAD

**Issue by callumacrae** [mochajs/mocha#2174]
Hello!

This works:

```
mocha app/**/*.spec.js
mocha src/**/*.spec.js
```

This does not:

```
mocha {app,src}/**/*.spec.js
```

Neither does this:

```
mocha app/**/*.spec.js src/**/*.spec.js
```

The error is… completely free of new lines. I also don't understand it.

Here it is:

`
error: uncaughtException: Cannot read property 'protocol' of undefined date=Tue Mar 29 2016 16:09:44 GMT+0100 (BST), pid=57513, uid=501, gid=20, cwd=/Users/callumacrae/Sites/lmn/phoenix, execPath=/Users/callumacrae/.nvm/versions/node/v4.3.2/bin/node, version=v4.3.2, argv=[/Users/callumacrae/.nvm/versions/node/v4.3.2/bin/node, /Users/callumacrae/.npm/lib/node_modules/mocha/bin/_mocha, --require, should, --require, ./test/setup, app/app.spec.js, app/lib/assets.spec.js, app/lib/eagleRequest.spec.js, app/lib/lang.spec.js, src/js/partials/BarTabs/duck.spec.js, src/js/partials/BarTabs/index.spec.js, src/js/partials/BookPreview/index.spec.js, src/js/partials/Dedication/DedicationSave.spec.js, src/js/partials/Dedication/index.spec.js, src/js/partials/GiftOption/index.spec.js, src/js/partials/GiftOptionList/duck.spec.js, src/js/partials/GiftOptionList/index.spec.js, src/js/partials/LMNChildFields/duck.spec.js, src/js/store/customisation/characters.duck.spec.js, src/js/store/customisation/dedication.duck.spec.js, src/js/store/preview/overlay.duck.spec.js], rss=242008064, heapTotal=202270048, heapUsed=162439064, loadavg=[2.47021484375, 2.6083984375, 2.54443359375], uptime=2411355, trace=[column=41, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server.js, function=null, line=39, method=null, native=false, column=2, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server.js, function=, line=247, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=416, method=_extensions..js, native=false, column=7, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=134, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=300, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=353, method=require, native=false, column=17, file=internal/module.js, function=require, line=12, method=null, native=false, column=9, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js, function=loadDependencies, line=89, method=null, native=false, column=9, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js, function=null, line=97, method=null, native=false, column=2, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js, function=, line=101, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=416, method=_extensions..js, native=false, column=7, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=134, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=300, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=353, method=require, native=false, column=17, file=internal/module.js, function=require, line=12, method=null, native=false, column=9, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/sandbox.js, function=loadDependencies, line=149, method=null, native=false, column=9, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/sandbox.js, function=null, line=161, method=null, native=false, column=2, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/sandbox.js, function=, line=168, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=416, method=_extensions..js, native=false, column=7, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=134, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=300, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=353, method=require, native=false, column=17, file=internal/module.js, function=require, line=12, method=null, native=false, column=9, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon.js, function=loadDependencies, line=29, method=null, native=false, column=9, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon.js, function=null, line=40, method=null, native=false, column=2, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon.js, function=, line=47, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=416, method=_extensions..js, native=false, column=7, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=134, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=300, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=353, method=require, native=false, column=17, file=internal/module.js, function=require, line=12, method=null, native=false, column=1, file=index.spec.js, function=, line=2, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false, column=5, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js, function=loader, line=126, method=null, native=false, column=7, file=/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=136, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=300, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=353, method=require, native=false, column=17, file=internal/module.js, function=require, line=12, method=null, native=false, column=27, file=/Users/callumacrae/.npm/lib/node_modules/mocha/lib/mocha.js, function=null, line=185, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=14, file=/Users/callumacrae/.npm/lib/node_modules/mocha/lib/mocha.js, function=Mocha.loadFiles, line=182, method=loadFiles, native=false, column=31, file=/Users/callumacrae/.npm/lib/node_modules/mocha/lib/mocha.js, function=Mocha.run, line=394, method=run, native=false, column=16, file=/Users/callumacrae/.npm/lib/node_modules/mocha/bin/_mocha, function=, line=394, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=416, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=300, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=441, method=Module.runMain, native=false, column=18, file=node.js, function=startup, line=134, method=null, native=false, column=3, file=node.js, function=null, line=962, method=null, native=false], stack=[TypeError: Cannot read property 'protocol' of undefined,     at /Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server.js:39:41,     at Object.<anonymous> (/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server.js:247:2),     at Module._compile (module.js:409:26),     at Module._extensions..js (module.js:416:10),     at Object.require.extensions.(anonymous function) [as .js] (/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js:134:7),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Module.require (module.js:353:17),     at require (internal/module.js:12:17),     at loadDependencies (/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js:89:9),     at /Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js:97:9,     at Object.<anonymous> (/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/util/fake_server_with_clock.js:101:2),     at Module._compile (module.js:409:26),     at Module._extensions..js (module.js:416:10),     at Object.require.extensions.(anonymous function) [as .js] (/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js:134:7),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Module.require (module.js:353:17),     at require (internal/module.js:12:17),     at loadDependencies (/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/sandbox.js:149:9),     at /Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/sandbox.js:161:9,     at Object.<anonymous> (/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon/sandbox.js:168:2),     at Module._compile (module.js:409:26),     at Module._extensions..js (module.js:416:10),     at Object.require.extensions.(anonymous function) [as .js] (/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js:134:7),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Module.require (module.js:353:17),     at require (internal/module.js:12:17),     at loadDependencies (/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon.js:29:9),     at /Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon.js:40:9,     at Object.<anonymous> (/Users/callumacrae/Sites/lmn/phoenix/node_modules/sinon/lib/sinon.js:47:2),     at Module._compile (module.js:409:26),     at Module._extensions..js (module.js:416:10),     at Object.require.extensions.(anonymous function) [as .js] (/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js:134:7),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Module.require (module.js:353:17),     at require (internal/module.js:12:17),     at Object.<anonymous> (index.spec.js:2:1),     at Module._compile (module.js:409:26),     at loader (/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js:126:5),     at Object.require.extensions.(anonymous function) [as .js] (/Users/callumacrae/Sites/lmn/phoenix/node_modules/babel-register/lib/node.js:136:7),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Module.require (module.js:353:17),     at require (internal/module.js:12:17),     at /Users/callumacrae/.npm/lib/node_modules/mocha/lib/mocha.js:185:27,     at Array.forEach (native),     at Mocha.loadFiles (/Users/callumacrae/.npm/lib/node_modules/mocha/lib/mocha.js:182:14),     at Mocha.run (/Users/callumacrae/.npm/lib/node_modules/mocha/lib/mocha.js:394:31),     at Object.<anonymous> (/Users/callumacrae/.npm/lib/node_modules/mocha/bin/_mocha:394:16),     at Module._compile (module.js:409:26),     at Object.Module._extensions..js (module.js:416:10),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Function.Module.runMain (module.js:441:10),     at startup (node.js:134:18),     at node.js:962:3]
`

Any ideas what's wrong? How can I fix this?

**Comment by callumacrae** [comment]
This wasn't an issue with mocha, in the end. A test file in the app directory was defining `global.window`, which was causing sinon, required in a test file in the src directory, to blow up.

Not sure why it was working for my colleague and not for me or CI. Ah well.
