### ISSUE TITLE
Failed on Node6

### ISSUE THREAD

**Issue by popomore** [mochajs/mocha#2215]
```
$ ./node_modules/.bin/node --version
v6.0.0-rc.2

$ cat ./node_modules/mocha/package.json | head -n 3
{
  "name": "mocha",
  "version": "2.4.5",

$ ./node_modules/.bin/node ./node_modules/.bin/mocha
module.js:128
  for (var i = 0; i < exts.length; i++) {
                          ^

TypeError: Cannot read property 'length' of undefined
    at tryExtensions (module.js:128:27)
    at tryPackage (module.js:107:10)
    at Function.Module._findPath (module.js:182:18)
    at Function.Module._resolveFilename (module.js:434:25)
    at Function.Module._load (module.js:384:25)
    at Module.require (module.js:464:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/popomore/code/tmp/a/node_modules/mocha/bin/_mocha:12:11)
    at Module._compile (module.js:539:32)
    at Object.Module._extensions..js (module.js:548:10)
```

**Comment by popomore** [comment]
It's the bug of nodejs https://github.com/nodejs/node/issues/6214

**Comment by boneskull** [comment]
yikes! thanks.
