### ISSUE TITLE
Error code remains zero when assertion failed

### ISSUE THREAD

**Issue by sedubois** [mochajs/mocha#2249]
I've been asserting deep equality of React components, and noticed a test silently failing with return code 0 (NB: I'm generally quite new to JavaScript). This seems to relate to React objects containing `Symbol`.

Considering the following test:

```js
const expect = require('chai').expect;
const a = Symbol('a');
console.log(`a = ${a.toString()} of type ${typeof a}`);

it("deep equal demo", () => {
  expect({ a, b: 'foo' }).to.deep.equal({ a, b: 'bar' });
});

```

I get a return code of 0 instead of 1, thus test is silently ignored in CI:
```
$ node --version; mocha --version; mocha demo.test.js; echo "Return code is $?"
v5.11.0
2.4.5
a = Symbol(a) of type symbol

  1) deep equal demo

  0 passing (12ms)
  1 failing

Return code is 0
```

If I comment out the `it` (leaving `expect` uncommented), I can see that the exception is thrown by chai and the error code is correct:
```
$ node --version; mocha --version; mocha demo.test.js; echo "Return code is $?"
v5.11.0
2.4.5
a = Symbol(a) of type symbol

XXX/node_modules/chai/lib/chai/assertion.js:107
      throw new AssertionError(msg, {
      ^
AssertionError: expected { a: {}, b: 'foo' } to deeply equal { a: {}, b: 'bar' }
    at Assertion.assertEqual (XXX/node_modules/chai/lib/chai/core/assertions.js:485:19)
    at Assertion.ctx.(anonymous function) [as equal] (XXX/node_modules/chai/lib/chai/utils/addMethod.js:41:25)
    at Object.<anonymous> (XXX/demo.test.js:6:35)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at XXX/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (XXX/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (XXX/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (XXX/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
Return code is 1
```

In both cases, the test passes with return code 0 if I change `bar` to `foo`.

The problem seems specific to the ES2015 `Symbol`, although it seems to be properly recognized as the logs show. 

It's not clear to me if mocha needs Babel in order to recognize `Symbol` (the log above makes me think not), but adding `--compilers js:babel-register,js:babel-polyfill` did not help.

**Comment by boneskull** [comment]
@sedubois this was fixed in 872684f44f677774f544373abf753b5080af8655

`npm install mochajs/mocha` to grab it
