### ISSUE TITLE
Mocha 2.5.0 runs with error

### ISSUE THREAD

**Issue by carlnordenfelt** [mochajs/mocha#2272]
I just ran our tests where we have mocha: * in package.json and got this error:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'to-iso-string'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/nordenfelt/Documents/dev/jayway/tobii/tobii-fire-cloud/services/apiAuthorizer/node_modules/mocha/lib/utils.js:15:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/nordenfelt/Documents/dev/jayway/tobii/tobii-fire-cloud/services/apiAuthorizer/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

I reverted back to version 2.4.5 in package.json and the tests worked.

**Comment by gabrieledarrigo** [comment]
Same for me, but I solved in installing `to-iso-string` as my project dependecy.
It is a devDependecies of mocha, but somehow is not installed:

```
├─┬ mocha@2.5.0 
│ ├── commander@2.3.0 
│ ├── diff@1.4.0 
│ ├── escape-string-regexp@1.0.2 
│ ├─┬ glob@3.2.11 
│ │ └─┬ minimatch@0.3.0 
│ │   ├── lru-cache@2.7.3 
│ │   └── sigmund@1.0.1 
│ ├── growl@1.9.2 
│ ├─┬ jade@0.26.3 
│ │ ├── commander@0.6.1 
│ │ └── mkdirp@0.3.0 
│ └── supports-color@1.2.0 
├── moment@2.13.0 
```

I'm reverting to 2.4 too

**Comment by deyhle** [comment]
Same here.
It should probably be in "dependencies" in the package.json, not in "devDependencies"?

**Comment by boneskull** [comment]
fixing... thanks, sorry
