### ISSUE TITLE
ENAMETOOLONG when files() from utils.js encounters a symlink loop

### ISSUE THREAD

**Issue by jedwards1211** [mochajs/mocha#2330]
On one of my projects, when I run Mocha in watch mode, I get the error below.  This is because `meteor-roles/examples/flow-router/alanning:roles` is a symlink back to `meteor-roles`.

```
Error: ENAMETOOLONG: name too long, stat '/Users/andy/jcore-portal/meteor-roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/examples/flow-router/packages/alanning:roles/docs/assets/vendor/prettify/prettify-min.css'
    at Error (native)
    at fs.statSync (fs.js:892:18)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:234:11
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at /Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:235:17
    at Array.forEach (native)
    at Object.exports.files (/Users/andy/jcore-portal/node_modules/mocha/lib/utils.js:232:6)
    at Object.<anonymous> (/Users/andy/jcore-portal/node_modules/mocha/bin/_mocha:353:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by boneskull** [comment]
Sounds plausible.  My suggestion for now is to avoid Mocha's "watch" functionality and use another tool which is purpose-built.  Since the implementation is hand-rolled, there are many edge cases which are not covered.

**Comment by jedwards1211** [comment]
@boneskull okay, any recommendations?  I was using a hand-rolled Webpack adapter for Jasmine in the past because Webpack is very good at watching, but I'd rather avoid bundling because it's slower and complicates the source maps.

**Comment by jedwards1211** [comment]
@boneskull nevermind, https://github.com/shama/gaze looks like it will work well

**Comment by jakehoskins** [comment]
I am seeing the same issue and it is is really annoying. I have symlinks in my repo and i get this consistently. 
@boneskull i would rather not use gaze. Can't we just make the `ignore` in utils dynamic? I.e. via a .opts file ? I would be happy to prepare a PR if you think it's a good solution.
