### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by asciiman** [mochajs/mocha#2414]
`$ mocha  test -r jsdom-global/register --compilers js:babel-core/register --recursive`

Exports used directly in our project work fine.

```
import * as exampleActions from './exampleActions';
import * as authentication from './authentication';
import * as questions from './questions';

export default {
  exampleActions,
  authentication,
  questions
};
```

Exports from a plugin (react-native-storage) receive an error.

```
/business-logic/node_modules/react-native-storage/storage.js:7
export default class Storage {
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/business-logic/node_modules/babel-register/lib/node.js:159:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/business-logic/src/utils/storageHelper.js:1:157)
```

**Comment by boneskull** [comment]
see babel docs for "why aren't my node_modules being transpiled?" or something similar
