### ISSUE TITLE
invalid reporter "html-cov"

### ISSUE THREAD

**Issue by tuanlv1206** [mochajs/mocha#2420]
sudo mocha indexSpec.js --reporter html-cov
"html-cov" reporter not found
/usr/local/lib/node_modules/mocha/lib/mocha.js:164
      throw new Error('invalid reporter "' + reporter + '"');
      ^

Error: invalid reporter "html-cov"
    at Mocha.reporter (/usr/local/lib/node_modules/mocha/lib/mocha.js:164:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:209:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

Can anyone help me to deal with this issue? thanks a lot!

**Comment by gurdiga** [comment]
Hey @tuanlv1206! 🙂

It looks like the `html-cov` [was dropped since 3.0.0](https://github.com/mochajs/mocha/issues/2356). 😶

**Comment by tuanlv1206** [comment]
@gurdiga thanks!
