### ISSUE TITLE
Exit Code 0 when mocha stack traces

### ISSUE THREAD

**Issue by darkn3rd** [mochajs/mocha#2427]
### Description

Recent changes to mocha caused stack traces, which is fine, but what is not fine is that the exit code is 0.

### Actual Results

```
$ NODE_ENV="test" PORT="6004"  mocha --recursive --timeout 8000 --reporter ${REPORTER_OPTS} ${COLOR_OPTS} 2>&1 | tee -a ${APP_ROOT}/logs/app-test.log
...
Created logger states level info path logs/test.log
Express server listening on port 6004 in test mode
module.js:327
    throw err;
    ^

Error: Cannot find module '../../services/selectLite/LiteActivityService'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/gobalto/test/controllers/Sites.js:13:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/lib/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/lib/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/usr/lib/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/usr/lib/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
$ echo $?
0
```

### Expected Behavior

Mocha would return a non-0 exit code.

**Comment by darkn3rd** [comment]
Small Test Case Snippet to reproduce case:

```javascript
require('./this/does/not/exist');

describe('This test fails before it even starts',function(){
  it('Should pass',function(done){
    done();
  })
});
```

**Comment by boneskull** [comment]
@darkn3rd I saw someone else complaining about this on twitter, but I can't reproduce, even with some of your options:

```shell
$ NODE_ENV=test mocha test2.js --timeout 8000 --reporter spec; echo $?
module.js:442
    throw err;
    ^

Error: Cannot find module './this/does/not/exist'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/alien/mochajs/mocha/test2.js:1:63)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Volumes/alien/mochajs/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Volumes/alien/mochajs/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Volumes/alien/mochajs/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/Volumes/alien/mochajs/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
1

```

I'm using v6.3.0, which is not what you're running.  If I had to guess, 4.something?

**Comment by boneskull** [comment]
Can't reproduce in Node v4.4.7 either

**Comment by boneskull** [comment]
Is there a `mocha.opts` anywhere? etc. etc.  any more info would be good

**Comment by gurdiga** [comment]
I have tried to reproduce, and here is what I found: https://asciinema.org/a/c8wxmyzuo3x79fqmftv9cmbig. 🤓

So I would think that `mocha`’s return value is swallowed by `tee`, and the `0` that’s coming out is actually from tee.

What do you guys think? 🤔

**Comment by darkn3rd** [comment]
I suspect it is `tee`. I containerized their project and started using `tee` to redirect output to logs.

**Comment by darkn3rd** [comment]
Yeah, it was `tee`. Close.
