### ISSUE TITLE
Mochawesome reporter no more working

### ISSUE THREAD

**Issue by chrisvidal** [mochajs/mocha#2432]
not sure what happened here but Since this morning, i got this error when running
with mochawesome 1.4.0, and it used to work properly

````bash
mocha --timeout 5000 tests/stats --reporter mochawesome
"mochawesome" reporter not found
/Users/qwerty/npm/lib/node_modules/mocha/lib/mocha.js:164
      throw new Error('invalid reporter "' + reporter + '"');
      ^

Error: invalid reporter "mochawesome"
    at Mocha.reporter (/Users/qwerty/npm/lib/node_modules/mocha/lib/mocha.js:164:13)
    at Object.<anonymous> (/Users/qwerty/npm/lib/node_modules/mocha/bin/_mocha:207:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
````

**Comment by gurdiga** [comment]
Hey @chrisvidal! 🙂

I have tried to reproduce this with a fresh install of both `mocha` and `mochawesome@1.4.0`, and it seems to have worked well, I mean I couldn’t get that error. 🤔

Could you please take a quick look and spot what may have been different in my case? Here is my terminal recording: https://asciinema.org/a/c9yhp355i36dgn77n571fowll. 🤓

**Comment by chrisvidal** [comment]
Hi @gurdiga 
thanks for your reply,
my mocha installation is global and seems to have some issue.
After installing mocha locally, the problem has been solved
