### ISSUE TITLE
use thunk-mocha with mocha@3.1.1 got error

### ISSUE THREAD

**Issue by atian25** [mochajs/mocha#2527]
https://github.com/thunks/thunk-mocha

work at 3.1.0

```shell
/Users/tz/Workspaces/eggjs/aliyun-egg/node_modules/.3.1.1@mocha/lib/runnable.js:52
  this.async = fn && fn.length;
             ^

TypeError: Cannot set property async of #<Runnable> which has only a getter
    at Test.Runnable [as constructor] (/Users/tz/Workspaces/eggjs/aliyun-egg/node_modules/.3.1.1@mocha/lib/runnable.js:52:14)
    at new Test (/Users/tz/Workspaces/eggjs/aliyun-egg/node_modules/.3.1.1@mocha/lib/test.js:28:12)
    at context.it.context.specify (/Users/tz/Workspaces/eggjs/aliyun-egg/node_modules/.3.1.1@mocha/lib/interfaces/bdd.js:86:18)
```

**Comment by atian25** [comment]
mv to thunk-mocha issue
