### ISSUE TITLE
before/after have wrong "this" scope?

### ISSUE THREAD

**Issue by zzen** [mochajs/mocha#253]
beforeEach/afterEach correctly invoke with "this" set to the scope of the suite. before/after however use global object instead. Maybe I'm missing something, but it seems weird why this would be intentional.
## Test case:

```
assert = require('assert')

describe('scope is lost',function() {
    before(function() { this.foo="world"}) // also this leaks into global scope
    describe('when using before/after', function() {
        it('should have value set for foo', function() { assert.equal(this.foo,'world') })
    })
})

describe('scope works fine',function() {
    beforeEach(function() { this.bar="hello"})
    describe('when using beforeEach/afterEach', function() {
        it('should have value set for bar', function() { assert.equal(this.bar,'hello') })
    })
})
```
## Result:

```
scope is lost
  0) "before all" hook
  when using before/after
    1) should have value set for foo

scope works fine
  when using beforeEach/afterEach
    ✓ should have value set for bar 


✖ 2 of 2 tests failed:

0) scope is lost "before all" hook:
   Error: global leak detected: foo
    at Runner.checkGlobals (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:103:21)
    at Runner.<anonymous> (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:44:44)
    at Runner.emit (events.js:64:17)
    at /Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:170:12
    at Hook.run (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runnable.js:155:5)
    at next (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:167:10)
    at Array.<anonymous> (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:177:5)
    at EventEmitter._tickCallback (node.js:126:26)

1) scope is lost when using before/after should have value set for foo:

ssertionError: "world" == "undefined"
    at Test.fn (/Users/jakub/Documents/test.js:6:59)
    at Test.run (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runnable.js:153:32)
    at Runner.runTest (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:272:10)
    at /Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:313:12
    at next (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:200:14)
    at /Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:209:7
    at next (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:157:23)
    at Array.<anonymous> (/Users/jakub/.nvm/v0.4.12/lib/node_modules/mocha/lib/runner.js:177:5)
    at EventEmitter._tickCallback (node.js:126:26)
```

**Comment by fernandoPalaciosGit** [comment]
Thanks, the only way is reference by the chain testing, it -> it -> it, thats not preaty nice
```javascript
this.test.parent.parent
```

**Comment by fernandoPalaciosGit** [comment]
Maybe creating a simple Object for the main ñcontext testing
```javascript
var Test = {
    connection: null
};

beforeEach(function () {
    this.connection = new MongoDbConn();
}.bind(Test));

describe('something', function(){
  before(function(done){
    initwhatever(function(err, conn){
      this.connection.query('select something', done)
      done();
  }.bind(Test))
```

[https://github.com/fernandoPalaciosGit/leemelo/blob/master/test/test-http-request/test.api.books.js](A simple Restfull API testing)

**Comment by boneskull** [comment]
My recommendation is to use closures instead of assigning things to `this`.
