### ISSUE TITLE
Test fail with Appveyor

### ISSUE THREAD

**Issue by torn4dom4n** [mochajs/mocha#2563]
I am using `devtool` and `mocha` to debug [`atom-keymap`](https://github.com/atom/atom-keymap). Although it success on [**Travis**](https://travis-ci.org/atom/atom-keymap/builds/171777087) but it is failing on [**Appveyor**](https://ci.appveyor.com/project/torn4dom4n/atom-keymap/build/1.0.44):

```
Error: 
C:\projects\atom-keymap\node_modules\mocha\bin\_mocha
Cannot find module 'C:\projects\atom-keymap\spec\fixtures'
  at Module._resolveFilename (module.js:455:15)
  at Function.Module._resolveFilename (C:\projects\atom-keymap\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at C:\projects\atom-keymap\node_modules\mocha\lib\mocha.js:222:27
  at Array.forEach (native)
  at Mocha.loadFiles (C:\projects\atom-keymap\node_modules\mocha\lib\mocha.js:219:14)
  at Mocha.run (C:\projects\atom-keymap\node_modules\mocha\lib\mocha.js:487:10)
  at Object.<anonymous> (C:\projects\atom-keymap\node_modules\mocha\bin\_mocha:458:18)
  at Module._compile (module.js:556:32)
  at Object.devtoolCompileModule (C:\projects\atom-keymap\node_modules\devtool\lib\require-hook.js:32:14)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at EventEmitter.<anonymous> (C:\projects\atom-keymap\node_modules\devtool\lib\preload.js:88:16)
  at emitOne (events.js:96:13)
  at EventEmitter.emit (events.js:188:7)
```

**Comment by ScottFreeCode** [comment]
I don't know if this is Mocha or Devtool, but I can see that something's trying to load your `spec/fixtures` directory as though it were a module/file. I also see your npm test scripts reference `spec/*`, which might be interpreted variously by OS-specific globbing behavior. Try quoting it to avoid OS shell globbing (`"spec/*"` instead of `spec/*`) and see if that resolves the issue?

**Comment by ScottFreeCode** [comment]
Another possible solution if that doesn't work (or if it makes both OSes fail; I'd expect quoting to at least make the behavior consistent on the different CI environments...) would be to include the file extension in the glob, e.g. `spec/*.js`, so folder names aren't matched.

**Comment by torn4dom4n** [comment]
@ScottFreeCode I used :
```sh
"test": "devtool node_modules/mocha/bin/_mocha -qc --colors spec/helpers/setup.js spec/helpers-spec.coffee spec/keymap-manager-spec.coffee
```
```sh
"test": "devtool  --quit --console node_modules/mocha/bin/_mocha --colors spec/helpers/setup.js spec/*.coffee *.js *.coffee",
```
```sh
"test": "devtool  --quit --console node_modules/mocha/bin/_mocha --colors spec/helpers/setup.js spec/*.coffee",
```
But it is still failing. You can see at here: https://ci.appveyor.com/project/torn4dom4n/atom-keymap/history
Here is my history commit: https://github.com/atom/atom-keymap/pull/159
I hope you can help!

**Comment by ScottFreeCode** [comment]
So, when I looked at the `spec/fixtures` directory issue I failed to notice that the `spec` directory doesn't contain any `.js` files, only `.coffee` files; in this case, `spec/*.coffee` would be correct. Also, adding `*.js`/`*.coffee` looks for test files in the project root, which is a change in location from `spec/*`. (You can also see on the Travis status for each commit in the PR that these two things caused issues there too.) Looks you got both of those things figured out in the last commit though, so the path/globbing issue should be resolved. (I still would recommend quoting as a rule to minimize OS-based globbing behavior, but it may not be strictly necessary in this instance at the current time.)

In fact, the error in the last commit, here: https://ci.appveyor.com/project/torn4dom4n/atom-keymap/build/1.0.47 is completely different, so it does seem the current path works.

According to the stacktrace, the new error looks related to the `keyboard-layout` dependency.
