### ISSUE TITLE
Run a single file ok but not with multi test files

### ISSUE THREAD

**Issue by ian4hu** [mochajs/mocha#2588]
I run a single test file by `mocha --compilers js:babel-register --recursive ./src/service/__test__/wechat.js` get all tests passed, like bellow
```text
[ian@ian-mbp ~/git/kindle-server (master)]$ mocha --compilers js:babel-register --recursive ./src/service/__test__/wechat.js 


  WeChatService
    #checkSignature
[2016-11-23 15:53:25.348] [INFO] wechat.js:WeChatService - Signature check is skipped because config.checkSignature = false
      ✓ should skiped when checkSignature is false
      ✓ should not skiped when checkSignature is true
      ✓ signature should be valid
      ✓ signature should be invalid 1
      ✓ signature should be invalid 2
    #getToken
      ✓ ok
      ✓ invalid appid


  7 passing (149ms)
```
but when I run like `mocha --compilers js:babel-register --recursive ./src/***/__test__/*.js`, the test is failed
```text
[ian@ian-mbp ~/git/kindle-server (master)]$ mocha --compilers js:babel-register --recursive ./src/***/__test__/*.js


  #DI
    ✓ Inject an object

  WeChatService
    #checkSignature
[2016-11-23 15:56:48.007] [INFO] wechat.js:WeChatService - Signature check is skipped because config.checkSignature = false
      ✓ should skiped when checkSignature is false
      ✓ should not skiped when checkSignature is true
      ✓ signature should be valid
      ✓ signature should be invalid 1
      ✓ signature should be invalid 2
    #getToken
      1) ok
      2) invalid appid


  6 passing (153ms)
  2 failing

  1) WeChatService #getToken ok:
     TypeError: Cannot convert undefined or null to object
      at getOwnPropertyNames (native)
      at getOwnPropertyNames (node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/private/private.js:72:20)
      at Function.assign (node_modules/di/node_modules/traceur/bin/traceur-runtime.js:163:19)
      at FetchMock.(anonymous function) [as getOnce] (node_modules/fetch-mock/src/fetch-mock.js:281:47)
      at Context.<anonymous> (src/service/__test__/wechat.js:80:17)

  2) WeChatService #getToken invalid appid:
     TypeError: Cannot convert undefined or null to object
      at getOwnPropertyNames (native)
      at getOwnPropertyNames (node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/private/private.js:72:20)
      at Function.assign (node_modules/di/node_modules/traceur/bin/traceur-runtime.js:163:19)
      at FetchMock.(anonymous function) [as getOnce] (node_modules/fetch-mock/src/fetch-mock.js:281:47)
      at Context.<anonymous> (src/service/__test__/wechat.js:92:17)


```

What is wrong with my test.
If you guys need, I can provide the sample code.
Here is my __test__/wechat.js
```javascript
/*
* @Author: Ian Hu
* @Date:   2016-11-19 23:28:35
* @Last Modified by:   Ian Hu
* @Last Modified time: 2016-11-23 10:02:45
*/

import {describe, it, before, after} from 'mocha'
import {expect, assert} from 'chai'
import log4js from 'koa-log4'
import mockery from 'mockery'

log4js.configure({
  levels: {
    '[all]': 'info'
  },
  appenders: [{type: 'console'}]
})

let WeChatService, WeChatApiError, wechatService, fetchMock

const token = 'mytoken'
const signature = '182d3eb04d23938eaab9f916d48995755c8f8093'
const params = [2, 3]

const appid = 'appid'
const secret = 'secret'

describe('WeChatService', () => {
  before(function () {
    mockery.enable({
      warnOnReplace: false,
      warnOnUnregistered: false
    })
    fetchMock = require('fetch-mock')
    mockery.registerMock('node-fetch', fetchMock.fetchMock)
    let holder = require('../wechat')
    WeChatService = holder.default
    WeChatApiError = holder.WeChatApiError
    // {'default': WeChatService, WeChatApiError} = (require('../wechat'))
    wechatService = new WeChatService({checkSignature: true, urlPrefix: 'http://127.0.0.1/cgi-bin'})
  })

  after(function () {
    mockery.disable()
  })

  describe('#checkSignature', () => {
    it('should skiped when checkSignature is false', () => {
      let result = new WeChatService({checkSignature: false}).checkSignature('wrong', token, ...params)
      expect(result).to.equal(true)
    })

    it('should not skiped when checkSignature is true', () => {
      let result = new WeChatService({checkSignature: true}).checkSignature('wrong', token, ...params)
      expect(result).to.equal(false)
    })

    it('signature should be valid', () => {
      let result = wechatService.checkSignature(signature, token, ...params)
      expect(result).to.equal(true)
    })

    it('signature should be invalid 1', () => {
      let result = wechatService.checkSignature('wrong', token, ...params)
      expect(result).to.equal(false)
    })

    it('signature should be invalid 2', () => {
      let result = wechatService.checkSignature(signature, 'wrong-token', ...params)
      expect(result).to.equal(false)
    })
  })

  describe('#getToken', () => {
    before(() => {
      // not defined
    })
    it('ok', done => {
      fetchMock.getOnce(/\/token/, {access_token: 'fake_token', expires_in: 7200})
      wechatService.getToken(appid, secret).then(resp => {
        let {errcode, errmsg, access_token: accessToken, expires_in: expires} = resp
        // console.info('resp: %j', resp)
        expect(errcode).to.be.undefined
        expect(errmsg).to.be.undefined
        expect(accessToken).to.be.a('string')
        expect(expires).not.to.be.NaN
      }).then(done)
    })

    it('invalid appid', done => {
      fetchMock.getOnce(/\/token/, {errcode: 40013, errmsg: 'invalid appid'})
      wechatService.getToken('wrong appid', secret).then(resp => {
        assert.fail()
      }).catch(err => {
        expect(err).to.be.instanceof(Error)
          .and.to.be.instanceof(WeChatApiError)
          .and.have.property('code', 40013)
      }).then(done)
    })
  })
})

```

**Comment by ScottFreeCode** [comment]
It sounds as though the `  #DI
    ✓ Inject an object` test or some other file matched by the `**/__test__/*.js` pattern is doing something that breaks `fetch-mock` (by causing a variable that's passed to `getOwnPropertyNames` to be `null` or `undefined`, it seems); seeing only wechat.js doesn't give me much more insight as to what's causing the breakage though, since it appears to be other files that are causing the issue.

It may also help you to try creating (or narrowing down to) minimal but complete example code that will recreate the issue, rather than posting files from your actual test -- not just because you can then post everything we need to see without having to dump your project's whole test on us (although on our end that is certainly an improvement), but also because you may gain a better understanding of what's happening in the process of isolating the underlying problem from your real code in which it merely happened to occur.

P.S. `--recursive` doesn't do anything if you specify the full path to the .js file, either explicitly or through globbing. And `***` as a glob doesn't, as far as I'm aware, have any specific meaning (though in this case apparently it's being treated the same as `**`, which means to match any number of directories).

**Comment by boneskull** [comment]
@ian4hu I encourage you to ask this in the [Gitter chat](http://gitter.im/mochajs/mocha).  When asking, please provide gists (pastebin, etc) for the test above as well as whatever "#DI" is.  This is very unlikely a bug in Mocha, so I'm going to close this issue.
