### ISSUE TITLE
ES6 import not working when using babel in Mocha.

### ISSUE THREAD

**Issue by huyaxiong** [mochajs/mocha#2655]
![snip20170103_3](https://cloud.githubusercontent.com/assets/6245250/21602682/ad68f2de-d1d1-11e6-8919-d4e2dba0bd83.png)

![snip20170103_4](https://cloud.githubusercontent.com/assets/6245250/21602690/bfcb8bee-d1d1-11e6-990b-c087dfe4b6ec.png)

I based on official document using mocha --require babel-register to run my test code,but not working.
"mocha": "^2.5.3",
"babel-register": "^6.18.0",

**Comment by Rukeith** [comment]
I use this configuration
`mocha --compilers js:babel-core/register file-you-want-test`

```
setting in package.json
"babel": {
    "presets": [
      "stage-3",
      "latest"
    ]
  }
```

```
mocha: 3.2.0
"babel-core": "^6.18.0",
"babel-preset-latest": "^6.16.0",
"babel-preset-stage-3": "^6.17.0",
```

**Comment by huyaxiong** [comment]
@Rukeith Thanks!

**Comment by wangbourne** [comment]
@Rukeith you are a star!

**Comment by beatak** [comment]
It seems they deprecated `babel-preset-latest` and `babel-preset-stage-3`? The command is still the same `mocha --compilers js:babel-core/register file-you-want-test` but the `package.json` is slightly different as follows:

```
  "devDependencies": {
    "mocha": "3.5.3",
    "babel-core": "6.26.0",
    "babel-preset-env": "1.6.0"
  },
  "babel": {
    "presets": ["env"]
  }
```

**Comment by yogeshgadge** [comment]
I have the same exact dependencies in package.json but I can't get away with the following which is an import in my source code. My test imports this source code to test a class - simple as that.

```
import isEmpty from 'lodash-es/isEmpty';
^^^^^^

SyntaxError: Unexpected token import
```

My dev dependencies

```
    "babel-cli": "6.26.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "6.26.0",
    "mocha": "3.5.3",
    "mock-local-storage": "1.0.5",
```
and also in package.json

```
  "babel": {
    "presets": ["env"]
  }

```
also my .babelrc

```
{
  "presets": ["env"]
}

```

However as I run `mocha --compilers js:babel-core/register file-you-want-test` I don;t have problems with the imports in the test.spec.js file itself i.e. chai etc seems imported properly however my source import fails 

```
import {MyMenuSvc} from '../../src/my-menu-svc';
```

Here `src/my-menu-svc` has the first statement

```
import isEmpty from 'lodash-es/isEmpty';
```

..and the error

**Comment by vladblindu** [comment]
Same here... any results?

**Comment by yogeshgadge** [comment]
I gave up. My workaround is to compile it and then test. Defeats the purpose but living with it with build on watch.

**Comment by yogeshgadge** [comment]
It's not mocha's problem in my mind.

**Comment by vladblindu** [comment]
My situation was simple. My package was a direct github install. ( with: git+https://github/….etc ) In the end I realised the problem. Webstorm offered itself to generate the .gitignore by its own. I was stupid enough to let that happen and realised after 2 hours of banging my head against the wall it added the dist/ folder to the ignored files. So node would fallback and import the n-transpliled files, which caused the problem.
For public tested packages, that’s really weird.

**Comment by jacobsun** [comment]
Both of the --require and --compilers will work, unless there is no `module: false` in your .babelrc

**Comment by jacobsun** [comment]
If you are building a project which is bundled by webpack, you may need this:

```javascript
{
  "env": {
    "production": {
      "presets": [
        [
          "env",{
            "modules": false,
            "targets": ["ie >= 9"]
          }
        ]
      ],
      "comments": false
    },
    "test": {
      "presets": [
        [
          "env",{"targets": {"node": "current"}}
        ]
      ]
    }
  }
}
```

Use `env` to separate configs for `webpack` and `node(mocha)`
My yarn scripts:

```javascript
    "build": "rimraf dist && cross-env NODE_ENV=production webpack --progress",
    "test": "cross-env NODE_ENV=test mocha --reporter=nyan --require babel-register test/**/*.js"
```

**Comment by andymcwraith** [comment]
@jacobsun Thanks, fixed my problem

**Comment by mykeels** [comment]
For presets `es2015` and `stage-3`, I had to place

```
{
    "presets": ["es2015", "stage-3"],
    "plugins": []
}
```

in my `.babelrc` file, then use

```
mocha -R spec --compilers js:babel-register
```

to get it working

**Comment by monsonjeremy** [comment]
I'm getting an error now like so:
```
  this.files = [];
             ^

TypeError: Cannot set property 'files' of undefined
    at Mocha (/Users/jmonson/Desktop/adventofcode/node_modules/mocha/lib/mocha.js:79:14)
```

**Comment by erguotou520** [comment]
@jacobsun 's answer solved.

**Comment by dd-david** [comment]
If you use ES6, you need to translate it to ES5 before testing with mocha.
To use mocha with ES6

1. intsall babel-core, babel-register, and mocha
```
  $ npm install --save-dev mocha babel-core babel-register
```

2. add test script in package.json.
```
   # package.json
   "scripts": {
   +  "test": "mocha --require babel-core/register ./test/**/*.js"
   }
   
   $ npm test
```

And see below link about details.  
https://github.com/mochajs/mocha/wiki/compilers-deprecation

**Comment by iamgkstack** [comment]
I have used the above script but still, I am getting an error, the error is below:-
```Error: Cannot find module './--require.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.getConstants (D:/gitlab-to-azure/blik-app/server/config/environment/index.js:12:16)
    at Object.<anonymous> (D:/gitlab-to-azure/blik-app/server/app.js:10:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at loader (D:\gitlab-to-azure\blik-app\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\gitlab-to-azure\blik-app\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:/gitlab-to-azure/blik-app/server/api/group/group.test.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at loader (D:\gitlab-to-azure\blik-app\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\gitlab-to-azure\blik-app\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at D:\gitlab-to-azure\blik-app\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\gitlab-to-azure\blik-app\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (D:\gitlab-to-azure\blik-app\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (D:\gitlab-to-azure\blik-app\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (D:\gitlab-to-azure\blik-app\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (D:\gitlab-to-azure\blik-app\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (D:\gitlab-to-azure\blik-app\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (D:\gitlab-to-azure\blik-app\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (D:\gitlab-to-azure\blik-app\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (D:\gitlab-to-azure\blik-app\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (D:\gitlab-to-azure\blik-app\node_modules\mocha\bin\mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)```

**Comment by Devesh14** [comment]
@dd-david  Thanks for the solution

**Comment by rsahni** [comment]
With the latest Mocha and Babel this problem is still there. I tried all the tricks it didn't help so reverted back to mocha version 7 works fine with it. 
Anybody else faced the same issue?

**Comment by dclark27** [comment]
I was able to get this working by adding a .mocharc.yaml file at the source of my project with the following:

```
require: '@babel/register'
```

source: https://github.com/mochajs/mocha-examples/tree/master/packages/babel

**Comment by christopherchubb** [comment]
> With the latest Mocha and Babel this problem is still there. I tried all the tricks it didn't help so reverted back to mocha version 7 works fine with it.
> Anybody else faced the same issue?

I rolled back to Mocha 7 and all is right again.

**Comment by lunayui** [comment]
I work with mocha 8 and have the issue

**Comment by rohan-deshpande** [comment]
@dclark27's solution worked for me with `mocha@8.2.0`, you need to put the file alongside your `package.json` rather than how it was with the old `mocha.opts` file which sat in the same directory as your tests

**Comment by Arrow66** [comment]
`module.exports = {presets: ["@babel/preset-react"],plugins:[ ["module-resolver", {
    "root": ["./src"],
    "alias": {
        "test-utils":"./src/utils/testutils/index.js"
    }
  }],"@babel/plugin-transform-modules-commonjs"]}`

incase any one still having this issue just add `@babel/plugin-transform-modules-commonjs`
