### ISSUE TITLE
browser - exceptions thrown in before/beforeEach are ignored

### ISSUE THREAD

**Issue by spmason** [mochajs/mocha#270]
I'm finding that exceptions thrown in my before/beforeEach blocks aren't being handled, it's simple enough to reproduce:

        mocha.setup('bdd');
        describe('testing the tests', function(){
            beforeEach(function(){ // also before(), 
                throw new Error('this should fail');
            });

            it('Works', function(){
            });
        });
        mocha.run();

This is on the most recent version, 0.12.1 on Chrome 17 and FireFox 10

**Comment by danielstjules** [comment]
Not sure when the issue was fixed, but it's no longer a problem in 2.2.0 :)

``` javascript
// When thrown in beforeEach

$ cat beforeEachError.js
describe('issue-270', function() {
  before(function() {
    console.log('before hook');
  });

  beforeEach(function() {
    console.log('beforeEach hook');
    throw new Error('beforeEach hook error');
  });

  afterEach(function() {
    console.log('afterEach hook');
  });

  after(function() {
    console.log('after hook');
  });

  it('test', function() {});
});

// Output

$ mocha beforeEachError.js

  before hook
beforeEach hook

  ․afterEach hook
after hook


  0 passing (6ms)
  1 failing

  1) issue-270 "before each" hook:
     Error: beforeEach hook error
      at Context.<anonymous> (beforeEachError.js:8:11)

// An example when thrown in before hook

$ cat beforeError.js
describe('issue-270', function() {
  before(function() {
    console.log('before hook');
    throw new Error('before hook error');
  });

  beforeEach(function() {
    console.log('beforeEach hook');
  });

  afterEach(function() {
    console.log('afterEach hook');
    invoked++;
  });

  after(function() {
    console.log('after hook');
  });

  it('test', function() {});
});

// Output

$ mocha beforeError.js

  before hook

  ․after hook


  0 passing (6ms)
  1 failing

  1) issue-270 "before all" hook:
     Error: before hook error
      at Context.<anonymous> (beforeError.js:4:11)
```

**Comment by bitmage** [comment]
Wonderful, thanks!  I just didn't want it to slip under the radar.

**Comment by danielstjules** [comment]
No problem! Happy it all worked out.

**Comment by bitwiseman** [comment]
Fantastic.
