### ISSUE TITLE
TypeError: Cannot read property 'currentRetry' of undefined

### ISSUE THREAD

**Issue by steadysupply** [mochajs/mocha#2768]
Running `node_modules/mocha/bin/mocha -w "test/**/*.js"` I saw.

```
/app/node_modules/mocha/lib/runner.js:553
          var retry = test.currentRetry();
                          ^

TypeError: Cannot read property 'currentRetry' of undefined
    at /app/node_modules/mocha/lib/runner.js:553:27
    at done (/app/node_modules/mocha/lib/runnable.js:295:5)
    at Test.<anonymous> (/app/node_modules/mocha/lib/runnable.js:370:16)
    at Test.assert (/app/node_modules/supertest/lib/test.js:179:6)
    at Server.assert (/app/node_modules/supertest/lib/test.js:131:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitCloseNT (net.js:1562:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Wasn't reproduced immediately when I restarted the process.

**Comment by ScottFreeCode** [comment]
This sounds like #2315, which *should* be fixed (although it was hard to test to be sure) in the current version of Mocha. However, without seeing an example of test code that would trigger this, it's nearly impossible to tell if it's actually the same issue -- or, for that matter, to dig into it in any meaningful way (debugging, root cause analysis, design of fix...).

Make sure you're running the latest version of Mocha (also beware global installs, which can have different version than the local install); if you are and the issue still occurs (even if only sporadically), please try to get us a [minimal, complete and verifiable example](http://stackoverflow.com/help/mcve).
