### ISSUE TITLE
Randomly unable to find modules (possible mocha caching issue?)

### ISSUE THREAD

**Issue by alxlu** [mochajs/mocha#2789]
I've been using mocha on a project that's about a year old. I haven't had to touch the config for a while and it seemed to be working fine.

However, when I ran the tests today, I got the following error
```
> cross-env NODE_ENV=localtest mocha --compilers js:babel-core/register $(find . -name '*.test.js' ! -ipath '*node_modules*')

module.js:472
    throw err;
    ^

Error: Cannot find module '../../src/utils/testutils'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```
 This issue happens on 3.2.0 and 3.3.0.

What's really confusing me is that the tests were running consistently minutes before that run and still fail after reverting all code changes back to how it was before. It just randomly started failing.

Also the module location there is off by an additional `../`. The offending file is located at
`projectdir/src/utils/tests/cmds.tests.js`

So far the only thing I can think of that could have triggered this issue is running the tests through Webstorm UI as opposed to the CLI (which I had normally done in the past).

Essentially what had happened was I ran the tests on the CLI which ran fine. I then ran the tests through Webstorm's UI, and they also ran fine. I then made an innocuous change (essentially exported an additional function from a file which isn't even called, let alone something that should impact the tests) which ran just fine before it randomly caused the module error above in Webstorm's UI, which then led to the CLI getting the error as well. After completely reverting the code change, clearing my node_modules, and rebooting, the error persists.

The issue seems to be related to module resolution. If I manually change all the imports to point directly to the file (as opposed to using a resolver plugin https://github.com/tleunen/babel-plugin-module-resolver), it seems to work again.

What's even weirder is that if I run a the command with a different NODE_ENV (e.g. the one I use for testing on CI) the I don't get the "Cannot find module" error. Unfortunately, this isn't really a fix since I use the NODE_ENV to determine which database credentials are passed into the server (and really, this is the only difference these two environment variables create).

The only difference NODE_ENV makes in these two instances is:
```js
const determineConnection = (): string => {
  switch (process.env.NODE_ENV) {
    case 'test':
      return 'postgres://jenkins:jenkins@localhost/testdb';
    case 'localtest':
      return 'postgres://vagrant:vagrant@localhost/testdb';
    case 'development':
      return 'postgres://vagrant:vagrant@localhost/devdb';
    case 'production':
      return process.env.DATABASE_URL;
    default:
      return process.env.DATABASE_URL;
  }
};
```

The project still builds and runs properly locally and on the server. Also, after building the project with babel and checking the output, it looks like the modules are resolved properly, so I'm not sure why mocha is having issues finding them.

Here is my `.babelrc`

```
{
  "presets": ["es2015", "stage-0"],
  "plugins": [
    "transform-runtime",
    "transform-flow-strip-types",
    ["module-alias", [
      { "src": "./src", "expose": "src" },
      { "src": "./src/db", "expose": "db" },
      { "src": "./src/utils", "expose": "utils" },
      { "src": "./src/routes", "expose": "routes" },
    ]]
  ]
}
```

and this is the scripts section of my `package.json` (I've removed irrelevant sections... `test` is what the CI server runs and `test:local` is what I'm running locally. Only the latter gets the error.)
```
    "test": "cross-env NODE_ENV=test mocha --compilers js:babel-core/register $(find . -name '*.test.js' ! -ipath '*node_modules*')",
    "test:local": "cross-env NODE_ENV=localtest mocha --compilers js:babel-core/register $(find . -name '*.test.js' ! -ipath '*node_modules*')",
```

I've tried various combinations of the following with zero success:

- Upgrading mocha to the latest version
- Upgrading the module-alias module with the latest module-resolver module
- Upgrading babel-core/register to babel-register

Does mocha keep some type of global cache that somehow persists after runs/reboots/etc.? And if so is there a way to clear it? Or is there something I'm overlooking? This doesn't seem to impact building the files with babel directly or running the project itself. It only seems to affect mocha tests...

**UPDATE:**
It looks like I can get the tests to run again by editing any source file (e.g. leaving a comment) then running it off the CLI.
They will then run properly in the CLI and in Webstorm. However, any innocuous change (even updating the file with a comment) will proceed to break the test in Webstorm which then breaks the test in the CLI until I make a change in the file again... Also, it seems to always report a different missing module (the most recent one is in the error above, but it has reported non-test files as well). It seems to be based on which file I run first in Webstorm's UI.

**Comment by alxlu** [comment]
Here's a screen recording of the issue:
https://drive.google.com/file/d/0BzHXj23U2E4dQ1Y5X0FqRjVpWkU/view

**Comment by alxlu** [comment]
Looks like updating the mocha working directory seems to fix this
