### ISSUE TITLE
relative --require breaks on folders, shouldn't be necessary

### ISSUE THREAD

**Issue by gfxmonk** [mochajs/mocha#285]
I happened to have the "should.js" repo checked out in a folder called "should.js" of my cwd, and this broke the tests because it tried to load that instead of the "should" that was actually correctly placed in $NODE_PATH.

I'd argue if your dependencies are not in $NODE_PATH or already fully-qualified you're doing it wrong, so I think this feature should be taken out. But if it is to be left in, it should:

 - ignore directories
 - support "modname/index.js" style modules

But really, it should be unnecessary.

**Comment by danielstjules** [comment]
Closing because this doesn't seem to be an issue anymore :)

``` javascript
$ tree -L 2 .
.
├── example.js
└── should
    ├── CONTRIBUTING.md
    ├── History.md
    ├── LICENSE
    ├── Readme.md
    ├── bower.json
    ├── gulpfile.js
    ├── index.js
    ├── lib
    ├── node_modules
    ├── package.json
    ├── should.js
    └── should.min.js

3 directories, 11 files
danielstjules:~/test
$ cat example.js
var should = require('should');


danielstjules:~/test
$ mocha example.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'should'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/danielstjules/test/example.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
danielstjules:~/test
$ cd should/
danielstjules:~/test/should
$ mocha ../example.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'should'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/danielstjules/test/example.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/Users/danielstjules/.nvm/v0.10.20/lib/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```
