### ISSUE TITLE
Empty error in before/after hook

### ISSUE THREAD

**Issue by sdiachenko** [mochajs/mocha#2892]
Trying to get mocha error stack.  
```
2) Menus: when a Print Group is added to a Menu Item: "after all" hook:
     ReferenceError: updateMenuItem is not defined
      at module.exports (node_modules/fuzzball-core/lib/helpers/menu_items.js:35:22)
      at Context.<anonymous> (medium_tests/menus/print_group_publishing_test.js:100:7)
```

when suite fails in before or after hooks. 
getting empty error obj instead.

```
failed test {
  "title": "\"after all\" hook",
  "body": "function (done) {\n      var errors;\n      Items()\n      menuItems()\n        .updateMenuItem({\n          menuID: menuDefault,\n          menuItemID: menuItemDefault,\n          printGroupID: null\n        })\n        .exec()\n        .catch(function (err) {\n          errors = err;\n        })\n        .then(function () {\n          done(errors);\n        });\n    }",
  "async": 1,
  "sync": false,
  "timedOut": false,
  "pending": false,
  "type": "hook",
  "parent": "#<Suite>",
  "ctx": "#<Context>",
  "timer": {
    "0": null
  },
  "duration": 1,
  "state": "failed",
  "err": {}
}

```

 var mochaOptions = { ui: 'bdd', timeout: 15000, reporter: JsonReporter };
```function JSONReporter (runner) {
  mocha.reporters.Base.call(this, runner);
runner.on('fail', function (test) {
  console.log(test);
}
}
```

**Comment by boneskull** [comment]
I don't really understand what's going on here. please provide an [MCVE](https://stackoverflow.com/help/mcve)
