### ISSUE TITLE
Unable to use --exit

### ISSUE THREAD

**Issue by zelein** [mochajs/mocha#3169]
### Prerequisites

* [ x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

I'm unable to use the `--exit` parameter when provided in `mocha.opts` or in the CLI.

### Steps to Reproduce

mocha.opts
```
--reporter spec
-timeout 2000
--delay
--exit
test/integration/
test/module
```

package.json npm script:
`"test": "mocha"`

`$ npm test`

Resulting output:
```
'--delay' expects a value

Usage: C:\Program Files\nodejs\node.exe _mocha [options]

Options:
   -v, --version   Print version and exit.
   -d, --debug     Run in debug mode.  [false]
   -p, --port      The port number to listen on.  [5000]
```

I've also attempted removing `--exit` from the opts file and providing directly in the CLI:
`$ npm mocha --exit`

Resulting output:
```
'--exit' expects a value

Usage: C:\Program Files\nodejs\node.exe _mocha [options]

Options:
   -v, --version   Print version and exit.
   -d, --debug     Run in debug mode.  [false]
   -p, --port      The port number to listen on.  [5000]
```

Removing this options from the CLI and the opts file causes mocha to behave as expected.

**Expected behavior:** Mocha to run

**Actual behavior:** Mocha doesn't run

**Reproduces how often:** 100%

### Versions

```
$ mocha --version
'mocha' is not recognized as an internal or external command, operable program or batch file.
```

```
$ node node_modules/.bin/mocha --version
E:\git\ts_template\node_modules\.bin\mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

However, running mocha within the context of an npm script:
```
E:\git\ts_template>npm test

> ts-template@6.3.0 test E:\git\ts_template
> mocha --version

4.0.1
```

```
E:\git\ts_template>node --version
v6.11.4
```

**Comment by boneskull** [comment]
I have no idea what's going on here.  What's the contents of `node_modules/.bin/mocha`? What package manager did you use to install it?  What shell are you using?

**Comment by zelein** [comment]
`node_modules/.bin/mocha`
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../mocha/bin/mocha" "$@"
  ret=$?
else 
  node  "$basedir/../mocha/bin/mocha" "$@"
  ret=$?
fi
exit $ret
```

`node_modules/.bin/mocha.cmd`
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\mocha\bin\mocha" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\mocha\bin\mocha" %*
)
```

I'm using `yarn 1.3.2` and this is on Windows 7 using the default terminal in VSCode - cmd. My machine does have cygwin installed.

**Comment by zelein** [comment]
Further investigation I'm confident this is an issue with my code/environment. Closing this.
