### ISSUE TITLE
Mocha broken queue with uncaught exceptions

### ISSUE THREAD

**Issue by schipiga** [mochajs/mocha#3198]
Hey guys!

I don't know, may be you already know problem, that mocha uncaught exception processing may lead to broken queue for async tests. But just in case, this is the post with repeatable example and detailed explanation, why it happens: https://glacejs.github.io/glace-core/tutorial-mocha-uncaught.html

**Comment by boneskull** [comment]
I just pasted the test case here into a file and ran it:

```
  scope
    1) test #1
    2) test #2
    3) test #3
    4) test #4
    5) test #5
I was sleeping 1000 ms
    6) test #6
I was sleeping 1000 ms


  0 passing (1s)
  6 failing

  1) scope
       test #1:
     Error: Timeout of 200ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Timeout.<anonymous> (lib/runnable.js:238:19)

  2) scope
       test #2:
     Error: Timeout of 200ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Timeout.<anonymous> (lib/runnable.js:238:19)

  3) scope
       test #3:
     Error: Timeout of 200ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Timeout.<anonymous> (lib/runnable.js:238:19)

  4) scope
       test #4:
     Error: Timeout of 200ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Timeout.<anonymous> (lib/runnable.js:238:19)

  5) scope
       test #5:
     Uncaught Error: BOOM!!!
      at Timeout.setTimeout [as _onTimeout] (foo.js:13:16)

  6) scope
       test #6:
     Error: Timeout of 200ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Timeout.<anonymous> (lib/runnable.js:238:19)
```

Not sure what version of Mocha you're working with here.

**Comment by boneskull** [comment]
(There are issues around the "allow uncaught" behavior otherwise)

**Comment by schipiga** [comment]
@boneskull , could you please provide full example of code which you use and how to run. I can't understand why you have exception 

```
Error: Timeout of 200ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves
```

My example have described result each time in any mocha version since v3.5 (when I started to work with JS) and any PC.

**Comment by schipiga** [comment]
@boneskull 

I just pasted my code to my another PC, with Window 10, just fresh installed nodejs v8.9.4 and mocha 4.1.0.  End executed it with command

```mocha uncaught.js```

And had got the result:

```
C:\nomad>mocha uncaught.js


  scope
    1) test #1
I was sleeping 1000 ms
    √ test #1 (1024ms)
    2) test #3
I was sleeping 1000 ms
I was sleeping 1000 ms
    √ test #4
    √ test #4
I was sleeping 1000 ms
I was sleeping 1000 ms
I was sleeping 1000 ms
    √ test #6 (1006ms)
    √ test #6 (1006ms)
    √ test #6 (1006ms)

  6 passing (3s)
  2 failing

  1) scope
       test #1:
     Uncaught Error: BOOM!!!
      at Timeout.setTimeout [as _onTimeout] (uncaught.js:14:16)

  2) scope
       test #3:
     Uncaught Error: BOOM!!!
      at Timeout.setTimeout [as _onTimeout] (uncaught.js:14:16)





  6 passing (3s)
  2 failing

  1) scope
       test #1:
     Uncaught Error: BOOM!!!
      at Timeout.setTimeout [as _onTimeout] (uncaught.js:14:16)

  2) scope
       test #3:
     Uncaught Error: BOOM!!!
      at Timeout.setTimeout [as _onTimeout] (uncaught.js:14:16)




  6 passing (3s)
  2 failing

  1) scope
       test #1:
     Uncaught Error: BOOM!!!
      at Timeout.setTimeout [as _onTimeout] (uncaught.js:14:16)

  2) scope
       test #3:
     Uncaught Error: BOOM!!!
      at Timeout.setTimeout [as _onTimeout] (uncaught.js:14:16)
```

Let's investigate deeply our difference. I think. you have timeout 200ms, instead of normal 2 sec, and it affects your result.

**Comment by boneskull** [comment]
Indeed, it was a 200ms timeout.

Uncaught exception handling does not extend to `Promise`s; see various other issues on the subject.  this is a dupe, of which issue exactly I'm not sure.

**Comment by schipiga** [comment]
@boneskull , ok, thank you, for my team it isn't a critical, as we use work around. Just wanted to inform that this problem is present.
