### ISSUE TITLE
Mocha error while running Ethereum Smart Contracts tests.

### ISSUE THREAD

**Issue by CPerezz** [mochajs/mocha#3279]
Hi all.
I'm opening this issue in order to try to fix some annoying problems I'm having while running ethereum smart contracts tests.

Here is my Inbox.test.js:
`{
const assert = require('assert');
const ganache = require('ganache-cli');
const Web3 = require('web3');
const web3 = new Web3(ganache.provider());
//const { interface, bytecode } = require('../compile');

let accounts;
let inbox;
beforeEach(async () => {
accounts = await web3.eth.getAccounts();

inbox = await new web3.eth.Contract(JSON.parse(interface))
.deploy({ data: bytecode, arguments:['Hi there!']})
.send({ from: accounts[0], gas:'1000000' })
});

describe('Inbox', ()=>{
it('deploys a contract', () => {

    assert.ok(inbox.options.address);

});
})
}`

And here it is my package.json file:
{ "name": "inbox", "version": "1.0.0", "description": "", "main": "index.js", "scripts": { "test": "mocha" }, "author": "", "license": "ISC", "dependencies": { "ganache-cli": "^6.1.0", "loadash": "^1.0.0", "mocha": "^4.0.1", "node-modules": "^1.0.1", "solc": "^0.4.19", "web3": "^1.0.0-beta.26" } }

When I run:
npm run test //I get the following console output:

root@XXXXXX:/home/pathtoproject/inbox# npm run test

inbox@1.0.0 test /pathtoproject/inbox
mocha

/pathtoproject/inbox/test/Inbox.test.js:6
const { interface, bytecode } = require('../compile');
^

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at /usr/lib/nodejs/mocha/lib/mocha.js:172:27
at Array.forEach (native)
at Mocha.loadFiles (/usr/lib/nodejs/mocha/lib/mocha.js:169:14)
at Mocha.run (/usr/lib/nodejs/mocha/lib/mocha.js:356:31)
at Object. (/usr/lib/nodejs/mocha/bin/_mocha:366:16)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)
at startup (node.js:136:18)
at node.js:966:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inbox@1.0.0 test: mocha
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inbox@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-03-11T11_15_11_436Z-debug.log

Then if I try to delete the line that gives problems this happens at running npm run test:

inbox@1.0.0 test /pathtoproject/inbox

mocha

/home/pathtoproject/inbox/test/Inbox.test.js:8
let accounts;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outsidestrict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at /usr/lib/nodejs/mocha/lib/mocha.js:172:27
at Array.forEach (native)
at Mocha.loadFiles (/usr/lib/nodejs/mocha/lib/mocha.js:169:14)
at Mocha.run (/usr/lib/nodejs/mocha/lib/mocha.js:356:31)
at Object. (/usr/lib/nodejs/mocha/bin/_mocha:366:16)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)
at startup (node.js:136:18)
at node.js:966:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inbox@1.0.0 test: mocha
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inbox@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/XxxxxX/.npm/_logs/2018-03-11T11_35_19_312Z-debug.log

Versioning and other stuff:
mocha --version --> 1.20.1
npm --version --> 5.6.0
node --version --> v.9.8.0

So anyone has any idea of what's happening? I've tried to reinstall node and npm, clear npm cache etc and nothing seems to work.

Thanks to all.

**Comment by outsideris** [comment]
Your code wrapped with `{ }` at line 1 and last line?  You should it.

**Comment by Bamieh** [comment]
@CPerezz can you format your message well in order for us to comprenehd your question better.
Anyways, this error means that you must write "use strict" at the top of the file to use block-scope declarations.

```
"use strict";
function runs() {
    let a = 1;
}
```

**Comment by boneskull** [comment]
wfm.

**Comment by Frothacker** [comment]
I had the same issue. We are following a Udemy course to learn solidity. 

The last line of your compile.js file references the contract names. In our case, the contract is named "Inbox" (with a capital i)
Make sure the last line of your compile statement is nameing "Inbox" correctly, with a capital "I" like so:
`module.exports = solc.compile(source, 1).contracts[':Inbox']; `

you may have mistyped like so: `.contracts[':inbox']`. This will instruct the compiler to compile the 'inbox' contract (which doesn't exist), instead of the proper "Inbox" with a capital I.

**Comment by sushanth3366** [comment]
I used small 'I' every where for inbox still I am not able to run test
<img width="888" alt="screen shot 2019-02-17 at 1 55 24 pm" src="https://user-images.githubusercontent.com/46863846/52910319-c3fe3200-32bb-11e9-9b69-e18be50d9a43.png">

**Comment by sushanth3366** [comment]
I used small 'I' every where for inbox still I am not able to run test
I am using web3@1.0.0-beta.26
I also tried web3@1.0.0-beta.37 but still got same error
<img width="815" alt="screen shot 2019-02-17 at 1 57 18 pm" src="https://user-images.githubusercontent.com/46863846/52910330-117a9f00-32bc-11e9-8b4c-482df340f0c5.png">

**Comment by plroebuck** [comment]
@sushanth3366, you misspelled `describe`...

**Comment by sushanth3366** [comment]
bro still its showing this error

**Comment by sushanth3366** [comment]
<img width="502" alt="screen shot 2019-02-17 at 4 30 01 pm" src="https://user-images.githubusercontent.com/46863846/52911997-565d0080-32d1-11e9-8929-5b48c3596073.png">
<img width="845" alt="screen shot 2019-02-17 at 4 23 58 pm" src="https://user-images.githubusercontent.com/46863846/52912002-6248c280-32d1-11e9-8d15-090025d5cee0.png">
any one please resolve this issue its a bit urjent for me.

**Comment by plroebuck** [comment]
I'll use this standard project layout.
```sh
$ PROJ="myproj"
$ mkdir ${PROJ}
$ cd ${PROJ}
$ mkdir lib test
```
Put your "Car" class in its own file...
```sh
$ cat << EOF >> "./lib/car.js"
class Car {
  park() {
    return 'stopped';
  }
  drive() {
    return 'vroom';
  }
}

module.exports = Car;

EOF
```
Now create its test specification...
```sh
$ cat << EOF >> "./test/car.spec.js"
const assert = require('assert');
const Car = require('../lib/car');

describe('Car', () => {
  it('can park', () => {
    const car = new Car();
    assert.equal(car.park(), 'stopped');
  });

  it('can drive', () => {
    const car = new Car();
    assert.equal(car.drive(), 'vroom');
  });
});

EOF
```
Create "package.json" and patch by hand...
```sh
$ npm init -y
$ npm install mocha --save-dev
$ "${EDITOR:=pico}" package.json
```
It should look like this:
```json
{
  "name": "myproj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "lib": "lib",
    "test": "test"
  },
  "scripts": {
    "test": "mocha"
  },
  "keywords": [],
  "devDependencies": {
    "mocha": "^5.2.0"
  },
  "engines": {
    "node": ">=6"
  },
  "author": "P. Roebuck <plroebuck@users.noreply.github.com>",
  "license": "ISC"
}
```
Finally, run the test.
```sh
$ npm test

> myproj@1.0.0 test /tmp/myproj
> mocha

  Car
    ✓ can park
    ✓ can drive

  2 passing (9ms)

```

**Comment by plroebuck** [comment]
Now (re)add the Etherium related modules.
**Ensure you have native build tools (e.g., Xcode on macOS) installed first***

```sh
$ npm install ganache-cli --save
$ npm install web3 --save    # Install requires build tools
```
Create another test specification to verify your Web3 setup.
```
$ cat << EOF >> "./test/web3.spec.js"
const assert = require('assert');

describe('Web3', () => {
  let ganache;
  let Web3;

  before(() => {
    ganache = require('ganache-cli');
    Web3 = require('web3');
  });

  it('should create an instance', () => {
    const web3 = new Web3(ganache.provider());
    console.log(web3);
    assert.ok(web3);
  });
});

EOF
```
Test again.
```sh
$ npm test
```

**Comment by sushanth3366** [comment]
Man thank u so much😀😀!!!

**Comment by muntahanoor** [comment]
Hi all.
I opened this issue in order to fix problems while running ethereum smart contracts tests.

Here is my Inbox.test.js:

require('assert');
const Web3 = require('web3');
const ganache = require('ganache-cli');
const web3 = new Web3(ganache.provider());
const { interface, bytecode } = require('../compile');
let accounts;
let inbox;
 beforeEach(async () => {
     //get a list of all accounts
    accounts = await web3.eth.getAccounts();
    //use one of those accounts to deploy the contract
    inbox = await new web3.eth.Contract(JSON.parse(interface))
        .deploy({data:bytecode, arguments:['Hi there']})
        .send({from:accounts[0],gas: '1000000'});
 });
describe('Inbox', function(){
it('deploys a contract', function(){
    console.log(inbox);
});
});

And here it is my package.json file:
{
  "name": "inbox",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ganache-cli": "^6.4.3",
    "mocha": "^6.1.4",
    "solc": "^0.4.17",
    "web3": "^1.0.0-beta.26"
  },
  "devDependencies": {
    "@types/node": "^12.0.0"
  },
  "directories": {
    "test": "test"
  },
  "description": ""
}

When I run:
npm run test //I get the following console output:

inbox@1.0.0 test inbox
> mocha

inbox\node_modules\mocha\node_modules\yargs\yargs.js:1163
      else throw err
           ^

TypeError: core.addProviders is not a function
    at Object.<anonymous> (C:\Users\Arooj\inbox\node_modules\web3\src\index.js:76:6)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Arooj\inbox\test\Inbox.test.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Users\Arooj\inbox\node_modules\mocha\lib\mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Arooj\inbox\node_modules\mocha\lib\mocha.js:327:14)
    at Mocha.run (C:\Users\Arooj\inbox\node_modules\mocha\lib\mocha.js:804:10)
    at Object.exports.singleRun (C:\Users\Arooj\inbox\node_modules\mocha\lib\cli\run-helpers.js:207:16)
    at exports.runMocha (C:\Users\Arooj\inbox\node_modules\mocha\lib\cli\run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (C:\Users\Arooj\inbox\node_modules\mocha\lib\cli\run.js:296:3)
    at Object.runCommand (C:\Users\Arooj\inbox\node_modules\mocha\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\Users\Arooj\inbox\node_modules\mocha\node_modules\yargs\yargs.js:1104:24)
    at Object.parse (C:\Users\Arooj\inbox\node_modules\mocha\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\Users\Arooj\inbox\node_modules\mocha\lib\cli\cli.js:63:6)
    at Object.<anonymous> (C:\Users\Arooj\inbox\node_modules\mocha\bin\_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inbox@1.0.0 test: `mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inbox@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arooj\AppData\Roaming\npm-cache\_logs\2019-05-09T07_43_28_384Z-debug.log

So anyone has any idea to solve this problem??

Thanks to all.

**Comment by Hauleraway** [comment]
having a similar issue. When I run test I get an error. It will not retrieve account from ganache

const assert = require('assert');
const ganache = require('ganache-cli');
const Web3 = require('web3');
const web3 = new Web3(ganache.provider());

let accounts;

beforeEach(async () => {
  // Get list of all accounts
  accounts = await web3.eth.getAccounts()

      //Use one of those accounts to deploy
      //the contract
});

  descirbe('Inbox', () => {
    it('deploys a contract', () => {
      console.log(accounts);
    });
});

![Annotation 2020-01-17 114307](https://user-images.githubusercontent.com/25989118/72637462-a2b82280-391e-11ea-8975-cd64707a1725.png)

**Comment by jarvissingh** [comment]
> ```shell
> npm install web3 --save 
> ```

having issue can someone help

**Comment by TheCodeInjection** [comment]
yeh me 2

**Comment by MMukkarram** [comment]
i have a similar problem. 
![image](https://user-images.githubusercontent.com/40773916/219509495-602244b2-09df-4937-b4fc-e631927df3bc.png)

**Comment by akbar-rundtc** [comment]
I solved this error using Chatgpt
use new version of node using nvm
