### ISSUE TITLE
Unexpected token while using mocha + @babel/register

### ISSUE THREAD

**Issue by ganapativs** [mochajs/mocha#3459]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Unable to run test files containing ECMAScript 6 modules using mocha + @babel/register.
```
❯ yarn test
yarn run v1.7.0
warning package.json: No license field
$ mocha --require @babel/register
/Users/<username>/mocha-reproduce/test/reproduce.js:1
(function (exports, require, module, __filename, __dirname) { import { expect } from "chai";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (/Users/<username>/mocha-reproduce/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/<username>/mocha-reproduce/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/<username>/mocha-reproduce/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/<username>/mocha-reproduce/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/<username>/mocha-reproduce/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/<username>/mocha-reproduce/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to Reproduce
https://github.com/ganapativs/mocha-babel-register-bug-reproduce

**Expected behavior:** Should run test files containing ECMAScript 6 modules using mocha + @babel/register.

**Actual behavior:** Unable to run test files containing ECMAScript 6 modules using mocha + @babel/register.

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: `command not found` and  `5.2.0`
- The output of `node --version`: `v10.6.0`
- The version and architecture of your operating system: `OSX 10.14 Beta`
- Your shell (bash, zsh, PowerShell, cmd, etc.): `zsh`
- Your browser and version (if running browser tests): nope
- Any other third party Mocha related modules (with versions): nope
- The code transpiler being used: babel

### Additional info
I'm not really sure if its babel issue or mocha issue!

**Comment by ganapativs** [comment]
Got resolved here - https://github.com/babel/babel/issues/8477

Thanks!
