### ISSUE TITLE
bcrypt.compare not executing when testing with mocha and chai-http

### ISSUE THREAD

**Issue by sysstas** [mochajs/mocha#3479]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

bcrypt.compare not executing when testing with mocha and chai-http

### Steps to Reproduce

**Expected behavior:** run test and complete test

**Actual behavior:** test fails because of error

**Reproduces how often:** everytime

### Versions

- mocha version 5.2.0 - global and local
- node v8.11.4
- windows 10 x64
- cmd

"devDependencies": {
    "@types/chai-as-promised": "^7.1.0",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "chai-http": "^4.2.0",
    "eslint": "^5.5.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "express-unit": "^2.1.1",
    "mocha": "^5.2.0",
    "mock-express-request": "^0.2.2",
    "mock-express-response": "^0.2.2",
    "nyc": "^13.0.1",
    "proxyquire": "^2.1.0",
    "sinon": "^6.2.0",
    "supertest": "^3.3.0",
    "ws": "3.3.2"
  }

### Additional Information
I posted question on stackoverflow. You can find code there.
https://stackoverflow.com/questions/52385375/bcrypt-compare-not-executing-in-chai-mocha-tests-but-executing-in-code

ERROR { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET', response: undefined }
undefined
ERROR { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET', response: undefined }

**Comment by sysstas** [comment]
Wrong behaviour wasn't connected to chai/mocha/bcript. It was caused by following statement

    } else {
        res.status(401)
    }
correct code should be

    } else {
        res.status(401).send(something)
    }
or

    } else {
        res.sendStatus(401)
    }
I think Express waiting for .send() after .status() and keep connection without response
