### ISSUE TITLE
Cannot understand if supported and how to use with babel 7

### ISSUE THREAD

**Issue by iongion** [mochajs/mocha#3541]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Very confusing if it is possible to use mocha with babel 7

### Steps to Reproduce

```bash
$ BABEL_DISABLE_CACHE=1 mocha --require @babel/register --require @babel/core --require @babel/polyfill --require setup-testing.js --check-leaks --timeout 5000 --recursive \"./src/**/*.spec.js\"
```

Where `setup-testing.js` is

```
/* eslint-disable */
(function() {
'use strict';
require('jsdom');
require('jsdom-global')();
})();
```

**Expected behavior:**

Tests should run and I should see `console.*` messages

**Actual behavior:**

**Sometimes** tests run and I can see output, sometimes they don't, and no output visible

**Reproduces how often:** [What percentage of the time does it reproduce?]

10 % of the time I can see `console.debug` messages

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.20
- The output of `node --version`: v8.11.3
- The version and architecture of your operating system: Windows 10 - using msys2
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash 4.4.23
- The code transpiler being used: babel 7

### Additional Information

There are a lot of tutorial online, but they don't apply to babel 7, it is very unclear what the support status is for mocha 5.20 and babel 7

**Comment by iongion** [comment]
Relevant dependencies:

```
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-gettext-extractor": "^3.0.0",
    "babel-gettext-plugin": "^2.2.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-inline-import": "^3.0.0"
```

**Comment by plroebuck** [comment]
Please add the OS information.

**Comment by plroebuck** [comment]
Honestly, not the "babel" guy here. @Bamieh would be better suited to help.

One thing I might suggest would be to change `--require setup-testing.js` to `--file setup-testing.js`, but that's unlikely your problem.

You didn't really give us enough to reproduce your problem though. Need [MCVE](https://stackoverflow.com/help/mcve).

**Comment by iongion** [comment]
Thank you so much, addressed the OS mention.

The problem I have might be very specific to my project, it simply dies silently **sometimes** and I cannot pin-point why, I have added a mcve, hopefully it will help others too with babel 7.
Added [mcve.zip](https://github.com/mochajs/mocha/files/2534563/mcve.zip)
But this one seems to just work every time. @plroebuck also changed to use `--file`
What can I do to get more info before mocha exists ?

**Comment by iongion** [comment]
My test script actually ends like this:

```
cross-env NODE_ENV=production STAGE=testing BABEL_DISABLE_CACHE=1 mocha --require @babel/register --require @babel/core --require @babel/polyfill --require tools/setup-testing.js --check-leaks --timeout 5000 --recursive "./src/**/*.spec.js"

Environment has been patched yes
npm ERR! Test failed.  See above for more details.
```

But there is nothing else to see.

**Comment by plroebuck** [comment]
> Thank you so much, addressed the OS mention.

OS info is still rather lacking - windows version ???.

> The problem I have might be very specific to my project, it simply dies silently **sometimes** and I cannot pin-point why, I have added a mcve, hopefully it will help others too with babel 7.
> Added [mcve.zip](https://github.com/mochajs/mocha/files/2534563/mcve.zip)
> But this one seems to just work every time.

> @plroebuck also changed to use `--file`

Not below you didn't...

> My test script actually ends like this:
> 
> ```
> cross-env NODE_ENV=production STAGE=testing BABEL_DISABLE_CACHE=1 mocha --require @babel/register --require @babel/core --require @babel/polyfill --require tools/setup-testing.js --check-leaks --timeout 5000 --recursive "./src/**/*.spec.js"
> 
> Environment has been patched yes
> npm ERR! Test failed.  See above for more details.
> ```
> 
> But there is nothing else to see.

Could it be related to cross-env's [quoting](https://github.com/kentcdodds/cross-env#cross-env-vs-cross-env-shell)?

> What can I do to get more info before mocha exists ?

As far as Mocha itself goes, I'd add `DEBUG="*"` environment variable. But it's still unclear whether you're showing me the actual command, or what you told `npm test` to run.

**Comment by iongion** [comment]
Running with this command:

```
DEBUG="*" NODE_ENV=production STAGE=testing BABEL_DISABLE_CACHE=1 ./node_modules/.bin/mocha --require @babel/register --require @babel
/core --require @babel/polyfill --file tools/setup-testing.js --check-leaks --timeout 50000 --recursive "./src/**/*.spec.js" > output.txt
t 2>&1
```

It generates 16 mb output, that starts with:

```
2018-10-31T14:14:24.191Z mocha:suite bail undefined
2018-10-31T14:14:24.192Z mocha:suite enableTimeouts true
2018-10-31T14:14:24.196Z mocha:suite timeout 50000
2018-10-31T14:14:24.196Z mocha:suite bail undefined
```

And ends in:

```
2018-10-31T14:14:28.055Z babel program.body[4] VariableDeclaration: exit
2018-10-31T14:14:28.069Z babel:config:config-chain Ignored 'W:\\Workspace\\studio\\node_modules\\fabric\\dist\\fabric.js' because it matched one of [ /^W:\\Workspace\\studio(?:\.*)?\\node_modules\\/i ] from 'W:\\Workspace\\studio'
```

And then no more output

**Comment by iongion** [comment]
Finally, managed to create a mcve with ability to reproduce the issue.

[mcve-with-issue.zip](https://github.com/mochajs/mocha/files/2534821/mcve-with-issue.zip)

Now, it is because of using  [fabric](https://github.com/fabricjs/fabric.js) which in turn uses [canvas](https://github.com/Automattic/node-canvas)

Now, when you run the tests, you will experience a silent fail:

```
NODE_ENV=production STAGE=testing BABEL_DISABLE_CACHE=1 ./node_modules/.bin/mocha --require @babel/register --require @babel/core --require @babel/polyfill --file setup-testing.js --check-leaks --timeout 5000 --recursive "./src/**/*.spec.js"

Environment has been patched yes
npm ERR! Test failed.  See above for more details.
```

**Comment by plroebuck** [comment]
**OS:** macOS 10.13.6 (17G65)
**Node:** v10.3.0
**Mocha:** 5.2.0 (master trunk)

Had to add `cross-env` to `devDependencies` to run (used latest):

```console
$ npm test

> studio@1.1.32 test /private/tmp/babel7
> cross-env NODE_ENV=production STAGE=testing BABEL_DISABLE_CACHE=1 DEBUG="*" mocha --require @babel/register --require @babel/core --require @babel/polyfill --file setup-testing.js --check-leaks --timeout 5000 --recursive "./src/**/*.spec.js"

  mocha:suite bail undefined +0ms
  mocha:suite enableTimeouts true +3ms
  mocha:suite timeout 5000 +7ms
  mocha:suite bail undefined +0ms
...[SNIP babel output]
  mocha:suite timeout 5000 +15s
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 5000 +0ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +1ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:runnable timeout 5000 +0ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable slow 75 +0ms
  mocha:suite timeout 5000 +0ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:runnable timeout 5000 +1ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable slow 75 +0ms
  mocha:suite timeout 5000 +1ms
  mocha:suite retries -1 +0ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:runnable timeout 5000 +0ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable slow 75 +0ms
  mocha:runner grep /.*/ +0ms
  mocha:runner globals ["DTRACE_NET_SERVER_CONNECTION","DTRACE_NET_STREAM_END","DTRACE_HTTP_SERVER_REQUEST","DTRACE_HTTP_SERVER_RESPONSE","DTRACE_HTTP_CLIENT_REQUEST","DTRACE_HTTP_CLIENT_RESPONSE","global","process","Buffer","clearImmediate","clearInterval","clearTimeout","setImmediate","setInterval","setTimeout","core","__core-js_shared__","regeneratorRuntime","_babelPolyfill","before","after","beforeEach","afterEach","run","context","describe","xcontext","xdescribe","specify","it","xspecify","xit","PROJECT_ROOT","DOMException","NamedNodeMap","Attr","Node","Element","DocumentFragment","HTMLDocument","Document","CharacterData","Comment","DocumentType","DOMImplementation","ProcessingInstruction","Image","Text","Event","CustomEvent","MessageEvent","ErrorEvent","HashChangeEvent","PopStateEvent","UIEvent","MouseEvent","KeyboardEvent","TouchEvent","ProgressEvent","EventTarget","Location","History","HTMLElement","HTMLAnchorElement","HTMLAppletElement","HTMLAreaElement","HTMLAudioElement","HTMLBaseElement","HTMLBodyElement","HTMLBRElement","HTMLButtonElement","HTMLCanvasElement","HTMLDataElement","HTMLDataListElement","HTMLDialogElement","HTMLDirectoryElement","HTMLDivElement","HTMLDListElement","HTMLEmbedElement","HTMLFieldSetElement","HTMLFontElement","HTMLFormElement","HTMLFrameElement","HTMLFrameSetElement","HTMLHeadingElement","HTMLHeadElement","HTMLHRElement","HTMLHtmlElement","HTMLIFrameElement","HTMLImageElement","HTMLInputElement","HTMLLabelElement","HTMLLegendElement","HTMLLIElement","HTMLLinkElement","HTMLMapElement","HTMLMediaElement","HTMLMenuElement","HTMLMetaElement","HTMLMeterElement","HTMLModElement","HTMLObjectElement","HTMLOListElement","HTMLOptGroupElement","HTMLOptionElement","HTMLOutputElement","HTMLParagraphElement","HTMLParamElement","HTMLPreElement","HTMLProgressElement","HTMLQuoteElement","HTMLScriptElement","HTMLSelectElement","HTMLSourceElement","HTMLSpanElement","HTMLStyleElement","HTMLTableCaptionElement","HTMLTableCellElement","HTMLTableColElement","HTMLTableDataCellElement","HTMLTableElement","HTMLTableHeaderCellElement","HTMLTimeElement","HTMLTitleElement","HTMLTableRowElement","HTMLTableSectionElement","HTMLTemplateElement","HTMLTextAreaElement","HTMLTrackElement","HTMLUListElement","HTMLUnknownElement","HTMLVideoElement","StyleSheet","MediaList","CSSStyleSheet","CSSRule","CSSStyleRule","CSSMediaRule","CSSImportRule","CSSStyleDeclaration","StyleSheetList","XPathException","XPathExpression","XPathResult","XPathEvaluator","HTMLCollection","NodeFilter","NodeIterator","NodeList","Blob","File","FileList","FormData","XMLHttpRequest","XMLHttpRequestEventTarget","XMLHttpRequestUpload","DOMTokenList","addEventListener","alert","atob","blur","btoa","close","confirm","createPopup","dispatchEvent","document","focus","frames","getComputedStyle","history","innerHeight","innerWidth","length","location","moveBy","moveTo","name","navigator","open","outerHeight","outerWidth","pageXOffset","pageYOffset","parent","postMessage","print","prompt","removeEventListener","resizeBy","resizeTo","screen","screenLeft","screenTop","screenX","screenY","scroll","scrollBy","scrollLeft","scrollTo","scrollTop","scrollX","scrollY","self","stop","top","window","Date","errno"] +0ms
  mocha:runner globals [] +1ms
  mocha:runner start +1ms

  mocha:runner run suite  +0ms

  mocha:runner run suite Application +21ms
  Application
  mocha:runner run suite Application .sum() +4ms
    .sum()
Application constructed
Adding two numbers 2 3
      ✓ should return the sum of two numbers
  mocha:runner run suite Application .sumAsync() +19ms
    .sumAsync()
Application constructed
      ✓ should return the sum of two numbers (3006ms)
  mocha:runner run suite Application .getFileReader() +3s
    .getFileReader()
Application constructed
Window context exists
      1) should return new new FileReader

  mocha:runner finished running +28ms

  2 passing (3s)
  1 failing

  1) Application
       .getFileReader()
         should return new new FileReader:
     ReferenceError: FileReader is not defined
      at Application.getFileReader (src/Application.js:20:5)
      at Context.getFileReader (src/Application.spec.js:30:26)



  mocha:runner end +1ms
npm ERR! Test failed.  See above for more details.
```

**Comment by plroebuck** [comment]
> Finally, managed to create a mcve with ability to reproduce the issue.
> 
> [mcve-with-issue.zip](https://github.com/mochajs/mocha/files/2534821/mcve-with-issue.zip)

```bash
$ curl -O https://github.com/mochajs/mocha/files/2534821/mcve-with-issue.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   582    0   582    0     0   1474      0 --:--:-- --:--:-- --:--:--  1473
server:babel72 $ unzip mcve-with-issue.zip 
Archive:  mcve-with-issue.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of mcve-with-issue.zip or
        mcve-with-issue.zip.zip, and cannot find mcve-with-issue.zip.ZIP, period.
```

**Comment by iongion** [comment]
@plroebuck The last issue with the zip file, dunno, I am using 7zip for both creating and unpacking

**Comment by plroebuck** [comment]
Its file size is _582 bytes_.

**Comment by iongion** [comment]
Try again, maybe it cached wrong in github CDN somewhere [mcve-with-issue.zip](https://github.com/mochajs/mocha/files/2534982/mcve-with-issue.zip)

**Comment by plroebuck** [comment]
Also, since you are using a glob, drop the `--recursive` argument to Mocha (unnecessary).

**Comment by plroebuck** [comment]
yeah, no change. rename it maybe?

**Comment by iongion** [comment]
I get a valid file when I download - even with curl :

```
$ curl -O https://github.com/mochajs/mocha/files/2534821/mcve-with-issue.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   582    0   582    0     0   1200      0 --:--:-- --:--:-- --:--:--  1200

```

**Comment by plroebuck** [comment]
That's what I get. But obviously the file cannot be unzipped...

**Comment by iongion** [comment]
I have placed it again here 
[mcve-with-issues-2.zip](https://github.com/mochajs/mocha/files/2535152/mcve-with-issues-2.zip)


After some investigation, was able to keep the test engine running, by patching the global scope in the  setup-testing.js file by using fabric's jsdom inclusion and not my own:

```
const fabric = require('fabric');
global.window = fabric.fabric.window;
global.document = fabric.fabric.window.document;
global.navigator = fabric.fabric.window.navigator;
global.Blob = fabric.fabric.window.Blob;
global.File = fabric.fabric.window.File;
global.FileReader = fabric.fabric.window.FileReader;
```

This allows test runner to work.

**Comment by plroebuck** [comment]
No luck with that file either. But sounds like you're good now, right?

**Comment by iongion** [comment]
Somehow, it would be a gain if I can find why test runner silently dies with no output, I close the issue, as soon as I find, I will mention it here, thank you so much!

**Comment by anentropic** [comment]
I am getting this error:
```
> mocha --require @babel/register --require regenerator-runtime

npm ERR! Test failed.  See above for more details.
```

I can't tell from the thread above what is the cause or if there is a fix

My package.json has:
```json
  "dependencies": {
    "chalk": "^4.1.0",
    "drafter": "^2.0.0",
    "escape-string-regexp": "^4.0.0",
    "esm": "^3.2.25",
    "lodash.partial": "^4.2.1",
    "lodash.partialright": "^4.2.1",
    "loglevel": "^1.7.1",
    "pluralize": "^8.0.0",
    "python-range": "^1.0.4",
    "walkdir": "^0.4.1",
    "yargs": "^16.2.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.13.14",
    "@babel/core": "^7.13.14",
    "@babel/node": "^7.13.13",
    "@babel/plugin-proposal-async-generator-functions": "^7.13.8",
    "@babel/plugin-proposal-export-default-from": "^7.12.13",
    "@babel/plugin-proposal-export-namespace-from": "^7.12.13",
    "@babel/preset-env": "^7.13.12",
    "@babel/register": "^7.13.14",
    "chai": "^4.3.4",
    "mocha": "^8.3.2",
    "regenerator-runtime": "^0.13.7",
    "sinon": "^10.0.0",
    "yaml": "^1.10.2"
  },
  "scripts": {
    "test": "mocha --require @babel/register --require regenerator-runtime"
  },
```
```
$ node --version
v12.21.0
$ npm --version
6.14.11
```
