### ISSUE TITLE
ReferenceError: interface is not defined

### ISSUE THREAD

**Issue by DoctorFishy** [mochajs/mocha#3782]
I'm trying to run the example from documentation but the only difference is that when I run it inside my existing project I get the error: ReferenceError: interface is not defined.

```
ReferenceError: interface is not defined
    at Suite.describe (I:\Development Projects\felix\test\test.js:5:3)
    at Object.create (I:\Development Projects\felix\node_modules\mocha\lib\interfaces\common.js:140:19)
    at context.describe.context.context (I:\Development Projects\felix\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Suite.describe (I:\Development Projects\felix\test\test.js:4:2)
    at Object.create (I:\Development Projects\felix\node_modules\mocha\lib\interfaces\common.js:140:19)
    at context.describe.context.context (I:\Development Projects\felix\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Object.<anonymous> (I:\Development Projects\felix\test\test.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at I:\Development Projects\felix\node_modules\mocha\lib\mocha.js:327:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (I:\Development Projects\felix\node_modules\mocha\lib\mocha.js:324:14)
    at Mocha.run (I:\Development Projects\felix\node_modules\mocha\lib\mocha.js:801:10)
    at Object.exports.singleRun (I:\Development Projects\felix\node_modules\mocha\lib\cli\run-helpers.js:207:16)
    at exports.runMocha (I:\Development Projects\felix\node_modules\mocha\lib\cli\run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (I:\Development Projects\felix\node_modules\mocha\lib\cli\run.js:296:3)
    at Object.runCommand (I:\Development Projects\felix\node_modules\mocha\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (I:\Development Projects\felix\node_modules\mocha\node_modules\yargs\yargs.js:1072:28)
    at Object.parse (I:\Development Projects\felix\node_modules\mocha\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (I:\Development Projects\felix\node_modules\mocha\lib\cli\cli.js:62:6)
    at Object.<anonymous> (I:\Development Projects\felix\node_modules\mocha\bin\_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
npm ERR! Test failed.  See above for more details.
```

This dosen't happen in new project initialized from scratch--but I need to test my existing project, not a new one.  I'm at a loss as to why this is happening.

package.json: 
```
{
  "name": "backend",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www",
    "test": "mocha ./test/test.js"
  },
  "dependencies": {
    "assert": "^1.4.1",
    "axios": "^0.18.0",
    "bluebird": "^3.5.1",
    "chai": "^4.2.0",
    "connect-mongo": "^2.0.1",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.4",
    "crypto": "^1.0.1",
    "csrf": "^3.0.6",
    "debug": "~2.6.9",
    "dotenv": "^6.2.0",
    "express": "~4.16.0",
    "express-session": "^1.15.6",
    "http-errors": "~1.6.2",
    "jade": "~1.11.0",
    "jsonwebtoken": "^8.3.0",
    "moment": "^2.23.0",
    "moment-range": "^4.0.1",
    "moment-recur": "^1.0.7",
    "moment-timezone": "^0.5.23",
    "mongoose": "^5.2.12",
    "mongoose-currency": "^0.2.0",
    "mongoose-unique-validator": "^2.0.2",
    "morgan": "~1.9.0",
    "node-quickbooks": "^2.0.25",
    "nodemailer": "^4.7.0",
    "passport": "^0.4.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^5.0.1",
    "pdfkit": "^0.9.0",
    "request": "^2.88.0",
    "session-file-store": "^1.2.0",
    "square-connect": "^2.20181212.0"
  },
  "devDependencies": {
    "mocha": "^6.0.2"
  }
}
```

/test/test.js
```
var assert = require('assert');

describe('Array', () => {
	describe('#indexOf()', () => {
		interface('should return -1 when the value is not present', () => {
			assert.equal(-1, [1,2,3].indexOf(4));
		});
	});
});
```

**Comment by plroebuck** [comment]
```js
    it('should return -1 when the value is not present', () => {
```

**Comment by DoctorFishy** [comment]
Thank you so much for the quick response.  I must have stared at that code for a hour never realizing my IDE must have gotten a bit agro on me when i was typing in the example.

This is embarrassing but I'm so grateful!
