### ISSUE TITLE
Mocha, Babel, and Windows symlinks

### ISSUE THREAD

**Issue by ricick** [mochajs/mocha#3860]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Mocha is not running Babel beforehand when the project is behind a symlink on windows.

I have a small SSD and a larger HDD so to make my life easier I have a hard symlink to D:/projects in C:/Users/MyUser home directory, so can access via ~/projects.

When running `mocha --require @babel/register` I'm getting the Unexpected identifier import problem. I even re-installed windows thinking it might be an environment problem before figuring out that this was the problem

### Steps to Reproduce

Create a simple mocha es6 project in realfoldercontainer/myproject, to be run via npm test with `mocha -r @babel/register` in package.json

Create a hard symlink with `mklink /j linkname realfoldercontainer`

Navigate to linkname/myproject

Run npm test

**Expected behavior:** [What you expect to happen]
```
npm test

> mochatest@1.0.0 test D:\projects\mochatest
> mocha -r @babel/register

  index test
    sayHello function
      √ should say Hello guys!


  1 passing (44ms)
```
**Actual behavior:** [What actually happens]
```
npm test

> mochatest@1.0.0 test D:\testlink\mochatest
> mocha -r @babel/register

D:\projects\mochatest\test\index.test.js:3
import sayHello from "../src/index"
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Module._compile (D:\projects\mochatest\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Object.newLoader [as .js] (D:\projects\mochatest\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at D:\projects\mochatest\node_modules\mocha\lib\mocha.js:327:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\projects\mochatest\node_modules\mocha\lib\mocha.js:324:14)
    at Mocha.run (D:\projects\mochatest\node_modules\mocha\lib\mocha.js:801:10)
    at Object.exports.singleRun (D:\projects\mochatest\node_modules\mocha\lib\cli\run-helpers.js:207:16)
    at exports.runMocha (D:\projects\mochatest\node_modules\mocha\lib\cli\run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (D:\projects\mochatest\node_modules\mocha\lib\cli\run.js:296:3)
    at Object.runCommand (D:\projects\mochatest\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\projects\mochatest\node_modules\yargs\yargs.js:1089:24)
    at Object.parse (D:\projects\mochatest\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (D:\projects\mochatest\node_modules\mocha\lib\cli\cli.js:62:6)
    at Object.<anonymous> (D:\projects\mochatest\node_modules\mocha\bin\_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
npm ERR! Test failed.  See above for more details.
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- Your operating system
  - name and version:
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd):
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

node v11.13.0

    "@babel/cli": "^7.4.3",
    "@babel/core": "^7.4.3",
    "@babel/node": "^7.2.2",
    "@babel/preset-env": "^7.4.3",
    "@babel/register": "^7.4.0",
    "chai": "^4.2.0",
    "jest": "^24.7.1",
    "mocha": "^6.0.2"

### Additional Information
I can now corretctly run the tests by going directly to the folder, but it took a long time to figure this out, including a ssystem rebuild to try and fix the problem.

I'm unsure as to whether this is a babel or mocha issue, so will be posting in both github issues pages.

**Comment by juergba** [comment]
I'm unsure about your hard symlink. I thought hard symlinks in Windows don't work across different partitions and should only point to files, not directories.

**Comment by ricick** [comment]
Technically it's a directory junction. See this guide here:

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

This is the first problem I've encountered using this method.

**Comment by plroebuck** [comment]
How did you conclude this was an issue with Mocha?

**Comment by ricick** [comment]
As I said in the issue, it could be a problem with babel. I'm not sure so i posted the issue in both. I don't know ho to go about testing where the issue lies.

**Comment by ricick** [comment]
One other hint is that if I use a js babel config and console.log in there, i don't see it in the output. This makes me suspect that mocha isn't loading babel rather than babel is loading and then not running, but i could be wrong.

**Comment by plroebuck** [comment]
> I don't know ho to go about testing where the issue lies.

We don't either.
* Saying Windows in the description is insufficient for version information.
* You're using Babel, but didn't provide any configuration information.

You're going to have to provide an [MCVE](https://stackoverflow.com/help/mcve) for anyone but yourself to be able to try.

**Comment by juergba** [comment]
While googling you find statements like: "a directory junction is a classic type of symbolic link, which does not support UNC paths (network paths that begin with \\) and **relative paths**."

"import sayHello from "../src/index"" is a relative path. This could be a problem.
You could try using a soft symbolic link, which should support relative paths.

**Comment by boneskull** [comment]
@juergba It's sounding to me like this is not a Mocha problem.  Is that correct?

**Comment by juergba** [comment]
@boneskull I don't really know, I guess it's rather not related with Mocha.

@ricick 
You could create a very simple ("hello world") js file and require some module, without Mocha/Babel. Then test wether your Windows symlinks do work, on different partitions, with relative paths ...
