### ISSUE TITLE
Not working with node 12

### ISSUE THREAD

**Issue by hugodes** [mochajs/mocha#4084]
### Prerequisites

- [ x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Runing tests with node 12.13.0 throws this error:

<code>
/app/node_modules/mocha/node_modules/yargs/yargs.js:1163 
      else throw err 
           ^ 
 
ReferenceError: primordials is not defined 
    at fs.js:27:26 
    at req_ (/app/node_modules/natives/index.js:143:24) 
    at Object.req [as require] (/app/node_modules/natives/index.js:55:10) 
    at Object.<anonymous> (/app/node_modules/s3/node_modules/graceful-fs/fs.js:1:37) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/node_modules/s3/node_modules/graceful-fs/graceful-fs.js:3:27) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/node_modules/s3/lib/index.js:3:10) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/config/lib/aws/s3.js:2:12) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/app/services/s3.js:6:18) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/app/services/index.js:2:14) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/libs/cron-jobs/recurring-invoice.js:4:18) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/libs/cron-jobs/index.js:2:21) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/app.js:23:18) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at Object.<anonymous> (/app/test/index.js:3:21) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Module.require (internal/modules/cjs/loader.js:849:19) 
    at require (internal/modules/cjs/helpers.js:74:18) 
    at /app/node_modules/mocha/lib/mocha.js:334:36 
    at Array.forEach (<anonymous>) 
    at Mocha.loadFiles (/app/node_modules/mocha/lib/mocha.js:331:14) 
    at Mocha.run (/app/node_modules/mocha/lib/mocha.js:809:10) 
    at Object.exports.singleRun (/app/node_modules/mocha/lib/cli/run-helpers.js:108:16) 
    at exports.runMocha (/app/node_modules/mocha/lib/cli/run-helpers.js:142:13) 
    at Object.exports.handler (/app/node_modules/mocha/lib/cli/run.js:292:3) 
    at Object.runCommand (/app/node_modules/mocha/node_modules/yargs/lib/command.js:242:26) 
    at Object.parseArgs [as _parseArgs] (/app/node_modules/mocha/node_modules/yargs/yargs.js:1104:24) 
    at Object.parse (/app/node_modules/mocha/node_modules/yargs/yargs.js:566:25) 
    at Object.exports.main (/app/node_modules/mocha/lib/cli/cli.js:68:6) 
    at Object.<anonymous> (/app/node_modules/mocha/bin/mocha:164:29) 
    at Module._compile (internal/modules/cjs/loader.js:956:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) 
    at Module.load (internal/modules/cjs/loader.js:812:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) 
    at internal/main/run_main_module.js:17:11 
<code>

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
6.2.2
- The output of `node --version`:
v10.16.3
- Your operating system
  - name and version: MacOS 10.14.6

**Comment by juergba** [comment]
Google for `ReferenceError: primordials is not defined`.
