### ISSUE TITLE
*.mjs support

### ISSUE THREAD

**Issue by stevenvachon** [mochajs/mocha#4114]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I run `mocha` with `--extension=mjs` and `--require=@babel/register` to transpile my ES2019+ code to what the current Node.js version supports.

### Steps to Reproduce

**Expected behavior:** Pass all `*.mjs` files through Babel before running tests.

**Actual behavior:** The `*.mjs` entry point is `require()`'d, resulting in "[ERR_REQUIRE_ESM]: Must use import to load ES Module".

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.2
- The output of `node --version`: 12.13.1
- Your operating system
  - name and version: macOS 10.15.1
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): -
- Any third-party Mocha-related modules (and their versions): [nyc](https://npmjs.com/nyc)
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): babel 7.7.4

**Comment by boneskull** [comment]
`node` now treats `.mjs` as ESM modules and tries to load them as such.  I'm not really sure what can be done about this.

**Comment by boneskull** [comment]
maybe a better place to create an issue would be in babel's repo, or nodejs/modules repo?

please cross-reference if you do

**Comment by brandonros** [comment]
`mocha test/e2e/**.spec.mjs`

```
Brandons-MacBook-Pro-2:api brandonros$ npm run test:e2e

> api@0.0.1 test:e2e /Users/brandonros/Desktop/syndicate/api
> mocha test/e2e/**.spec.mjs

/Users/brandonros/Desktop/syndicate/api/test/e2e/auth.spec.mjs:1
(function (exports, require, module, __filename, __dirname) { import fetch from 'node-fetch'
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/brandonros/Desktop/syndicate/api/node_modules/mocha/lib/mocha.js:311:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/brandonros/Desktop/syndicate/api/node_modules/mocha/lib/mocha.js:308:14)
    at Mocha.run (/Users/brandonros/Desktop/syndicate/api/node_modules/mocha/lib/mocha.js:849:10)
    at Object.exports.singleRun (/Users/brandonros/Desktop/syndicate/api/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/brandonros/Desktop/syndicate/api/node_modules/mocha/lib/cli/run-helpers.js:143:13)
    at Object.exports.handler.argv [as handler] (/Users/brandonros/Desktop/syndicate/api/node_modules/mocha/lib/cli/run.js:305:3)
    at Object.runCommand (/Users/brandonros/Desktop/syndicate/api/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/brandonros/Desktop/syndicate/api/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/Users/brandonros/Desktop/syndicate/api/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/brandonros/Desktop/syndicate/api/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/brandonros/Desktop/syndicate/api/node_modules/mocha/bin/mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@0.0.1 test:e2e: `mocha test/e2e/**.spec.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@0.0.1 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brandonros/.npm/_logs/2020-02-03T19_59_07_927Z-debug.log
Brandons-MacBook-Pro-2:api brandonros$ 

```
