### ISSUE TITLE
TypeError: Cannot set property 'state' of undefined

### ISSUE THREAD

**Issue by TheRoSS** [mochajs/mocha#4119]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
This test gives an error from inside mocha code

```
/home/alex/workspace/pushd.bug/node_modules/mocha/lib/runner.js:684
        test.state = STATE_PASSED;
                   ^

TypeError: Cannot set property 'state' of undefined
    at /home/alex/workspace/pushd.bug/node_modules/mocha/lib/runner.js:684:20
    at done (/home/alex/workspace/pushd.bug/node_modules/mocha/lib/runnable.js:334:5)
    at /home/alex/workspace/pushd.bug/node_modules/mocha/lib/runnable.js:435:7
    at onClose (/home/alex/workspace/pushd.bug/test/server.js:154:3)
    at WebSocket.<anonymous> (/home/alex/workspace/pushd.bug/test/server.js:115:3)
    at WebSocket.emit (events.js:210:5)
    at WebSocket.emitClose (/home/alex/workspace/pushd.bug/node_modules/ws/lib/websocket.js:193:10)
    at Socket.socketOnClose (/home/alex/workspace/pushd.bug/node_modules/ws/lib/websocket.js:861:15)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12)
```

I think this is because the closing socket is trying to call callback after exception has been thrown. And mocha looses its context.

### Steps to Reproduce
yarn install
yarn test

**Expected behavior:** Just mocha's message the test has failed

**Actual behavior:** Message AND exception from mocha's code. No additional tests will be run

**Reproduces how often:** always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:  6.2.2
- The output of `node --version`: v12.13.1 (no es6 features are used)
- Your operating system
  - name and version: ubuntu 18.04
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

### Additional Information
[mocha.zip](https://github.com/mochajs/mocha/files/3923275/mocha.zip)

**Comment by tanjacky** [comment]
I am getting a similar error, although my stack trace seems to deal with [SuperTest](https://github.com/visionmedia/supertest) callbacks
```
/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/mocha/lib/runner.js:687
        test.state = STATE_PASSED;
                   ^

TypeError: Cannot set property 'state' of undefined
    at /Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/mocha/lib/runner.js:687:20
    at done (/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/mocha/lib/runnable.js:334:5)
    at /Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/mocha/lib/runnable.js:435:7
    at Test.request.get.set.expect.expect.end (/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/src/tests/read/organizations.test.js:53:9)
    at Test.assert (/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/supertest/lib/test.js:181:6)
    at localAssert (/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/supertest/lib/test.js:131:12)
    at /Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/superagent/lib/node/index.js:716:12)
    at parser (/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.res.on (/Users/jacky.tan/projects/provider-bindings-sdk/packages/cwi-binding-tests/node_modules/superagent/lib/node/parsers/json.js:19:7)
```

**Comment by juergba** [comment]
@TheRoSS @tanjacky
I have made some changes on the uncaught exception handling.
If you have some time left, could you checkout my `juergba/recover-uncaught` draft branch? Wether it helps or not? Thank you.

**Comment by juergba** [comment]
@TheRoSS @tanjacky
could you please test your test cases with Mocha `v7.0.1`? Thank you.

**Comment by TheRoSS** [comment]
All works perfectly. Thank you
