### ISSUE TITLE
done() called multiple times with should.js

### ISSUE THREAD

**Issue by cliffano** [mochajs/mocha#414]
I'm using mocha with should.js and I wonder how this example gives the error done() called multiple times 

////////////////////////////////////////////////////////////////// blah.js
var should = require('should');

function _something(cb) {
  cb();
}

describe('foo', function () {

  describe('bar', function () {

```
it('should do something', function (done) {
  var x = {};
  _something(function () {
    x.foo = 'bar';
    done();
  });
  x.foo.should.equal('bara');
});
```

  });
});
//////////////////////////////////////////////////////////////////

$ mocha blah.js

  ..

  ✖ 1 of 1 test failed:

  1) foo bar should do something:
     Error: done() called multiple times
      at multiple (/Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runnable.js:126:24)
      at done (/Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runnable.js:132:26)
      at Test.run (/Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runnable.js:151:7)
      at Runner.runTest (/Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runner.js:292:10)
      at /Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runner.js:336:12
      at next (/Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runner.js:220:14)
      at /Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runner.js:229:7
      at next (/Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runner.js:179:23)
      at Array.0 (/Users/cliffano/.nvm/v0.6.10/lib/node_modules/mocha/lib/runner.js:197:5)
      at EventEmitter._tickCallback (node.js:192:40)

But if I changed the equal expectation from 'bara' to the correct 'bar', then the error no longer occurs.
Why is done called multiple times only when should equal check is incorrect?

node v0.6.10
mocha v1.0.3
should v0.6.3

**Comment by mohammedSlimani** [comment]
Make sure that you are not defining any function as async when it is actually sync.
