### ISSUE TITLE
Can't run tests inside subpackage of monorepo if using transpiler (babel)

### ISSUE THREAD

**Issue by soryy708** [mochajs/mocha#4162]
MCVE: https://github.com/soryy708/typeof3.default-repro

### Prerequisites

- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Running all tests in a subpackage of a monorepo with `--require @babel/register` results in an error: `TypeError: (0 , _typeof3.default) is not a function` (coming from babel/runtime)

### Steps to Reproduce

Repro repo: https://github.com/soryy708/typeof3.default-repro
Just run `npm test`

**Expected behavior:** ES6+ tests to run and pass successfully

**Actual behavior:** [What actually happens]
```
TypeError: (0 , _typeof3.default) is not a function
    at _typeof (C:\Users\soryy\Desktop\repro\subrepo\node_modules\@babel\runtime\helpers/typeof.js:2:39)
    at Object.<anonymous> (C:\Users\soryy\Desktop\repro\subrepo\node_modules\regenerator-runtime/runtime.js:710:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module._compile (C:\Users\soryy\Desktop\repro\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (C:\Users\soryy\Desktop\repro\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\soryy\Desktop\repro\subrepo\node_modules\@babel\runtime\regenerator/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module._compile (C:\Users\soryy\Desktop\repro\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (C:\Users\soryy\Desktop\repro\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\soryy\Desktop\repro\subrepo\index.test.js:5:43)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module._compile (C:\Users\soryy\Desktop\repro\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (C:\Users\soryy\Desktop\repro\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at C:\Users\soryy\Desktop\repro\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\soryy\Desktop\repro\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\Users\soryy\Desktop\repro\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\Users\soryy\Desktop\repro\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\Users\soryy\Desktop\repro\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\Users\soryy\Desktop\repro\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\Users\soryy\Desktop\repro\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\Users\soryy\Desktop\repro\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\Users\soryy\Desktop\repro\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\Users\soryy\Desktop\repro\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\Users\soryy\Desktop\repro\node_modules\mocha\bin\mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Reproduces how often:** 100% every time

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.2
- The output of `node --version`: v12.13.0
- Your operating system
  - name and version: Windows 10 Home
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): cmd
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): None
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): Babel 7.8.3 + plugins

### Additional Information

* No global installation of mocha.
* Perhaps related: https://github.com/babel/babel/issues/11036 (don't know if the issue is with babel itself, or with the way mocha calls it via `--require`)

**Comment by soryy708** [comment]
I don't repro with Jest instead of mocha but identical `babel.config.js`. Perhaps the issue is with mocha rather than babel?

**Comment by juergba** [comment]
Windows 10 / Node v12.14.1 / powershell and git-bash

I downloaded your repo, then `npm install`, then `npm test`.
result:
```
  foo
    √ bar

  1 passing (24ms)
```

**Comment by soryy708** [comment]
I just tried again with CMD, also tried with git-bash and with powershell. All the same output: `TypeError: (0 , _typeof3.default) is not a function`

**Comment by soryy708** [comment]
@juergba Did you `npm install` inside `subrepo` as well?
If I don't `npm install` inside the sub-package, I get the same output as you.

**Comment by juergba** [comment]
In the root of your project, that is where your package.json is located, so not in your sub-package directory.

**Comment by soryy708** [comment]
There's a `package.json` both in the root and in `subrepo`. Why was this issue closed?

**Comment by juergba** [comment]
A project has one root. If you install your packages the correct way, your repo is working.
Installing the same packages several times is not the correct way to do it.

**Comment by soryy708** [comment]
It is one root. It's a monorepo. Potentially multiple packages inside one repository.
