### ISSUE TITLE
Mocha does not run tests with ts-node if main entry of package.json does not exist

### ISSUE THREAD

**Issue by karniol** [mochajs/mocha#4179]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I have an npm package written in Typescript with a test suite using Mocha. I have set up Mocha with `ts-node` so that no compiled Javascript will be outputted. When running the tests, Mocha looks for the `"main"` entry in `package.json`, which points to a non-existent `./dist/index.js`, and does not run tests.

### Steps to Reproduce

- Run `npm test` with the following:

##### File structure

```
| node_modules
| src
    - index.ts 
| test
    - index.test.ts
- package.json
- tsconfig.json
```

##### `package.json`

```json
{
    "name": "test",
    "version": "1.0.0",
    "description": "",
    "main": "./dist/index.js",
    "types": "./dist/index.d.ts",
    "files": [
        "/dist"
    ],
    "scripts": {
        "test": "mocha"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@types/mocha": "^7.0.1",
        "mocha": "^7.0.1",
        "source-map-support": "^0.5.16",
        "ts-node": "^8.6.2",
        "typescript": "^3.7.5"
    },
    "mocha": {
        "package": "./package.json",
        "extension": [
            "ts"
        ],
        "spec": [
            "test/**/*.test.ts"
        ],
        "recursive": true,
        "file": [],
        "require": [
            "ts-node/register",
            "source-map-support/register"
        ],
        "ui": "bdd",
        "exit": true
    }
}
```

##### `tsconfig.json`

```
{
    "compilerOptions": {
        "target": "es6",
        "lib": [
            "es2017",
            "es7",
            "es6",
            "dom"
        ],
        "declaration": true,
        "sourceMap": true,
        "outDir": "./dist",
        "removeComments": true,
        "strict": true,
        "noImplicitAny": false,
        "strictNullChecks": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "moduleResolution": "node",
        "baseUrl": "./",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "downlevelIteration": true
    },
    "typeRoots": [
        "node_modules/@types"
    ],
    "types": [
        "node",
        "mocha",
        "chai"         
    ],
    "include": [
        "src/**/*.ts",
    ],
    "exclude": [
        "coverage",
        "node_modules",
        "dist",
        "test/**/*.ts"
    ]
}
```

##### `src/index.ts`

Empty file.

##### `test/index.test.ts`

```javascript
describe('title', () => {
    it('case', () => {
        return;
    });
});
```

**Expected behavior:** Mocha runs tests without looking at the `"main"` entry in `package.json`.

**Actual behavior:** Mocha looks at the `"main"` entry in `package.json`, quits if the file doesn't exist and does not run tests.

```
Error: Cannot find module '$MY_PROJECT_ROOT/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at $MY_PROJECT_ROOT/node_modules/mocha/lib/mocha.js:311:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles ($MY_PROJECT_ROOT/node_modules/mocha/lib/mocha.js:308:14)
    at Mocha.run ($MY_PROJECT_ROOT/node_modules/mocha/lib/mocha.js:849:10)
    at Object.exports.singleRun ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/run-helpers.js:143:13)
    at Object.exports.handler ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/run.js:305:3)
    at Object.runCommand ($MY_PROJECT_ROOT/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] ($MY_PROJECT_ROOT/node_modules/yargs/yargs.js:1087:28)
    at Object.parse ($MY_PROJECT_ROOT/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> ($MY_PROJECT_ROOT/node_modules/mocha/bin/mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! Test failed.  See above for more details.
```

**Reproduces how often:** Every time.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: both `7.0.1`
- The output of `node --version`: `v12.15.0`
- Your operating system
  - name and version: macOS High Sierra 10.13.6
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): `fish`
- ~Your browser and version (if running browser tests):~
- Any third-party Mocha-related modules (and their versions): 
  - `@types/mocha 7.0.1`
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): 
  - `tsc 3.7.5`
  - `ts-node v8.6.2`
  - `source-map-support 0.5.16`

### Additional Information

- Compiling output with `npx tsc` and running `npm test` results in:

```
$MY_PROJECT_ROOT/dist/index.js:1
import { Thing } from './file';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at $MY_PROJECT_ROOT/node_modules/mocha/lib/mocha.js:311:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles ($MY_PROJECT_ROOT/node_modules/mocha/lib/mocha.js:308:14)
    at Mocha.run ($MY_PROJECT_ROOT/node_modules/mocha/lib/mocha.js:849:10)
    at Object.exports.singleRun ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/run-helpers.js:143:13)
    at Object.exports.handler ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/run.js:305:3)
    at Object.runCommand ($MY_PROJECT_ROOT/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] ($MY_PROJECT_ROOT/node_modules/yargs/yargs.js:1087:28)
    at Object.parse ($MY_PROJECT_ROOT/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main ($MY_PROJECT_ROOT/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> ($MY_PROJECT_ROOT/node_modules/mocha/bin/mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-cache@1.0.0 test: `mocha`
npm ERR! Exit status 1
```

- **Creating an empty `index.js` file in `dist` allows me to run tests with no problems.**

**Comment by juergba** [comment]
Re "Additional Information": _ts-node_ does not support ES modules, see [mocha-examples](https://github.com/mochajs/mocha-examples/tree/master/packages/typescript).

**Comment by cspotcode** [comment]
Should this be closed since ts-node does support ESM modules?  Should mocha-examples be updated to reflect this as well?  How often is mocha-examples used as an example these days?

**Comment by juergba** [comment]
@cspotcode I opened an issue in our _mocha-examples_ repo and added some links to your issue/sample in _ts-node_.
