### ISSUE TITLE
🚀 Feature: Xunit reporter Failure node does not include message and type attributes

### ISSUE THREAD

**Issue by rkpareek** [mochajs/mocha#4182]
mocha default xunit reporter <Failure> node does not include message and type attributes

Actual Outcome:

```xml
<testcase classname="Get current provider..." name="1. Sample Test Case" time="0"><failure>

    at Object.assert200OK (Test\controller\request-controller.js:341:23)
    at C:\working_directory\automation-core-microservices\Test\test-apis\RaaS-V2\Authentication-Apis\Access-Token-Apis\GetCurrentProvider.js:58:27
    at pass_cb (Test\controller\request-controller.js:92:17)
    at Test.&#x3C;anonymous&#x3E; (Test\controller\request-controller.js:95:13)
    at Test.assert (node_modules\supertest\lib\test.js:179:6)
    at assert (node_modules\supertest\lib\test.js:131:12)
    at C:\working_directory\automation-core-microservices\node_modules\supertest\lib\test.js:128:5
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:718:3)
    at parser (node_modules\superagent\lib\node\index.js:906:18)
    at Stream.res.on (node_modules\superagent\lib\node\parsers\json.js:19:7)
    at Stream.EventEmitter.emit (domain.js:466:23)
    at Unzip.unzip.on (node_modules\superagent\lib\node\unzip.js:55:12)
    at Unzip.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</failure></testcase>
```

Expected Outcome
```xml
<testcase classname="Get current provider..." name="1. Sample Test Case" time="0">
 <failure message="<This will include the message thrown by assertion>" type="Error">

    at Object.assert200OK (Test\controller\request-controller.js:341:23)
    at C:\working_directory\automation-core-microservices\Test\test-apis\RaaS-V2\Authentication-Apis\Access-Token-Apis\GetCurrentProvider.js:58:27
    at pass_cb (Test\controller\request-controller.js:92:17)
    at Test.&#x3C;anonymous&#x3E; (Test\controller\request-controller.js:95:13)
    at Test.assert (node_modules\supertest\lib\test.js:179:6)
    at assert (node_modules\supertest\lib\test.js:131:12)
    at C:\working_directory\automation-core-microservices\node_modules\supertest\lib\test.js:128:5
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:718:3)
    at parser (node_modules\superagent\lib\node\index.js:906:18)
    at Stream.res.on (node_modules\superagent\lib\node\parsers\json.js:19:7)
    at Stream.EventEmitter.emit (domain.js:466:23)
    at Unzip.unzip.on (node_modules\superagent\lib\node\unzip.js:55:12)
    at Unzip.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</failure></testcase>
```

**Comment by outsideris** [comment]
Are message and type attributes mandatory?

**Comment by rkpareek** [comment]
@outsideris XML extractor (cloud pipeline) looks for these attributes for graphical stistical representation specially for xml(Junit/xunit) outputs

**Comment by JoshuaKGoldberg** [comment]
@rkpareek Sorry to ping so long after this was filed, but I'm new here and not familiar: do you have a link for the xunit spec? And/or, any documentation for the "XML (JUnit/xunit) output extractor (cloud pipeline)" mentioned?

This issue makes sense as filed, but I'd want to see some formal docs on the intended schemas as reference. Thanks!

**Comment by JoshuaKGoldberg** [comment]
Closing out old issues. If someone want to continue the discussion, please do post back - we'd be happy to take a look! 🤎
