### ISSUE TITLE
Mocha cli throws "ES modules is not supported" error

### ISSUE THREAD

**Issue by gcatto** [mochajs/mocha#4445]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I cannot figure out how to run mocha on my project that uses ES modules. My `package.json` file includes `"type": "module"` and my `.mocharc.js` file is fairly simple:

```
export default {
  require: 'should',
  spec: "test/routes/**/*.test.js"
};
```

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

Mocha runs the tests on my project which uses ES modules.

**Actual behavior:** [What actually happens]

```
> my-project@0.0.18 test C:\dev\my-project
> mocha

C:\dev\my-project\node_modules\mocha\lib\cli\config.js:85
    throw new Error(`failed to parse config "${filepath}": ${err}`);
    ^

Error: failed to parse config "C:\dev\my-project\.mocharc.js": Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\dev\my-project\.mocharc.js
require() of ES modules is not supported.
require() of C:\dev\my-project\.mocharc.js from C:\dev\my-project\node_modules\mocha\lib\cli\config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename .mocharc.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\dev\my-project\package.json.

    at exports.loadConfig (C:\dev\my-project\node_modules\mocha\lib\cli\config.js:85:11)
    at loadRc (C:\dev\my-project\node_modules\mocha\lib\cli\options.js:160:21)
    at loadOptions (C:\dev\my-project\node_modules\mocha\lib\cli\options.js:229:20)
    at Object.<anonymous> (C:\dev\my-project\node_modules\mocha\bin\mocha:27:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.0.18 test: `mocha`
npm ERR! Exit status 1
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

I am using node v12.18.3 on Windows

**Comment by gcatto** [comment]
Finally (perhaps took too long...) figured out that needed to rename my `.mocharc.js` to `.mocharc.cjs`
