### ISSUE TITLE
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

### ISSUE THREAD

**Issue by umakanth-pendyala** [mochajs/mocha#4462]
Guys I am getting this error whenever I use async/await functions in it()method
Take a look at the **test_script.dev.js** file 

```
const chai = require("chai");
const chaiHttp = require("chai-http");
const should = chai.should();
const expect = chai.expect;
const server = require("../../../../server.js");

chai.use(chaiHttp);

const request = chai.request(server).keepOpen();

describe("GET /admin/view_dentists", () => {
  let response;
  
  before(async () => {
    response = await request.get("/admin/view_dentists").set({
      Authorization:
        "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVtYUBnbWFpbC5jb20iLCJ1c2VySWQiOiI1Zjc4NTRiNzQ2MmYwNTY3ODQ4N2Y4NWMiLCJyb2xlIjoiYWRtaW4iLCJpc1ZlcmlmaWVkIjp0cnVlLCJpYXQiOjE2MDE3MjE1Mjd9.X-7uTgA9KFRWMrCgoNalUdh--lrH8O6S-WBNfAQbsmI",
      "content-type": "application/json",
    });
  });
  it("should send statusCode 200 for an admin user", (done) => {
    response.body.statusCode.should.be.eq(200);
    done();
  });
  it("should send json data for admin user", (done) => {  
    expect(response.body).to.be.an("object");
    done();
  });
  it("should send status 401 when token is not present", async (done) => {
    response = await request.get("/admin/view_dentists").set({
      "content-type": "application/json",
    });
    console.log(response.body.statusCode);
    response.body.statusCode.should.be.eq(401);
  });
});
```

when I type npm run test command in my terminal. I get the following output

```
GET /admin/view_dentists
database connection successful
server is on port 3000
    √ should send statusCode 200 for an admin user
    √ should send json data for admin user
401
    1) should send status 401 when token is not present


  2 passing (10s)
  1 failing

  1) GET /admin/view_dentists
       should send status 401 when token is not present:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\Smilycon Internship\Journal Server\test\app\routes\admin\list_dentists.dev.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```
Even though I extend the time to 10s, It's throwing me an error.
If I have failed to describe the problem clearly. Please tell me what else do I have to upload.

**Comment by juergba** [comment]
@umakanth-pendyala please note this is an issue tracker, not a help forum. You can try to get support in our [gitter chanel](https://gitter.im/mochajs/mocha).

`it("should send status 401 when token is not present", async (done) => {`
Above line doesn't make sense, you have an `async` keyword and a `done`callback. And you never call the callback in your code.
