### ISSUE TITLE
Chai Mocha unit Testing Issue

### ISSUE THREAD

**Issue by ashishsme14** [mochajs/mocha#4562]
We are given below task as write test cases for basic conversions using mocha and chai. it contains :

1. adddetails
2. deleteDetails
3. editDetails
4. updateDetails
5. detailsPop
6. concatData

Below is index.js code which is fixed where we cannot change anything -

```
module.exports = {
  
  addDetails: function() {
    let data =[]
    data.push("one");
    return data
  },

  deleteDetails: function() {
    let data =["one" , "two"]
    data.splice(0 , 1)
    return data
  },

  editDetails: function() {
    let data =["one"]
    data.splice(0 , 1 , "three")
    return data
  },

  updateDetails: function() {
    let data = ["one" , "three"]
    data.splice(1 , 0 , "two")
    return data
  },

  detailsPop: function() {
    let numb = ["one" , "two"]
    numb.pop()
    return numb
  },

  concatData: function() {
    let data1 = ["one"]
    let data2 = ["two"]
    let result = data1.concat(data2)
    return result
  }
 }
```

Based om above index.js we had written below code. But when we running below code we are getting time out issue. Not sure where we went wrong. Hence need expertise advice on below code -

```
var assert = require("assert");
var crud = require('../src/index');

describe('Crud application', function(){
  it('add Details',function(){
    assert.equal(crud.addDetails(),[ "one" ]);
  });
  it('delete Details',function(){
    assert.equal(crud.deleteDetails(),[ "two" ] );
  });
  it('edit Details',function(){
    assert.equal(crud.editDetails(),[ "three" ] );
  });
  it('update Details',function(){
    assert.equal(crud.updateDetails(),[ "one", "two", "three" ]);
  });
  it('details Pop',function(){
    assert.equal(crud.detailsPop(),[ "one" ] );
  });
  it('concat Data',function(){
    assert.equal(crud.concatData(),[ "one", "two" ]);
  });

});
```

Error detail -

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0030" tests="6" failures="6">
  <testsuite name="Root Suite" timestamp="2021-01-30T16:00:15" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Crud application" timestamp="2021-01-30T16:00:15" tests="6" file="/projects/challenge/test/indextest.js" time="0.0030" failures="6">
    <testcase name="Crud application add Details" time="0.0030" classname="add Details">
      <failure message="[ &apos;one&apos; ] == [ &apos;one&apos; ]" type="AssertionError [ERR_ASSERTION]"><![CDATA[AssertionError [ERR_ASSERTION]: [ 'one' ] == [ 'one' ]
    at Context.<anonymous> (test/indextest.js:6:12)]]></failure>
    </testcase>
    <testcase name="Crud application delete Details" time="0.0000" classname="delete Details">
      <failure message="[ &apos;two&apos; ] == [ &apos;two&apos; ]" type="AssertionError [ERR_ASSERTION]"><![CDATA[AssertionError [ERR_ASSERTION]: [ 'two' ] == [ 'two' ]
    at Context.<anonymous> (test/indextest.js:9:12)]]></failure>
    </testcase>
    <testcase name="Crud application edit Details" time="0.0000" classname="edit Details">
      <failure message="[ &apos;three&apos; ] == [ &apos;three&apos; ]" type="AssertionError [ERR_ASSERTION]"><![CDATA[AssertionError [ERR_ASSERTION]: [ 'three' ] == [ 'three' ]
    at Context.<anonymous> (test/indextest.js:12:12)]]></failure>
    </testcase>
    <testcase name="Crud application update Details" time="0.0000" classname="update Details">
      <failure message="[ &apos;one&apos;, &apos;two&apos;, &apos;three&apos; ] == [ &apos;one&apos;, &apos;two&apos;, &apos;three&apos; ]" type="AssertionError [ERR_ASSERTION]"><![CDATA[AssertionError [ERR_ASSERTION]: [ 'one', 'two', 'three' ] == [ 'one', 'two', 'three' ]
    at Context.<anonymous> (test/indextest.js:15:12)]]></failure>
    </testcase>
    <testcase name="Crud application details Pop" time="0.0000" classname="details Pop">
      <failure message="[ &apos;one&apos; ] == [ &apos;one&apos; ]" type="AssertionError [ERR_ASSERTION]"><![CDATA[AssertionError [ERR_ASSERTION]: [ 'one' ] == [ 'one' ]
    at Context.<anonymous> (test/indextest.js:18:12)]]></failure>
    </testcase>
    <testcase name="Crud application concat Data" time="0.0000" classname="concat Data">
      <failure message="[ &apos;one&apos;, &apos;two&apos; ] == [ &apos;one&apos;, &apos;two&apos; ]" type="AssertionError [ERR_ASSERTION]"><![CDATA[AssertionError [ERR_ASSERTION]: [ 'one', 'two' ] == [ 'one', 'two' ]
    at Context.<anonymous> (test/indextest.js:21:12)]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by juergba** [comment]
Please note this is an issue tracker, not a help forum.

There are no timeout issues, your assertions are failing.
With `assert.equal()` you are not comparing the content of your arrays, but their references.
`[ 'one' ] == [ 'one' ]` is `false`, since you have two different arrays (with the identical content though).
Use [deepStrictEqual](https://nodejs.org/docs/latest-v14.x/api/assert.html#assert_assert_deepstrictequal_actual_expected_message) instead of `assert.equal` to compare arrays.
