### ISSUE TITLE
Error: Cannot find module '@/rum/perf/common'

### ISSUE THREAD

**Issue by zengzuo613** [mochajs/mocha#4628]
# problem
The following exception occurs when I run a unit test case.
```
"C:\Program Files\nodejs\node.exe" D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\bin\mocha --require ts-node/register --ui bdd --reporter "D:\J2eeSoft\WebStorm 2020.2.3\plugins\NodeJS\js\mocha-intellij\lib\mochaIntellijReporter.js" D:\WorkCode\Git\my-group\ftwo-web-sdk\test\unit\rum\perf\commonTest.ts --grep "^My math library "

Error: Cannot find module '@/rum/perf/common'
Require stack:
- D:\WorkCode\Git\my-group\ftwo-web-sdk\test\unit\rum\perf\commonTest.ts
- D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\esm-utils.js
- D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\mocha.js
- D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\cli\one-and-dones.js
- D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\cli\options.js
- D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\bin\mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (D:\WorkCode\Git\my-group\ftwo-web-sdk\test\unit\rum\perf\commonTest.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module.m._compile (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.require.extensions.<computed> [as .ts] (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.exports.requireOrImport (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\esm-utils.js:55:34)
    at Mocha.loadFilesAsync (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\mocha.js:473:19)
    at singleRun (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\cli\run-helpers.js:125:15)
    at exports.runMocha (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\cli\run-helpers.js:190:10)
    at Object.exports.handler (D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\lib\cli\run.js:362:11)
    at D:\WorkCode\Git\my-group\ftwo-web-sdk\node_modules\mocha\node_modules\yargs\build\index.cjs:443:71

Process finished with exit code 1
```

# code
```typescript
import * as mocha from 'mocha';
import * as chai from 'chai';
import { ResourceModel } from '@/types/rum/resstats';
import * as common from '@/rum/perf/common';

const expect = chai.expect;

describe('My math library', () => {
  const resourceModels: Array<ResourceModel> = [];
  const resourceModel1: ResourceModel = { name: 'name1', duration: 1001, size: 1002, transSize: 1003, type: '1' };
  resourceModels.push(resourceModel1);

  it('should be able to add things correctly', () => {
    expect(common.computeResDuration(resourceModels)).to.equal(3003);
  });
});
```
# append
The dependent file can be found through the link in WebStorm.
![image](https://user-images.githubusercontent.com/76633368/115700800-a6481e00-a399-11eb-96db-5b09a3631ff2.png)

# directory structure
![image](https://user-images.githubusercontent.com/76633368/115701281-35553600-a39a-11eb-8b88-6a60cf22d800.png)

# package.json
```json
  "scripts": {
    "test": "mocha --require ts-node/register test/**/*Test.ts",
  }
```

# question
Is it related to @/path？

**Comment by outsideris** [comment]
`@` seems module bundler's feature like webpack/babel. Isn't it happened without mocha?

**Comment by legend80s** [comment]
@zengzuo613  how to fix this
