### ISSUE TITLE
mocha test fails when i add route middleware in express

### ISSUE THREAD

**Issue by Xexnon** [mochajs/mocha#4749]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
After Adding route middleware mocha runs into error but after commenting the route middlware mocha test works
i have configured it to run in my test folder only. 
```
const express = require('express)
const routes = require('../routes)
const app = express()

app.use('/api/, routes)

```

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
```
 ✓ generateId should generate a uuid
    ✓ generateTransactionRef should generate a uuid
    ✓ hashPassword should hash a plain password (73ms)
    ✓ compareHash should compare hashed password to the plain value (65ms)
    ✓ generateToken should generate a string of token with different characters
    ✓ addTokenToData should generate a user object with the token included
    ✓ verifyToken should decoded the token
    ✓ validateInput should validate an input using a schema
    ✓ checkArrayIsNotEmpty should check if an array is empty
```

**Actual behavior:** [What actually happens]
Users/xexnon/Resource/practice/wallet-api/app/utils/helpers/helper.js:1
TypeError: Cannot destructure property 'SECRET' of '_07c‍.a(...)' as it is undefined.
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/utils/helpers/helper.js:11:9)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/utils/helpers/index.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/utils/index.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/validations/user.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/validations/index.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/routes/v1/auth/index.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/routes/v1/index.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/config/app.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/config/index.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/flutterwave/helpers/helper.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/app/flutterwave/helpers/index.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/xexnon/Resource/practice/wallet-api/test/unit/flwhelper.test.js:1)
    at Generator.next (<anonymous>)
    at Object.exports.requireOrImport (/Users/xexnon/Resource/practice/wallet-api/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/Users/xexnon/Resource/practice/wallet-api/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/Users/xexnon/Resource/practice/wallet-api/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/Users/xexnon/Resource/practice/wallet-api/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/Users/xexnon/Resource/practice/wallet-api/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/Users/xexnon/Resource/practice/wallet-api/node_modules/mocha/lib/cli/run.js:362:11)
    at /Users/xexnon/Resource/practice/wallet-api/node_modules/yargs/build/index.cjs:443:71
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)
    at internal/main/run_main_module.js:17:47

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.4.0
- The output of `node --version`:v14.17.0
- Your operating system
  - name and version: Mac 
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):chai
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): esm 3.2.25

**Comment by juergba** [comment]
@Xexnon without any sample to reproduce this issue, you will have to find the cause on your own. I will close this issue within the next few days.

The `esm` package hasn't been maintained since more than two years. I guess you use it on your own risk. I recommend to switch to Node's native ESM support, which is supported by Mocha.
