### ISSUE TITLE
it.only breaks if test title ends with three question mark characters (???)

### ISSUE THREAD

**Issue by d0ox** [mochajs/mocha#4810]
# Description
If you create a test case that uses the `only` function like this:
```typescript
it.only('should only parse  ???', () => {
//... some test code
```
and please notice that the test title ends with `???`.

If you start the test case from the treminal using the following command:
```
mocha -r ts-node/register --ui mocha-cakes-2 ".\specs\<your spec file>"
```

it will produce the following error:

```terminal
> mocha -r ts-node/register --ui mocha-cakes-2 ".\specs\grammar.spec.ts"


SyntaxError: Invalid regular expression: /Grammar should only parse  ???/: Nothing to repeat
    at new RegExp (<anonymous>)
    at Mocha.grep (D:\git\sillk\node_modules\mocha\lib\mocha.js:499:25)
    at Function.only (D:\git\sillk\node_modules\mocha-cakes-2\mocha-cakes.js:88:13)
    at Suite.<anonymous> (D:\git\sillk\specs\grammar.spec.ts:204:8)
    at wrapper (D:\git\sillk\node_modules\mocha-cakes-2\mocha-cakes.js:108:10)
    at Object.<anonymous> (D:\git\sillk\specs\grammar.spec.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (D:\git\sillk\node_modules\ts-node\src\index.ts:1365:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (D:\git\sillk\node_modules\ts-node\src\index.ts:1368:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at requireOrImport (D:\git\sillk\node_modules\mocha\lib\esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (D:\git\sillk\node_modules\mocha\lib\esm-utils.js:28:26)
    at Mocha.loadFilesAsync (D:\git\sillk\node_modules\mocha\lib\mocha.js:386:19)
    at singleRun (D:\git\sillk\node_modules\mocha\lib\cli\run-helpers.js:149:15)
    at exports.runMocha (D:\git\sillk\node_modules\mocha\lib\cli\run-helpers.js:186:11)
    at Object.exports.handler (D:\git\sillk\node_modules\mocha\lib\cli\run.js:319:11)
    at D:\git\sillk\node_modules\yargs\lib\command.js:241:49
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sillk@1.0.0 test-single: `mocha -r ts-node/register --ui mocha-cakes-2 ".\specs\grammar.spec.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sillk@1.0.0 test-single script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dusan\AppData\Roaming\npm-cache\_logs\2022-01-11T23_07_53_544Z-debug.log
```

But if you remove ```???``` the test will run normaly.

Also this can not be reproduced when using the Mocha Test Runner in VSCODE.

**Comment by juergba** [comment]
@d0ox This issue's description is incomplete, please add all required information, otherwise I will close it within a few days.

I tried to reproduce this issue on Mocha@9.1.3 without success. I used a simple test scenario with plain javascript and Mocha's own `spec` reporter. Please add a simple test case for reproduction, narrowing down the issue as far as possible. Thank you.

**Comment by d0ox** [comment]
@juergba here is the [repo](https://github.com/d0ox/mocha_issue_4810) I created for you to check out the bug.

**Comment by KunaPrime** [comment]
can reproduce with Mocha@9.1.3, npm 8.1.4, nodejs v10.19.0, ubuntu 20.4.3

**Comment by juergba** [comment]
@d0ox This a nice repo, from here it should be easy for you to narrow down the error cause. You are using Mocha, typescript with _ts-node_ and a third-party reporter _mocha-cakes-2._ I don't think it's Mocha.

@KunaPrime Node v10 has been end-of-life ages ago and is not supported by Mocha@9.1.3 anymore.

**Comment by d0ox** [comment]
@juergba I made a pure js branch with nothing but mocha and chai [branch](https://github.com/d0ox/mocha_issue_4810/tree/mocha_pure_js) and I was not able to reproduce this problem. I am running the test on ```win10```, and ```node V14.18.1```. Seems that I could be a problem of mocha-ts.

**Comment by juergba** [comment]
@d0ox I'm going to close this issue.
You are using different packages, one of these is Mocha. I tried to support you in narrowing down the issue, but well ...
`grep` is  running correctly with plain Mocha and IMO it's an issue with the third-party reporter _mocha-cakes-2_ you are using.
