### ISSUE TITLE
Mocha does not work with typescript when `compilerOptions.module` set to `esnext`

### ISSUE THREAD

**Issue by ryanzec** [mochajs/mocha#4919]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When attempting to use Mocha with TypeScript that has `compilerOptions.module` set to `esnext`, mocha fails to work with the following error:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/ryanzec/repositories/monorepo-template/packages/utils/tests/drag-drop.spec.ts
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/Users/ryanzec/repositories/monorepo-template/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/Users/ryanzec/repositories/monorepo-template/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/Users/ryanzec/repositories/monorepo-template/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/Users/ryanzec/repositories/monorepo-template/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/ryanzec/repositories/monorepo-template/node_modules/mocha/lib/cli/run.js:374:5)
```

The same exact code / test works fine if `compilerOptions.module` is set to `commonjs`.

### Steps to Reproduce

- Checkout this repo: https://github.com/ryanzec/monorepo-template
- Change the `tsconfig.testing.json` file so that `compilerOptions.module` is set to `esnext`
- Run `yarn test:unit`

**Expected behavior:** Tests should run

**Actual behavior:** Error as described above

**Reproduces how often:** Everytime

### Versions

Mocha: `10.0.0`
Node: `v16.15.0`
OS: `Mac OS 11.6 (64bit)`
Bash: `3.2.57(1)-release (x86_64-apple-darwin20)`
`ts-node`: `10.9.1`
`typescript`: `4.8.2`

**Comment by ryanzec** [comment]
Same issue happen in the `package.json` has `"type": "module"`

**Comment by tombrouwer** [comment]
Unfortunately this happens to me too.

**Comment by Zxj199604** [comment]
me too

**Comment by juergba** [comment]
This is not a mocha issue. Looking at your repo I guess you have found the correct way to configure _ts-node_ with ESModules.

**Comment by ryanzec** [comment]
No I have not found a way to get mocha to work with esmodules, I have it working by having a separate `tsconfig` for mocha that sets `module` to `commonjs` which is less than ideal since the production tsconfig has `module` set to `esnext`.

**Comment by rschoenbichler** [comment]
this issues seems to still be relevant, as just setting the module resolution to commonjs for mocha breaks code coverage that can be genreated i.e. via nyc
