### ISSUE TITLE
TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by strk** [mochajs/mocha#493]
Happening with node-0.8.0 and mocha-1.2.2

```
/home/src/cartodb/superagent/node_modules/mocha/lib/runner.js:410
  if ('failed' == runnable.state) return;
                          ^
TypeError: Cannot read property 'state' of undefined
    at Runner.uncaught (/home/src/cartodb/superagent/node_modules/mocha/lib/runner.js:410:27)
    at process.uncaught (/home/src/cartodb/superagent/node_modules/mocha/lib/runner.js:443:10)
    at process.EventEmitter.emit (events.js:115:20)
```

Invocation is:
```
mocha --require should --reporter dot --timeout 100 --growl test/node/*.js
```

From top-dir of superagent master

**Comment by danielstjules** [comment]
Yup, closing since it was fixed in https://github.com/mochajs/mocha/commit/b255074d3104fd8b7dd1697740696bf38fe96783 :)
