### ISSUE TITLE
Broken IntelliJ integration when tests are running in parallel 2

### ISSUE THREAD

**Issue by Tcharl** [mochajs/mocha#4940]
Tried to execute intellij reporter on a quite difficult project, but didn't work.

The test suite is the one of [jhipster/generator-jhipster.](https://github.com/jhipster/generator-jhipster)

### Description

Multiple issues
 - --jobs=1 trick does not work because the index.mjs file is using await. If used, results in the following error (which seems to be normal)
```
Error: Transform failed with 2 errors:
/Users/charliemordant/Code/Sources/jhipster/generator-jhipster/generators/base/index.mjs:30:19: ERROR: Top-level await is currently not supported with the "cjs" output format
```
 - The loader doesn't take the good one (doesn't support ESM) (as it's using _mocha instead using mocha, and enabling debug) I had to
   - node_options: `-r @esbuild-kit/cjs-loader --loader @esbuild-kit/esm-loader --experimental-specifier-resolution node` despites the presence of the .mocharc containing these infos
   - Extra mocha options: --no-insight --forbid-only --parallel --max-old-space-size=4096
 - Executing in parrallel mode leads to: 
 ```
TypeError: Cannot read properties of undefined (reading 'length')
    at Object.joinList (/Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijUtil.js:95:23)
    at getLocationPath (/Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:56:17)
    at findOrCreateAndRegisterSuiteNode (/Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:20:26)
    at registerTestNode (/Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:92:19)
    at startTest (/Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:108:16)
    at ParallelBufferedRunner.<anonymous> (/Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:328:5)
    at ParallelBufferedRunner.<anonymous> (/Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijUtil.js:129:17)
    at ParallelBufferedRunner.emit (node:events:513:28)
    at emitEvent (/Users/charliemordant/Code/Sources/jhipster/generator-jhipster/node_modules/mocha/lib/nodejs/parallel-buffered-runner.js:119:12)
    at <anonymous> (/Users/charliemordant/Code/Sources/jhipster/generator-jhipster/node_modules/mocha/lib/nodejs/parallel-buffered-runner.js:196:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
warn mocha-intellij: /Users/charliemordant/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijUtil.js:95
    itemLength = item.length;
```

Thus I have no mean to run the mocha suite in debug mode in intellij...

### Steps to Reproduce
Clone generator-jhipster, import in intellij, copy the package.json 'test' directive in an intellij configuration.

**Expected behavior:** Tests to execute well in IJ

**Actual behavior:** fails, while `npm test` works

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: `"mocha": "10.1.0",`
- The output of `node --version`: `v16.18.0`
- Your operating system
  - name and version: max ventura
  - architecture (32 or 64-bit): Arm M1
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): FF, but the tests don't use it...

### Additional Information

Feel free to ask!
However, thanks for this framework, the js community relies on it!

**Comment by juergba** [comment]
@Tcharl I won't spend any time on this issue. An issue you have not even tried to narrow down to the core problem.

Will be closed unless you have some specific questions to mocha.

**Comment by Tcharl** [comment]
Hi @juergba ,

Really sorry, I tried to narrow as much as I could the issue (I'm just an humble java guy that is learning javascript on my spare time to contribute to a js-written java code generator), I promise that I spent many hour trying to identify from where came the issue.
I was also maybe lead to this repo by mistake due to [this issue](https://github.com/mochajs/mocha/issues/4403), which made me think that this repo was also in charge of the IJ reporter and that this --parrallel option was supposed to work due the the `ParallelBuffered` change introduced in the mocha codebase.

Please accept my apologies, I'll submit the request to Jetbrain folks and hope they'll fix it: I'm unfortunately not (yet) skilled enough to fix this kind of javascript black magic by myself.

Thank you again for this amazing framework.
Kind regards

**Comment by juergba** [comment]
@Tcharl ok, no worries. Thank you for your understandig and kind words.
