### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED] Mocha incompatible with "deepdash"

### ISSUE THREAD

**Issue by c0ncentus** [mochajs/mocha#4956]
I use deepdash since half-year and dont understand why "export thing" is related to the test ...
or why it apply some specefic strict ts-rules for running tests.

````
> mocha -r ts-node/register src/Manipulation/Node/string/test.spec.ts


Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './es/eachDeep' is not defined by "exports" in C:\WORKBRENCH\PACKAGE\LordTs\node_modules\deepdash\package.json
    at new NodeError (node:internal/errors:393:5)
    at exportsNotFound (node:internal/modules/esm/resolve:295:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:631:9)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\dontUnderstant.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\Manipulation\Utils\color\operation.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\Manipulation\Utils\color\index.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\Manipulation\Node\number\convert.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\Manipulation\Node\number\index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\Manipulation\Node\string\random.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\Manipulation\Node\string\index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\WORKBRENCH\PACKAGE\LordTs\src\Manipulation\Node\string\test.spec.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\ts-node\src\index.ts:1621:12)   
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.exports.requireOrImport (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\mocha\lib\nodejs\esm-utils.js:53:16)
    at async Object.exports.loadFilesAsync (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\mocha\lib\nodejs\esm-utils.js:100:20)     
    at async singleRun (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (C:\WORKBRENCH\PACKAGE\LordTs\node_modules\mocha\lib\cli\run.js:370:5)
````
when execute this command
```
mocha -r ts-node/register src/Manipulation/Node/string/test.spec.ts
```
if it found 0 test then it exit with a correct message so I suppose that Mocha found the test file but cannot execute it beacause of deepdash (or more ?).

my tests concerned a string:
```
import { makeSuiteTest } from "../../../MBT";
import {
    randomStr, analysPassword, capitalizeWord, insertAt, isCorrectString, replaceAll, replaceChainAll,
    strTextStruct
} from "./";

makeSuiteTest(
    {
        arrange: data => capitalizeWord(data),
        nameObject: 'capitalizeWord',
        bundleTests: [
            {
                type: "Commun",
                tests: [
                    { operande: "equal", data: "captain", expected: "Captain" },
                    { operande: "equal", data: "commandant ivovovna", expected: "Commandant ivovovna" }
                ],
            },
            {
                type: "Alternate",
                tests: [
                    { operande: "equal", data: "3", expected: "3" }
                ],
            }
        ]
    }
);


makeSuiteTest(
    {
        arrange: data => insertAt(data.str, data.strAdd, data.position),
        nameObject: 'insertAt',
        bundleTests: [
            {
                type: "Commun",
                tests: [
                    { operande: "equal", data: {str:"elune", strAdd:"Fr", position:0}, expected: "Frelune" },
                    { operande: "equal", data: {str:"elune", strAdd:"shak", position:4}, expected: "elunshake" }
                ],
            },
        ]
    }
);

makeSuiteTest(
    {
        arrange: data => replaceAll(data.value, data.search, data.replacement),
        nameObject: 'replaceAll',
        bundleTests: [
            {
                type: "Commun",
                tests: [
                    { operande: "equal", data: {value:"elune", search:"e", replacement:"bi"}, expected: "bilunbi" },
                    { operande: "equal", data: {value:"elunelun", search:/lun/, replacement:""}, expected: "ee" }
                ],
            },
        ]
    }
)
```

**Comment by juergba** [comment]
@c0ncentus I'm going to close this issue, this topic is out of Mocha's scope. This is Mocha's issue tracker, not a help forum. There is no way either to reproduce your issue with present informations, lacking most input as a simple sample, configuration files, etc.

Some input from my side:
- why _deepdash_, not _deepdash-es_?
- why `-r ts-node/register`, not _ts-node_'s ESM solution (with `--loader` option)?
- try to get it working without _ts-node_ first, by using `tsc`
