### ISSUE TITLE
🚀 Feature: JSON stream reporter: show expected and actual object for deeply nested objects in case of error

### ISSUE THREAD

**Issue by edi9999** [mochajs/mocha#4975]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

Currently, I mostly use the json-reporter with some postprocessing programm to display the output the way I exactly want.

**Describe the solution you'd like**

```output
["start",{"total":75}]
["fail",{"title":"should throw error with null value","fullTitle":"Full table should throw error with null value","file":"/home/edgar/www/xtm/modules/table/es6/test.js","duration":55,"currentRetry":0,"err":"expected { name: 'RenderingError', …(2) } to deeply equal { name: 'RenderingError', …(2) }","stack":"AssertionError: expected { name: 'RenderingError', …(2) } to deeply equal { name: 'RenderingError', …(2) }\n    at errorVerifier (node_modules/docxtemplater/js/tests/utils.js:349:32)\n    at expectToThrow (node_modules/docxtemplater/js/tests/utils.js:388:3)\n    at Context.<anonymous> (es6/test.js:295:4)\n    at process.processImmediate (node:internal/timers:476:21)"}]
["end",{"suites":1,"tests":1,"passes":0,"pending":0,"failures":1,"start":"2023-04-03T09:47:50.864Z","end":"2023-04-03T09:47:50.925Z","duration":61}]
["start",{"total":75}]
["fail",{"title":"should throw error with null value","fullTitle":"Full table should throw error with null value","file":"/home/edgar/www/xtm/modules/table/es6/test.js","duration":32,"currentRetry":0,"err":"expected { name: 'RenderingError', …(2) } to deeply equal { name: 'RenderingError', …(2) }","stack":"AssertionError: expected { name: 'RenderingError', …(2) } to deeply equal { name: 'RenderingError', …(2) }\n    at errorVerifier (node_modules/docxtemplater/js/tests/utils.js:349:32)\n    at expectToThrow (node_modules/docxtemplater/js/tests/utils.js:388:3)\n    at Context.<anonymous> (es6/test.js:295:4)\n    at process.processImmediate (node:internal/timers:476:21)"}]
["end",{"suites":1,"tests":1,"passes":0,"pending":0,"failures":1,"start":"2023-04-03T09:50:55.895Z","end":"2023-04-03T09:50:55.930Z","duration":35}]
```

As you can see, the failure doensn't give me enough info as to why the test failed (the actual and expected object).

```
AssertionError: expected { name: 'RenderingError', …(2) } to deeply equal { name: 'RenderingError', …(2) }\n    at errorVerifier (node_modules/docxtemplater/js/tests/utils.js:349:32)\n    at expectToThrow (node_modules/docxtemplater/js/tests/utils.js:388:3)\n    at Context.<anonymous> (es6/test.js:295:4)\n    at process.processImmediate (node:internal/timers:476:21)
```

**Describe alternatives you've considered**

I could write my own mocha reporter

(The default reporter shows the difference when I run the same tests)

Maybe to avoid too big json for current users, this could be behind a mocha flag.

Hope that helps.

**Comment by JoshuaKGoldberg** [comment]
> I could write my own mocha reporter

Indeed. The `json` reporter is really made for machine consumption. If you want human-readable, your best bet would either be the `spec` reporter or writing your own custom one for your needs. Tests that fail on big pieces of JSON data aren't particularly common (which is why nobody else has requested this feature that I can find).

Thanks for filing! 🤎
