### ISSUE TITLE
🛠 Repo: Nondeterministic test failures on the main branch

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha#5052]
### Tooling Suggestion Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `master` branch of the repository.
- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I want to provide a PR to resolve this

### Overview

Example from 9f9917822fa1d3fe2ec2867809cbbf86f4165f0c -> https://github.com/mochajs/mocha/actions/runs/7335062477/job/19972549741:

```plaintext
  313 passing (2m)
  1 pending
  2 failing

  1) --exit
       default behavior
         should not force exit after root suite completion:
     Uncaught UnexpectedError: 
expected true to be false

      at postmortem (test/integration/options/exit.spec.js:51:9)
      at /home/runner/work/mocha/mocha/test/integration/helpers.js:69:7
      at ChildProcess.<anonymous> (test/integration/helpers.js:352:5)
      at ChildProcess.emit (node:events:517:28)
      at maybeClose (node:internal/child_process:1098:16)
      at ChildProcess._handle.onexit (node:internal/child_process:303:5)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  2) --exit
       when disabled
         should not force exit after root suite completion:
     Uncaught UnexpectedError: 
expected true to be false

      at postmortem (test/integration/options/exit.spec.js:51:9)
      at /home/runner/work/mocha/mocha/test/integration/helpers.js:69:7
      at ChildProcess.<anonymous> (test/integration/helpers.js:352:5)
      at ChildProcess.emit (node:events:517:28)
      at maybeClose (node:internal/child_process:1098:16)
      at ChildProcess._handle.onexit (node:internal/child_process:303:5)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace
```

### Additional Info

This is surprising given that we haven't changed any code since before these started. ~All~ commits on `master` are failing right now.

* Last commit with ✅: b41e98533aa0fb87d7ba61163254881607a8a8c5
* Two commits with no CI runs: 4b60c1ad07a3baaedab86c3787d8baad29538b8f, 060f77dc2f97daac996fce926e7527e438c17e85
* First commit with ❌: eca4fec9eee1332a0474b80aa1740822438955f3 

Edit: ah, I spoke too soon! 645469e1920e2e86458ff068e74eef2e2915083e is passing ✅. Updating this issue's title to indicate that the tests are nondeterministic. _Hooray_.

**Comment by voxpelli** [comment]
The tests are really failing at random all over the place. A couple of `rerun failed tests` later and all tests are passing.

**Comment by mark-wiemer** [comment]
Going to see if I can look into this as it's blocking #5319 and also we shouldn't have flaky tests as a test framework!

**Comment by mark-wiemer** [comment]
Some current failures are Node 20 Ubuntu:

State | OS | Node version | Sample workflow logs link
--|--|--|--
Passing | Windows | 20.18.3 | [Node 20 Windows logs - mark-wiemer/mocha fork](https://github.com/mark-wiemer/mocha/actions/runs/14098468095/job/39490278453?pr=1)
Failing | Ubuntu | 20.19.0 | [Node 20 Ubuntu logs - mark-wiemer/mocha fork](https://github.com/mark-wiemer/mocha/actions/runs/14098468095/job/39490278442?pr=1 )

**Comment by mark-wiemer** [comment]
@mochajs/maintenance-crew, curious for your thoughts to make our build workflow more stable:

1. Change our workflow to pin exact versions of nodes, e.g. 20.18.3 instead of just 20
2. Add a second workflow "mocha-node-lts" that tests recent Node versions on a schedule, but isn't used directly in PRs
3. Add a step to the "mocha-node-lts" workflow to open issues when test failures occur so we can catch them early and investigate

The main problem I'm seeing is that failures can be for one of three reasons:

1. New code in Mocha is bad
2. New code in Node.js is bad
3. Test code in Mocha has been flaky and gone unnoticed

I can work to resolve `#3` in this one but it's looking like a lot of our current problems are actually due to `#2`. Separating workflow will help us eliminate cause `#1` much quicker :)

**Comment by JoshuaKGoldberg** [comment]
My vote is `#1` for now. If we are often impacted by changes in new versions of Node.js then pinning seems very appropriate to me. Once we're able to automatically update dependencies (#5055) it'd be nice to have granular PR tracking for _"this is when we started using version XYZ of Node.js"_. And we can always have Node.js update PRs run tests >1x for extra confidence.

**Comment by mark-wiemer** [comment]
Still have flaky issues on Windows 20.18.3

**Comment by mark-wiemer** [comment]
Tests pass locally 10/10 on my Windows machine with Node 20.18.3. Will think on this and run it a bunch in a GitHub workflow as well.

**Comment by mark-wiemer** [comment]
Closing as completed, tests passed very 10/10 times in GH as well!

![](https://github.com/user-attachments/assets/9deb9ba0-4c89-49ef-934b-bfa9140cc624)

**Comment by JoshuaKGoldberg** [comment]
![Colin Jost in SNL Weekly Update saying "well, that's a relief"](https://github.com/user-attachments/assets/32b522f0-88b6-4d24-8b72-9ea1eeac29af)
