### ISSUE TITLE
🐛 Bug: Eleventy template builds crash with 'unexpected token at ": string, msg..."'

### ISSUE THREAD

**Issue by marjys** [mochajs/mocha#5115]
### Bug Report Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [ ] I want to provide a PR to resolve this

### Expected

Running `npm start docs` should build the docs without errors.

### Actual

The following error from Eleventy is popping up:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering liquid template ./docs/api/reporters_base.js.html (via TemplateContentRenderError)
[11ty] 2. unexpected token at ": string, msg...", file:./docs/api/reporters_base.js.html, line:273, col:12 (via ParseError)
[11ty] 3. unexpected token at ": string, msg..." (via AssertionError)
[11ty]
[11ty] Original error stack trace: AssertionError: unexpected token at ": string, msg..."
[11ty]     at new AssertionError (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:1201:28)
[11ty]     at assert (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:1236:15)
[11ty]     at Tokenizer.readFilter (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:2245:9)
[11ty]     at Tokenizer.readFilters (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:2234:31)
[11ty]     at new Value (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:2788:34)
[11ty]     at new Output (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:4472:23)
[11ty]     at Parser.parseToken (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:4541:24)
[11ty]     at Parser.parseTokens (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:4531:33)
[11ty]     at Parser.parse (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:4525:21)
[11ty]     at Liquid.parse (/Users/marjorie/Documents/github/courses/mocha/node_modules/liquidjs/dist/liquid.node.cjs.js:4663:28)
[11ty] Benchmark   3054ms  73%     1× (Data) `./docs/_data/supporters.js`
[11ty] Benchmark    380ms   9%     1× (Data) `./docs/_data/toc.js`
[11ty] Wrote 0 files in 4.06 seconds (v1.0.2)
The script called "doc" which runs "nps docs.clean && nps docs.api && eleventy && nps docs.linkcheck" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```
![Screenshot 2024-03-07 at 11 29 39](https://github.com/mochajs/mocha/assets/18129844/5fa20062-5f83-4e32-91f5-ec3fcd260e53)

### Minimal, Reproducible Example

This error happens when building the docs by running `npm start docs`

### Versions

mocha version: 10.3.0
node version: v21.7.0

**Comment by JoshuaKGoldberg** [comment]
😄 looks like @Lcsk might be working on a fix already?
