### ISSUE TITLE
🚀 Feature: if loading a file as CJS and ESM both fail, display both errors instead of just ESM

### ISSUE THREAD

**Issue by jedwards1211** [mochajs/mocha#5235]
### Feature Request Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I want to provide a PR to resolve this

### Overview

Ever since `chai` v5 dropped support for CJS, we get errors like this when we accidentally install chai 5+:

```
$ mocha 

 Exception during run: TypeError: Unknown file extension ".ts" for /Users/user/src/battalion/storage-site-sim/src/__tests__/SeededRNG.test.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:141:22)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:7)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:45)
    at link (node:internal/modules/esm/module_job:76:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

This threw us for a loop at first, because normally our tests work fine with `@babel/register` handling `.ts` files.

What's happening is first Mocha tries to load our file as CJS, which make it as far as `require('chai')` which fails with `ERROR_REQUIRE_ESM`.  Then Mocha tries to load our file as ESM instead, which triggers the above error.

### Suggested Solution

If Mocha would print out the error from loading our file as CJS in addition to the above error, we would have seen what caused the problem more quickly.

### Alternatives

I've thought about adding code to our toolchain to check for chai v5+ and explicitly warn...but this same issue could occur with any package we're using in tests that drops CJS support

I guess another solution would be a mocharc option to force Mocha to only try one of CJS or ESM, not both.

I can't just put `type: "commonjs"` in my `package.json` because I made my toolchain run tests in CJS mode with `@babel/register`, and then in ESM mode with `babel-register-esm`, since I'm transpiling my TypeScript source to both CJS and ESM for publishing.

**Comment by JoshuaKGoldberg** [comment]
This is tricky. If both CJS and ESM fail to import the file because it actually doesn't exist, then displaying both errors would be extra noise for users. If this were to be implemented it would probably need some kind of heuristic for determining whether the errors are different enough to both warrant being displayed. I don't know how straightforward that would be to implement.

Would you be able to post a [minimum reproduction project](https://antfu.me/posts/why-reproductions-are-required#reproducible-projects-or-playgrounds) we could look at to better understand this?

**Comment by jedwards1211** [comment]
Okay I'll work on making a repro soon

**Comment by jedwards1211** [comment]
I don't think the extra noise would be worse, because what it currently displays is very confusing at first in a situation like this.

Theoretically the heuristic could be whether ERR_REQUIRE_ESM came from the user's own project files or from node_modules

**Comment by JoshuaKGoldberg** [comment]
👋 just checking in @jedwards1211, any luck on a repro?

**Comment by jedwards1211** [comment]
Sorry I forgot about that, here you go: https://github.com/jedwards1211/mocha-cjs-esm

**Comment by JoshuaKGoldberg** [comment]
Ok thanks - I got a chance to look at the repro and it makes sense. The heuristic for which error is thrown comes from #4803 -> #4807:

The `requireErr` caught from the CJS require is the `throw err` on line 73 here:

https://github.com/mochajs/mocha/blob/73bb81904fa017fc474973ce9b1e8fc325709142/lib/nodejs/esm-utils.js#L41-L80

```plaintext
requireErr: Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/josh/repos/mocha-cjs-esm/node_modules/.pnpm/chai@5.1.2/node_modules/chai/chai.js from /Users/josh/repos/mocha-cjs-esm/test.ts not supported.
  Instead change the require of chai.js in /Users/josh/repos/mocha-cjs-esm/test.ts to a dynamic import() which is available in all CommonJS modules.
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at Object.<anonymous> (/Users/josh/repos/mocha-cjs-esm/test.ts:3:13)
      at Module._compile (/Users/josh/repos/mocha-cjs-esm/node_modules/.pnpm/pirates@4.0.6/node_modules/pirates/lib/index.js:117:24)
      at Object.newLoader [as .ts] (/Users/josh/repos/mocha-cjs-esm/node_modules/.pnpm/pirates@4.0.6/node_modules/pirates/lib/index.js:121:7)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at exports.requireOrImport (/Users/josh/repos/mocha/lib/nodejs/esm-utils.js:55:16)
      at async exports.loadFilesAsync (/Users/josh/repos/mocha/lib/nodejs/esm-utils.js:103:20)
      at async singleRun (/Users/josh/repos/mocha/lib/cli/run-helpers.js:162:3)
      at async exports.handler (/Users/josh/repos/mocha/lib/cli/run.js:375:5) {
    code: 'ERR_REQUIRE_ESM'
```

I was able to fix this issue locally by having it `throw requireErr` instead of `throw err` when `err.code === 'ERR_UNKNOWN_FILE_EXTENSION'`. But I haven't dug into the CJS/ESM logic enough to know if that's sensible.

Accepting PRs, with the caveat that fixing this will require being able to explain why the fix is correct. [Chesterton's Fence](https://en.wiktionary.org/wiki/Chesterton%27s_fence) applies. 🙂

**Comment by giltayar** [comment]
This makes sense.

**Comment by giltayar** [comment]
But maybe a better solution would be to remove the use of `require`? Just use `import` to import both ESM and CJS. Especially since v23, `require` DOES work with ESM, but not _all_ ESM (not those with top-level await). I did this "require and then import" because the implementation of ESM in Node.js was just at the beginning and I didn't want to interfere with the code path of 99.9999% of the users at that time that used CJS test files.

But we're in 2024. I would just use `import` and this may probably remove all the weirdness here. It's a risky move, but I believe a good one.

**Comment by jedwards1211** [comment]
@giltayar using `import` for everyone would break all users who are using CJS module loader looks like `@babel/register` or `ts-node/register`

**Comment by jedwards1211** [comment]
I mean, it would probably end up calling `require` and going through the CJS module loader if it gets to that point, but it won't get to that point for file extensions like `.ts` that don't get resolved by the ESM loader without hooks installed

**Comment by JoshuaKGoldberg** [comment]
That's a really interesting idea @giltayar. If all test cases pass, then that's lovely.

In fact, I tried the latest Node 23.5.0, and the test case repro no longer fails! 

```plaintext
$ node --version
v23.5.0
$ pnpm test

> mocha-cjs-esm@1.0.0 test /Users/josh/repos/mocha-cjs-esm
> mocha



  ✔ testcase

  1 passing (1ms)
```

https://nodejs.org/docs/latest/api/modules.html#loading-ecmascript-modules-using-require: in 22.12.0 and 23.5.0, `require` can load ESM by default.

So, I bet we can actually:

1. Mark this as 'aged away' in that the newest Node versions no longer have the crash
2. Once Mocha drops support for <22.12.0 -which will be several years from now- consider investigating removing `require()` altogether

Thoughts?

**Comment by jedwards1211** [comment]
Well it should still be an issue for no. 1 in the newest versions of Node.
I think you would at least need to configure the ESM loader to accept `.ts`/`.tsx` extensions, even if it's ultimately loading those files as CJS.

**Comment by JoshuaKGoldberg** [comment]
Gotcha. For 1, I'm not following how the difference between JS and TS users will be relevant in the newest versions of Node when using `--import`. If the difference is that both CJS and ESM can generally load ESM now, it shouldn't matter whether the source is JS or TS, right?

Supporting evidence: I pushed up https://github.com/JoshuaKGoldberg/mocha-examples/tree/use-chai-in-typescript-examples using `chai` in TypeScript-authored tests:

* `typescript`: is separately broken 🙃, ignore [^1]
* [typescript-babel](https://github.com/JoshuaKGoldberg/mocha-examples/tree/use-chai-in-typescript-examples/packages/typescript-babel): fails on Node 20, passes on 23.5.0
* [typescript-ts-node-esm-loader](https://github.com/JoshuaKGoldberg/mocha-examples/tree/use-chai-in-typescript-examples/packages/typescript-ts-node-esm-loader): passes in Node 20 and 23.5.0
* [typescript-tsx-esm-import](https://github.com/JoshuaKGoldberg/mocha-examples/tree/use-chai-in-typescript-examples/packages/typescript-tsx-esm-import): passes in Node 20 and 23.5.0

[^1]: https://github.com/mochajs/mocha-examples/issues/105

**Comment by jedwards1211** [comment]
If the user has to use CJS for whatever reason, and they're using something like `@babel/register` so that they can `require` TS files directly and calling `mocha` with `extensions`, then you would be trying to `import` a TS file, but the ESM loader won't know what to do with TS extensions.

**Comment by jedwards1211** [comment]
In the `typescript-babel` example, mocha is `require`ing the TS files.  You're talking about making mocha `import` the TS files instead, even though they are CJS, right?  The ESM loader would complain that the .ts file extension is invalid, unless I'm misunderstanding something

**Comment by jedwards1211** [comment]
Oh I didn't realize Node 23 supports .ts by default now.

However, it doesn't support .tsx, so the `typescript-babel` config would still be broken for tsx projects.

**Comment by JoshuaKGoldberg** [comment]
Coming back to this: I've thought about it a bunch and I'm not convinced that it'll be worth the code complexity & effort to special-case this error long-term. Now that the bug only applies to non-standard extensions such as `.tsx`, the expected user benefit is much smaller. And as Gil notes the whole system around `import`/`require` should eventually be overhauled.

If someone else in @mochajs/maintenance-crew wants to champion this work I won't get in the way at all. But personally I just don't see it as worth it.

**Comment by JoshuaKGoldberg** [comment]
>2 months and no comment - I'm going to go ahead and close this out as a relatively niche edge case. If someone feels strongly that this is the wrong move, please do post here explaining why. We can always reopen. Cheers! 🤎

**Comment by JoshuaKGoldberg** [comment]
#5393 was posted with a similar issue. Fun. Its proposal was a bit different: to still only show one error, and be a bit more intelligent about _which_ one error to show. I marked that one as accepting PRs. Cheers!

**Comment by mark-wiemer** [comment]
Reopening per the recent mention (https://github.com/mochajs/mocha/issues/5792#issuecomment-4107044102). In short, something like this is probably nice, in my book, given the wide variety of error messages and ongoing changes to how Node handles these things. We can keep trying to catch 'em all, but until then, we should have a nice fallback for confused users.

**Comment by mark-wiemer** [comment]
@mochajs/maintenance-crew can we mark this as accepting PRs?
