### ISSUE TITLE
🐛 Bug: Tests pass without running after uncaught exception

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha#5251]
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [x] I want to provide a PR to resolve this

### Expected

If an uncaught exception occurs, I would think Mocha should report a failure and continue running subsequent tests.

### Actual

If a test throws an error inside a `process.nextTick` callback, Mocha correctly reports that test failing, but then doesn't run subsequent tests. It reports them as passed.

For example, in the MRE, there are three tests -`a`, `b`, and `c`- and `b` throws an error inside `process.nextTick`. The report is:

```plaintext
  a
    ✔ should pass

  b
    ✔ should pass, then fail
    1) should pass, then fail


  2 passing (3ms)
  1 failing

  1) b
       should pass, then fail:
     Uncaught Error: uncaught!!
      at /Users/josh/repos/repros/test/example-b.js:4:15
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### Minimal, Reproducible Example

https://github.com/JoshuaKGoldberg/repros/tree/mocha-skip-test-after-uncaught

```shell
git clone https://github.com/JoshuaKGoldberg/repros -b mocha-skip-test-after-uncaught
npm i
npx mocha
```

### Versions

* Mocha: 10.8.2
* Node: 18, 20, and 22

### Additional Info

Discovered in #5250 -> 6b5ff680716f2a67d7783bdb0874054841bdd5ce.

Somewhat similar-looking to #5184 but not the same.

**Comment by wnghdcjfe** [comment]
Hello@JoshuaKGoldberg 
I think this error can be resolved in the following two ways. 
Are you talking about the part where the fail should appear when an error in process.nextTick occurs?
1. try - catch
```js
describe('b', function() {
  it('should pass, then fail', function(done) {
    process.nextTick(function() {
      try {
        throw new Error('uncaught!!');
      } catch (err) {
        done(err); // Mocha에 에러를 알림
      }
    });
  });
}); 
```
![Image](https://github.com/user-attachments/assets/8db70b2a-db42-476c-be78-27eb03fa80f1)

2. promise
```js
describe('b', function() {
  it('should pass, then fail', function() {
    return new Promise((resolve, reject) => {
      process.nextTick(function() {
        reject(new Error('uncaught!!'));  
      });
    });
  });
});

```

![Image](https://github.com/user-attachments/assets/c5b9190e-352c-46df-8ac0-eeea1371f61f)

**Comment by JoshuaKGoldberg** [comment]
I don't follow what you're asking, sorry. But if you can send a PR that would help me understand :)

**Comment by wnghdcjfe** [comment]
Okay. I'll  PR it later. 
First of all, I found that it occur "pass" in beforeEach hook.  
![Image](https://github.com/user-attachments/assets/ea98ba3b-8c4b-43fe-ae5f-c181966403c9)

If the code is error-handling well, it should appear as follows.
![Image](https://github.com/user-attachments/assets/44f3ef06-3ff0-4ec6-a0d4-9962821e1547)

**Comment by wnghdcjfe** [comment]
Hello sorry for leaving a reply so late, I try to do it every weekend but it's not easy haha


In my opinion, the callback of process.nextTick() runs asynchronously, because there is no logic with the parameter "done"  

For example 
The next code will be error-handled normally. 
```
    it('should pass, then fail', function(done) {
        process.nextTick(function() { 
            throw new Error('uncaught!!'); 
        });
      });
```


So, how should we solve this? 
Here's how I'm currently thinking. 

let's see this function.
```
Runable(title, fn) 
``` 
If the parameter 'done' is included, the fn.length becomes 1 and it is recognized as an asynchronous function. 
Therefore, when "the nextTick " is included in fn, it would be better to check whether there is 'done' in it and add 'done' appropriately. Is it okay to proceed like this? 

For example 
runnable.js
```
  if (this.fn && typeof this.fn.call !== 'function') {
    done(
      new TypeError(
        'A runnable must be passed a function as its second argument.'
      )
    );
    return;
  }
   
  if (this.fn.toString().includes('process.nextTick') && fn.length === 0) {
    this.async = 1;
  } 

  // explicit async with `done` argument
  if (this.async) {
    this.resetTimeout();
```

https://github.com/mochajs/mocha/blob/main/lib/runnable.js#L326

@JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
That seems reasonable at first glance. But it's hard to say without looking at a PR. I say: go for it, let's try it out! 🚀

**Comment by alxndrsn** [comment]
> ### Actual
> 
> If a test throws an error inside a `process.nextTick` callback, Mocha correctly reports that test failing, but then doesn't run subsequent tests. It reports them as passed.

I think this section, and the current issue title, are slightly mis-stating the problem: I don't think that subsequent tests are reported as passed, I think:

1. subsequent tests are not run at all, and
2. the failing test is reported as failing twice

A longer set of subsequent tests can demonstrate this more clearly, e.g. this longer suite will fail with an identical report to the original repro:

```js
describe("a", function () {
  it("should pass", function () {
  });
});

describe('b', function() {
  it('should pass, then fail', function() {
    process.nextTick(function() {
      throw new Error('uncaught!!');
    });
  });
});

describe("c", function () {
  it("should fail 1", function () {
    throw new Error("Oh no 1!");
  });
  it("should fail 2", function () {
    throw new Error("Oh no 1!");
  });
  it("should fail 3", function () {
    throw new Error("Oh no 1!");
  });
  it("should fail 4", function () {
    throw new Error("Oh no 1!");
  });
  it("should fail 5", function () {
    throw new Error("Oh no 1!");
  });
  it("should fail 6", function () {
    throw new Error("Oh no 1!");
  });
});
```

**Comment by alxndrsn** [comment]
...although maybe there is a bigger issue?

Consider the following:

```js
describe('unhandled async failure within a test', () => {
  it('should pass 1', () => {});

  it('should pass, then fail', () => {
    setTimeout(() => { throw new Error('uncaught!!'); }, 100);
  });

  it('should pass after some time 1', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 2', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 3', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 4', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 5', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 6', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 7', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 8', () => new Promise(resolve => setTimeout(resolve, 50)));
  it('should pass after some time 9', () => new Promise(resolve => setTimeout(resolve, 50)));
});
```

For me, this fails like so:

```sh
$ yarn mocha test.js 


  unhandled async failure within a test
    ✔ should pass 1
    ✔ should pass, then fail
    ✔ should pass after some time 1 (51ms)
    1) should pass after some time 2
    2) should pass after some time 2
    ✔ should pass after some time 3 (50ms)
    ✔ should pass after some time 4 (50ms)
    ✔ should pass after some time 5 (51ms)
    ✔ should pass after some time 6 (50ms)
    ✔ should pass after some time 7 (50ms)
    ✔ should pass after some time 8 (50ms)
    ✔ should pass after some time 9 (50ms)


  10 passing (461ms)
  2 failing

  1) unhandled async failure within a test
       should pass after some time 2:
     Uncaught Error: uncaught!!
      at Timeout._onTimeout (test.js:5:30)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)

  2) unhandled async failure within a test
       should pass after some time 2:
     Error: done() called multiple times in test <unhandled async failure within a test should pass after some time 2> of file test.js
```

This failure looks incorrect and very misleading.  It seems like mocha is ascribing the unhandled async failure to whatever test happens to be running at the time the async failure happens.  Personally I'd expect that either

1. mocha just errors out the whole test suite if there's an unhandled promise rejection somewhere, and states that it doesn't know what's going on, or
2. somehow mocha keeps track of which test was running when a promise chain was initiated, so that it can point the user in the right direction when an unhandled rejection occurs

Even in case 2, short-circuiting the whole suite seems like a more helpful default than continuing, as whatever was happening in the background may be affecting subsequent tests.

**Comment by mark-wiemer** [comment]
I'll put this on my personal backlog, but I'm still catching up from notifications today. Just want to say @alxndrsn I appreciate your insights and hopefully we can fix this bug soon :)

**Comment by mostafaNazari702** [comment]
You guys are making it complicated for no reason, just track which runnable owns each async context then _uncaught can attribute a stray error to the test that scheduled it, mark that test failed, and keep running and you get no mis-attribution, so no need to bail, ez. Falls back to today's behavior when attribution isn't available (browser, or synthetic calls).

**Comment by mostafaNazari702** [comment]
Backing PR is stale. Will work on this.

**Comment by mostafaNazari702** [comment]
@mark-wiemer #6226 fixes the half this is titled after but not the one @alxndrsn raised (error gets blamed on whatever test is running and a false "done() called multiple times"). Different branch in _uncaught so it cant.

I will take that other half as a follow up once #6226 lands. It says "Fixes #5251" so merging will close this. Would be nice if you maybe edit the PR's body and replace with "Progress on #..."

**Comment by mark-wiemer** [comment]
@mostafaNazari702 that might be a little too succinct--which "half" are you referring to and what exactly is the "one alxndrsn raised"? Can you create two repros for better reference?

**Comment by mostafaNazari702** [comment]
> Can you create two repros for better reference?

Two repros against my main at d59467a8, for now.

A (we will call it that) is what this issue is titled after. A test passes then throws async between tests. Everything after it is skipped and nothing says so.

```js
describe("first", function () {
  it("passes, then throws async", function () {
    process.nextTick(function () {
      throw new Error("boom");
    });
  });
});

describe("second", function () {
  it("should run and fail", function () {
    throw new Error("I never ran");
  });
});
```

```log
$ npm test

  first
    ✔ passes, then throws async
    1) passes, then throws async

  1 passing (1ms)
  1 failing

  1) first
       passes, then throws async:
     Uncaught Error: boom
      at test/hello.spec.js:4:13
      at process.processTicksAndRejections (node:internal/process/task_queues:85:11)

Exit code 1
Mocha 12.0.1
Node v24.17.0
```

"second" never ran, and the summary gives no hint of it.

B: what @alxndrsn mentioned. Same async throw but it lands while a different test is still in progress. The wrong test gets blamed and the real `done()` then takes the process down.

```js
describe("suite", function () {
  it("passes, then throws async", function () {
    setTimeout(function () {
      throw new Error("boom");
    }, 50);
  });

  it("innocent bystander", function () {
    return new Promise(function (resolve) {
      setTimeout(resolve, 200);
    });
  });
});
```

```log
$ npm test

  suite
    ✔ passes, then throws async
    1) innocent bystander

  1 passing (59ms)
  1 failing

  1) suite
       innocent bystander:
     Uncaught Error: boom
      at Timeout._onTimeout (test/hello.spec.js:4:13)

lib/runner.js:1110
    throw err;
    ^

Error: done() called multiple times in test <suite innocent bystander>
  code: 'ERR_MOCHA_MULTIPLE_DONE'

Exit code 7
Mocha 12.0.1
Node v24.17.0
```

The test that actually threw is green the one that didnt is red and the process crashes after the summary have already printed.

They take different branches in `_uncaught` which is why one fix can not cover both. With DEBUG=mocha:runner:

```log
A: uncaught(): Runnable has already passed; bailing gracefully
B: uncaught(): forcing Runnable to complete with Error
   uncaught(): throwing after run has completed!
```

i checked #6226 against both, A is fixed and our "second" runs and it reports 2 failing.

B is unchanged and still exit 7. B is the half i want to follow up on.
