### ISSUE TITLE
🚀 Feature: Support running with node --frozen-intrinsics

### ISSUE THREAD

**Issue by kevinoid** [mochajs/mocha#5252]
### Feature Request Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I want to provide a PR to resolve this

### Overview

When node is invoked with the experimental [--frozen-intrinsics flag](https://nodejs.org/api/cli.html#--frozen-intrinsics) (added in Node.js 11.12 by https://github.com/nodejs/node/pull/25685) it causes mocha to exit due to an uncaught `TypeError` from attempting to set `Error.stackTraceLimit`:

    /path/to/node_modules/mocha/lib/cli/cli.js:45
      Error.stackTraceLimit = Infinity; // configurable via --stack-trace-limit?
                            ^
    
    TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot assign to read only property 'stackTraceLimit' of function 'function Error() { [native code] }'
        at exports.main (/path/to/node_modules/mocha/lib/cli/cli.js:45:25)
        at Object.<anonymous> (/path/to/node_modules/mocha/bin/mocha.js:141:29)
        at Module._compile (node:internal/modules/cjs/loader:1469:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Module._load (node:internal/modules/cjs/loader:1104:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
        at node:internal/main/run_main_module:28:49

It would be nice if mocha supported running under `--frozen-intrinsics` for testing code under this flag.

### Suggested Solution

Wrapping

https://github.com/mochajs/mocha/blob/d3b2c386db74f0d448c7381097381dedb1c996f2/lib/cli/cli.js#L45

in `try-catch` appears to be sufficient.

### Alternatives

Not supporting running under `--frozen-intrinsics`? (yet)

**Comment by JoshuaKGoldberg** [comment]
TIL about `--frozen-intrinsics`, what an interesting flag! Yes, this seems like a straightforward bug. Thank you!

**Comment by TG199** [comment]
Hi @JoshuaKGoldberg,

I've been looking into implementing the fix for the `--frozen-intrinsics` support, and I have a few clarifying questions:

Given that `--frozen-intrinsics` is still an experimental Node.js flag, what are your thoughts on adding support for it? Specifically:
   - Do you see value in supporting an experimental feature?
   - Are there specific use cases in Mocha's ecosystem that would benefit from this?

**Comment by TG199** [comment]
Got it!

**Comment by JoshuaKGoldberg** [comment]
🙌 Good news, I tried this again with the latest Mocha and it's no longer an issue! #5254 added a `try`/`catch` around the problematic line:

https://github.com/mochajs/mocha/blob/945d6e3bf5a9de19c3aa26fbdac966a721006b58/lib/cli/cli.js#L43-L47

I can confirm locally that running with `--frozen-intrinsics` on https://github.com/eslint/eslint's Mocha tests works. 

Therefore: `mocha>=11.0.2` should work with Node.js frozen intrinsics. If someone sees that not to be the case, please file a new issue with a full reproduction we can take a look at. Cheers! 🤎
