### ISSUE TITLE
Add test file location on timeout exceeded test failure

### ISSUE THREAD

**Issue by rngadam** [mochajs/mocha#627]
This is a problem when running a directory of multiple tests.

Test failures on assertion or exception give the correct file from the stack trace.

A timeout however leaves us grepping for the correct file:

```
  2) lophilo watch watching...:
     Error: timeout of 2000ms exceeded
      at Object.<anonymous> (/home/rngadam/local/node/lib/node_modules/mocha/lib/runnable.js:158:14)
      at Timer.list.ontimeout (timers.js:101:19
```

**Comment by BetaKevin** [comment]
:+1:
