### ISSUE TITLE
Mocha exists after the first test failure when it is used programmatically

### ISSUE THREAD

**Issue by aneshlya** [mochajs/mocha#728]
I am trying to run mocha programmatically.
The code of runner is the following:

var Mocha = require("mocha");
var mocha = new Mocha();
mocha.reporter('list').ui('bdd').ignoreLeaks();
//Here the serv_paths variable is defined, -- this code snippet is skipped
// ...

serv_paths.forEach(function(file){
	mocha.addFile(file);
        });
var runner = mocha.run(function(){ });

The tests are very simple:

var assert = require("assert");

describe('True!', function(){
	it('true = true', function(){
		assert.equal(true, true);
	});

	it('true = false', function(){
		assert.equal(true, false);
	});

	it('true = false -- second', function(){
		assert.equal(true, false);
	});

	it('true = true', function(){
		assert.equal(true, true);
	});
});

The mocha runs tests before the first failure and then exits and ignore other tests. 

The output is:
[Jan 21 04:57:23]   ✓ True! true = true: 0ms
[Jan 21 04:57:23]   1) True! true = false
[Jan 21 04:57:23]   ✖ 1 of 4 tests failed:
[Jan 21 04:57:23]   1) True! true = false:
 AssertionError: true == false
      at Context.<anonymous> (/home/ubuntu/project/plugins-server/cloud9.ide.help/test_test.js:14:10)
      at Test.run (/home/ubuntu/project/node_modules/mocha/lib/runnable.js:213:32)
      at Runner.runTest (/home/ubuntu/project/node_modules/mocha/lib/runner.js:343:10)
      at /home/ubuntu/project/node_modules/mocha/lib/runner.js:389:12
      at next (/home/ubuntu/project/node_modules/mocha/lib/runner.js:269:14)
      at /home/ubuntu/project/node_modules/mocha/lib/runner.js:278:7
      at next (/home/ubuntu/project/node_modules/mocha/lib/runner.js:226:23)
      at Array.<anonymous> (/home/ubuntu/project/node_modules/mocha/lib/runner.js:246:5)
      at EventEmitter._tickCallback (node.js:190:38)

Is there way to force Mocha run all tests?

**Comment by danielstjules** [comment]
Closing since this isn't a problem with the latest version of mocha Both failures are reported. :)

``` javascript
// -------------------------------------------------------------------------
// example.js
// -------------------------------------------------------------------------
var Mocha = require("mocha");
var mocha = new Mocha();
mocha.reporter('list').ui('bdd').ignoreLeaks();

mocha.addFile('./test.js');
var runner = mocha.run(function(){ });

// -------------------------------------------------------------------------
// test.js
// -------------------------------------------------------------------------
var assert = require("assert");

describe('True!', function(){
  it('true = true', function(){
    assert.equal(true, true);
  });

  it('true = false', function(){
    assert.equal(true, false);
  });

  it('true = false -- second', function(){
    assert.equal(true, false);
  });

  it('true = true', function(){
    assert.equal(true, true);
  });
});

// -------------------------------------------------------------------------
// Output
// -------------------------------------------------------------------------
$ node example.js

  ․ True! true = true: 0ms
  1) True! true = false
  2) True! true = false -- second
  ․ True! true = true: 0ms

  2 passing (6ms)
  2 failing

  1) True! true = false:
     AssertionError: true == false
      at Context.<anonymous> (/Users/danielstjules/Desktop/test.js:9:12)
      at callFn (/Users/danielstjules/Desktop/node_modules/mocha/lib/runnable.js:266:21)
      at Test.Runnable.run (/Users/danielstjules/Desktop/node_modules/mocha/lib/runnable.js:259:7)
      at Runner.runTest (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:387:10)
      at /Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:470:12
      at next (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:312:14)
      at /Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:322:7
      at next (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:257:23)
      at Object._onImmediate (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

  2) True! true = false -- second:
     AssertionError: true == false
      at Context.<anonymous> (/Users/danielstjules/Desktop/test.js:13:12)
      at callFn (/Users/danielstjules/Desktop/node_modules/mocha/lib/runnable.js:266:21)
      at Test.Runnable.run (/Users/danielstjules/Desktop/node_modules/mocha/lib/runnable.js:259:7)
      at Runner.runTest (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:387:10)
      at /Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:470:12
      at next (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:312:14)
      at /Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:322:7
      at next (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:257:23)
      at Object._onImmediate (/Users/danielstjules/Desktop/node_modules/mocha/lib/runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
```
