### ISSUE TITLE
When an assertion fails, mocha first checks for globals

### ISSUE THREAD

**Issue by vvo** [mochajs/mocha#731]
In a browser environment, using mocha latest, expect.js:

```js
(function (global) {
    describe('a foo', function () {

        it('should be bar', function () {
            global.foo = {};
            expect(global.foo).to.be.a(Function);
            delete global.foo
        });
    });
}(this));
```

Results in:

``` text
Error: global leak detected: foo
    at Runner.checkGlobals (http://localhost:8080/node_modules/mocha/mocha.js:4230:21)
    at Runner.<anonymous> (http://localhost:8080/node_modules/mocha/mocha.js:4115:44)
[...]
```

This is very tricky because the actual error is that the expect failed and so the delete global.foo failed.

Right?

**Comment by boneskull** [comment]
well, the actual error is that there was a leak, because the leak check comes before any error handling.  I don't see this as an issue
