### ISSUE TITLE
HTML runner doesn't display error for multiple done calls

### ISSUE THREAD

**Issue by Met48** [mochajs/mocha#816]
Consider this suite:

```javascript
describe("Something", function () {
  it("should one", function (done) {
    done();
    done();
  });
  it("should two", function () { });
});
```

In the html runner, it will say "passes: 2 failures: 1" but not show a failure in the test results. This means no stack trace is displayed and it's more difficult to track down which test failed.

The second test is only there to prevent Mocha from immediately exiting after the first `done` call (see discussion in #216)

**Comment by danielstjules** [comment]
Closing since this has been fixed. :) Here's the output of your example:

``` javascript
$ ./bin/mocha test.js


  ․․․

  2 passing (4ms)
  1 failing

  1) Something should one:
     Error: done() called multiple times
      at Test.Runnable (/Users/danielstjules/git/mocha/lib/runnable.js:50:17)
      at new Test (/Users/danielstjules/git/mocha/lib/test.js:22:12)
      at context.it.context.specify (/Users/danielstjules/git/mocha/lib/interfaces/bdd.js:87:18)
      at Suite.<anonymous> (/Users/danielstjules/git/mocha/test.js:2:3)
      at context.describe.context.context (/Users/danielstjules/git/mocha/lib/interfaces/bdd.js:49:10)
      at Object.<anonymous> (/Users/danielstjules/git/mocha/test.js:1:63)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /Users/danielstjules/git/mocha/lib/mocha.js:187:27
      at Array.forEach (native)
      at Mocha.loadFiles (/Users/danielstjules/git/mocha/lib/mocha.js:184:14)
      at Mocha.run (/Users/danielstjules/git/mocha/lib/mocha.js:405:31)
      at Object.<anonymous> (/Users/danielstjules/git/mocha/bin/_mocha:405:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:901:3
```
