### ISSUE TITLE
Unhalted exception: RangeError: Invalid array length (failing code attached)

### ISSUE THREAD

**Issue by mcharytoniuk** [mochajs/mocha#998]
Hello,

while developing node package I ran into an issue with "mocha" (Windows 7  with node v0.10.18). 

```
c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\reporters\spec.js:32
    return Array(indents).join('  ')
           ^
RangeError: Invalid array length
    at indent (c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\reporters\spec.js:32:12)
    at Runner.<anonymous> (c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\reporters\spec.js:50:26)

    at Runner.EventEmitter.emit (events.js:95:17)
    at next (c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:398:10)
    at next (c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:281:14)
    at c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:290:7
    at next (c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:234:23)
    at Object._onImmediate (c:\Users\mcharytoniuk\workspace\jsloader\flow-inspector\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:258:5)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

The affected code is here (I am going to leave this branch there until this issue is resolved):
https://github.com/jsloader/flow-inspector/tree/mocha-bug

To reproduce this issue do:

```
$ npm install configuration-processor
$ cd node_modules/configuration-processor
$ git checkout mocha-bug
$ grunt test
```

Then mocha should fail with this unhalted error.

Best wishes,
Mateusz

**Comment by zekenie** [comment]
I'm experiencing this issue as well

**Comment by dasilvacontin** [comment]
I can't find OP's code anymore. Can someone post a reproducible case? Thanks.

**Comment by zekenie** [comment]
I'm testing a mongoose model

Here's the model

```javascript
'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var CohortSchema = new Schema({
  name: {type: String, required: true},
  start: {type: Date, required:true},
  workshops: [{ type: Schema.Types.ObjectId, ref: "Workshop"}],
  defaultRoles: [String]
});

CohortSchema.methods.addWorkshop = function(wid,cb) {
  this.workshops.addToSet(wid._id || wid);
  this.save(cb);
}

CohortSchema.methods.removeWorkshop = function(wid,cb) {
  this.workshops.pull(wid._id || wid)
  this.save(cb);
}

CohortSchema.methods.addStudent = function(s,cb) {
  var self = this
  this.students.addToSet(s._id);
  this.save(function(err,cohort) {
    self.defaultRoles.forEach(s.addRole.bind(s))
    s.cohort = cohort;
    s.save(cb);
  })
}

CohortSchema.plugin(require('../studentGroup/studentGroup.plugin.js'));

module.exports = mongoose.model('Cohort', CohortSchema);
```

here's the spec

```javascript
'use strict';
var should = require('should')
var mongoose = require('mongoose')
var Cohort = require('./cohort.model')
var Workshop = require('../workshop/workshop.model')

describe('Cohort Model', function() {
  var c

  describe('validations', function() {
    var err
    beforeEach(function(done) {
      c = new Cohort()
      c.validate(function(_err) {
        err = _err
        done()
      })
    })

    it('errors without name', function() {
      err.errors.should.have.property('name');
    })

    it('errors without start', function() {
      err.errors.should.have.property('start');
    })
  })

  describe('methods',function() {
    describe('addWorkshop', function() {

      it('adds id to workshop array when passed workshop doc', function() {
        var w = new Workshop();
        c.addWorkshop(w);
        c.workshops.should.containEql(w._id);
      });

      it('adds id to workshop array when passed workshop id', function() {
        var w = new Workshop();
        c.addWorkshop(w._id);
        c.workshops.should.containEql(w._id);
      });

    });

    describe('addWorkshop', function() {});
    describe('addStudent', function() {});
  });
});
```

**Comment by boneskull** [comment]
@zekenie thanks

**Comment by boneskull** [comment]
@zekenie do you have a stack trace? what happens when, instead of using the `beforeEach` hook, you copy the same code into both of its tests?

**Comment by zekenie** [comment]
That didn't really work. But, I got the spec to pass by changing the model a bit. Instead of calling save in the model methods, I rely on the user of the method to save after. For some reason that fixed the mocha issue. Perhaps it was because my spec wasn't passing in a callback? I can't quite piece together why, though. 

I think Mocha is determining the number of spaces in the output indentation by creating an array of `n` length and joining that array on ` `. But for some reason a negative number is getting passed into the Array constructor.

Here's the stacktrack:

```
/Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/reporters/spec.js:33
    return Array(indents).join('  ')
           ^
RangeError: Invalid array length
    at indent (/Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/reporters/spec.js:33:12)
    at Runner.<anonymous> (/Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/reporters/spec.js:42:41)
    at Runner.emit (events.js:117:20)
    at Runner.runSuite (/Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:491:8)
    at next (/Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:511:10)
    at /Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:518:7
    at next (/Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:247:23)
    at Object._onImmediate (/Users/zekenierenberg/newlearn/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by dasilvacontin** [comment]
Looks like `suite end` is happening more often than `suite`, hmm.

**Comment by ergdev** [comment]
This is also happening for me using mocha 2.0.1 and node v0.10.25

**Comment by boneskull** [comment]
not stale

**Comment by JoshuaKGoldberg** [comment]
> The affected code is here (I am going to leave this branch there until this issue is resolved):
> https://github.com/jsloader/flow-inspector/tree/mocha-bug

😞 in the >10 years since this issue was posted, that branch has been deleted.

> This is also happening for me using mocha 2.0.1 and node v0.10.25

Mocha is now on version 10 and Node LTS maintenance is now 18.

---

I can't personally reproduce this issue in the latest stable versions of Mocha and Node, so closing it out. We're a new maintenance team (#5027) so might be missing context that's key here. Apologies if so. Please do file an issue using the new templates with a reproduction we can work with if you're still seeing this. Thanks all!
